"""Safety graph seed edges — intervention ↔ medication/condition/organ relationships."""

from __future__ import annotations

from app.models.enums import SafetyRelationshipType, SafetyRiskLevel, SafetyWarningEvidenceLevel

# Each edge:
# intervention (lowercase canonical), relationship, target, severity, mechanism, evidence_level, citations, note
SAFETY_GRAPH_EDGES: list[dict] = [
    # Drug interactions (INTERACTS_WITH)
    {"intervention": "curcumin", "relationship": SafetyRelationshipType.INTERACTS_WITH, "target": "Warfarin",
     "severity": SafetyRiskLevel.MODERATE, "mechanism": "May increase bleeding risk via antiplatelet activity.",
     "evidence_level": SafetyWarningEvidenceLevel.RCT, "citations": ["PMID:17211725"]},
    {"intervention": "curcumin", "relationship": SafetyRelationshipType.INTERACTS_WITH, "target": "Apixaban",
     "severity": SafetyRiskLevel.MODERATE, "mechanism": "Potential additive anticoagulant/bleeding risk.",
     "evidence_level": SafetyWarningEvidenceLevel.MECHANISTIC, "citations": []},
    {"intervention": "berberine", "relationship": SafetyRelationshipType.INTERACTS_WITH, "target": "Metformin",
     "severity": SafetyRiskLevel.MODERATE, "mechanism": "May potentiate hypoglycemia.",
     "evidence_level": SafetyWarningEvidenceLevel.RCT, "citations": ["PMID:18442638"]},
    {"intervention": "berberine", "relationship": SafetyRelationshipType.INTERACTS_WITH, "target": "Insulin",
     "severity": SafetyRiskLevel.MODERATE, "mechanism": "Additive glucose-lowering effect.",
     "evidence_level": SafetyWarningEvidenceLevel.OBSERVATIONAL, "citations": []},
    {"intervention": "berberine", "relationship": SafetyRelationshipType.INTERACTS_WITH, "target": "Cyclosporine",
     "severity": SafetyRiskLevel.HIGH, "mechanism": "CYP3A4/P-gp inhibition may raise cyclosporine levels.",
     "evidence_level": SafetyWarningEvidenceLevel.MECHANISTIC, "citations": []},
    {"intervention": "omega-3", "relationship": SafetyRelationshipType.INTERACTS_WITH, "target": "Warfarin",
     "severity": SafetyRiskLevel.MODERATE, "mechanism": "High-dose omega-3 may increase bleeding risk.",
     "evidence_level": SafetyWarningEvidenceLevel.META_ANALYSIS, "citations": ["PMID:19211485"]},
    {"intervention": "st. john's wort", "relationship": SafetyRelationshipType.INTERACTS_WITH, "target": "Warfarin",
     "severity": SafetyRiskLevel.HIGH, "mechanism": "CYP induction may reduce anticoagulant efficacy.",
     "evidence_level": SafetyWarningEvidenceLevel.OBSERVATIONAL, "citations": []},
    {"intervention": "st. john's wort", "relationship": SafetyRelationshipType.INTERACTS_WITH, "target": "Sertraline",
     "severity": SafetyRiskLevel.HIGH, "mechanism": "Serotonergic interaction; serotonin syndrome risk.",
     "evidence_level": SafetyWarningEvidenceLevel.OBSERVATIONAL, "citations": []},
    {"intervention": "ginkgo", "relationship": SafetyRelationshipType.INTERACTS_WITH, "target": "Warfarin",
     "severity": SafetyRiskLevel.MODERATE, "mechanism": "Additive antiplatelet effect.",
     "evidence_level": SafetyWarningEvidenceLevel.RCT, "citations": []},
    {"intervention": "garlic", "relationship": SafetyRelationshipType.INTERACTS_WITH, "target": "Warfarin",
     "severity": SafetyRiskLevel.MODERATE, "mechanism": "May increase bleeding risk.",
     "evidence_level": SafetyWarningEvidenceLevel.MECHANISTIC, "citations": []},
    {"intervention": "allicin", "relationship": SafetyRelationshipType.INTERACTS_WITH, "target": "Warfarin",
     "severity": SafetyRiskLevel.MODERATE, "mechanism": "May increase bleeding risk.",
     "evidence_level": SafetyWarningEvidenceLevel.MECHANISTIC, "citations": []},
    {"intervention": "ashwagandha", "relationship": SafetyRelationshipType.INTERACTS_WITH, "target": "Levothyroxine",
     "severity": SafetyRiskLevel.MODERATE, "mechanism": "May increase thyroid hormone levels; monitor TSH.",
     "evidence_level": SafetyWarningEvidenceLevel.OBSERVATIONAL, "citations": []},
    {"intervention": "ashwagandha", "relationship": SafetyRelationshipType.INTERACTS_WITH, "target": "Cyclosporine",
     "severity": SafetyRiskLevel.MODERATE, "mechanism": "Immune-stimulating activity may counteract immunosuppression.",
     "evidence_level": SafetyWarningEvidenceLevel.MECHANISTIC, "citations": []},
    {"intervention": "alpha lipoic acid", "relationship": SafetyRelationshipType.INTERACTS_WITH, "target": "Insulin",
     "severity": SafetyRiskLevel.MODERATE, "mechanism": "May potentiate hypoglycemia.",
     "evidence_level": SafetyWarningEvidenceLevel.RCT, "citations": []},
    {"intervention": "chromium", "relationship": SafetyRelationshipType.INTERACTS_WITH, "target": "Insulin",
     "severity": SafetyRiskLevel.MODERATE, "mechanism": "May potentiate hypoglycemia.",
     "evidence_level": SafetyWarningEvidenceLevel.OBSERVATIONAL, "citations": []},
    {"intervention": "milk thistle", "relationship": SafetyRelationshipType.INTERACTS_WITH, "target": "Atorvastatin",
     "severity": SafetyRiskLevel.LOW, "mechanism": "Possible CYP-mediated statin metabolism interaction.",
     "evidence_level": SafetyWarningEvidenceLevel.MECHANISTIC, "citations": []},
    {"intervention": "coq10", "relationship": SafetyRelationshipType.INTERACTS_WITH, "target": "Warfarin",
     "severity": SafetyRiskLevel.LOW, "mechanism": "Structural similarity to vitamin K may affect INR.",
     "evidence_level": SafetyWarningEvidenceLevel.OBSERVATIONAL, "citations": []},
    {"intervention": "boswellia serrata", "relationship": SafetyRelationshipType.INTERACTS_WITH, "target": "Warfarin",
     "severity": SafetyRiskLevel.MODERATE, "mechanism": "May potentiate anticoagulant effect.",
     "evidence_level": SafetyWarningEvidenceLevel.MECHANISTIC, "citations": []},
    # Condition contraindications / cautions
    {"intervention": "berberine", "relationship": SafetyRelationshipType.CONTRAINDICATED_IN, "target": "pregnancy",
     "severity": SafetyRiskLevel.CONTRAINDICATED, "mechanism": "Insufficient safety data; potential uterotonic activity.",
     "evidence_level": SafetyWarningEvidenceLevel.ANIMAL, "citations": []},
    {"intervention": "ashwagandha", "relationship": SafetyRelationshipType.CONTRAINDICATED_IN, "target": "pregnancy",
     "severity": SafetyRiskLevel.CONTRAINDICATED, "mechanism": "Insufficient human safety data in pregnancy.",
     "evidence_level": SafetyWarningEvidenceLevel.TRADITIONAL, "citations": []},
    {"intervention": "curcumin", "relationship": SafetyRelationshipType.USE_WITH_CAUTION, "target": "pregnancy",
     "severity": SafetyRiskLevel.MODERATE, "mechanism": "High-dose extracts lack robust pregnancy safety data.",
     "evidence_level": SafetyWarningEvidenceLevel.OBSERVATIONAL, "citations": []},
    {"intervention": "magnesium", "relationship": SafetyRelationshipType.USE_WITH_CAUTION, "target": "kidney_disease",
     "severity": SafetyRiskLevel.HIGH, "mechanism": "Reduced renal clearance may increase hypermagnesemia risk.",
     "evidence_level": SafetyWarningEvidenceLevel.OBSERVATIONAL, "citations": []},
    {"intervention": "potassium", "relationship": SafetyRelationshipType.CONTRAINDICATED_IN, "target": "kidney_disease",
     "severity": SafetyRiskLevel.CONTRAINDICATED, "mechanism": "Hyperkalemia risk with impaired renal excretion.",
     "evidence_level": SafetyWarningEvidenceLevel.OBSERVATIONAL, "citations": []},
    {"intervention": "ashwagandha", "relationship": SafetyRelationshipType.USE_WITH_CAUTION, "target": "autoimmune_disease",
     "severity": SafetyRiskLevel.MODERATE, "mechanism": "Immune-stimulating properties; caution on immunosuppressants.",
     "evidence_level": SafetyWarningEvidenceLevel.MECHANISTIC, "citations": []},
    {"intervention": "echinacea", "relationship": SafetyRelationshipType.USE_WITH_CAUTION, "target": "autoimmune_disease",
     "severity": SafetyRiskLevel.MODERATE, "mechanism": "Immune-modulating effects may be undesirable.",
     "evidence_level": SafetyWarningEvidenceLevel.MECHANISTIC, "citations": []},
    {"intervention": "ashwagandha", "relationship": SafetyRelationshipType.USE_WITH_CAUTION, "target": "thyroid_disease",
     "severity": SafetyRiskLevel.MODERATE, "mechanism": "May increase thyroid hormone activity.",
     "evidence_level": SafetyWarningEvidenceLevel.OBSERVATIONAL, "citations": []},
    # Organ cautions (from labs + conditions)
    {"intervention": "egcg", "relationship": SafetyRelationshipType.CAUTION_IN, "target": "liver",
     "severity": SafetyRiskLevel.MODERATE, "mechanism": "Concentrated green tea extract linked to rare hepatotoxicity at high doses.",
     "evidence_level": SafetyWarningEvidenceLevel.OBSERVATIONAL, "citations": ["PMID:21164020"]},
    {"intervention": "green tea extract", "relationship": SafetyRelationshipType.CAUTION_IN, "target": "liver",
     "severity": SafetyRiskLevel.MODERATE, "mechanism": "High-dose catechin extracts require liver monitoring.",
     "evidence_level": SafetyWarningEvidenceLevel.OBSERVATIONAL, "citations": []},
    {"intervention": "vitamin a", "relationship": SafetyRelationshipType.CAUTION_IN, "target": "liver",
     "severity": SafetyRiskLevel.MODERATE, "mechanism": "High-dose retinol associated with hepatotoxicity.",
     "evidence_level": SafetyWarningEvidenceLevel.OBSERVATIONAL, "citations": []},
    {"intervention": "niacin", "relationship": SafetyRelationshipType.CAUTION_IN, "target": "liver",
     "severity": SafetyRiskLevel.MODERATE, "mechanism": "High-dose niacin may elevate liver enzymes.",
     "evidence_level": SafetyWarningEvidenceLevel.RCT, "citations": []},
]

REGULATED_INTERVENTIONS: dict[str, str] = {
    "bpc-157": "Investigational peptide — evidence context only; not a recommendation to self-administer.",
    "tb-500": "Investigational peptide — evidence context only; not a recommendation to self-administer.",
    "semaglutide": "Prescription GLP-1 agonist — requires physician oversight.",
    "tirzepatide": "Prescription GIP/GLP-1 agonist — requires physician oversight.",
    "liraglutide": "Prescription GLP-1 agonist — requires physician oversight.",
    "exenatide": "Prescription GLP-1 agonist — requires physician oversight.",
    "dulaglutide": "Prescription GLP-1 agonist — requires physician oversight.",
    "tesamorelin": "Prescription GHRH analog — requires physician oversight.",
    "bremelanotide": "Prescription melanocortin agonist — requires physician oversight.",
}


def edges_for_intervention(intervention_name: str) -> list[dict]:
    key = intervention_name.lower().strip()
    return [e for e in SAFETY_GRAPH_EDGES if e["intervention"] == key]