"""initial schema

Revision ID: 44ad2f4e104a
Revises: 
Create Date: 2026-07-06 04:48:49.395120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.mixins


# revision identifiers, used by Alembic.
revision: str = '44ad2f4e104a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biomarkers',
    sa.Column('canonical_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_unit', sa.String(length=30), nullable=True),
    sa.Column('reference_low', sa.Float(), nullable=True),
    sa.Column('reference_high', sa.Float(), nullable=True),
    sa.Column('optimal_low', sa.Float(), nullable=True),
    sa.Column('optimal_high', sa.Float(), nullable=True),
    sa.Column('id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    op.create_table('citations',
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('source', sa.Enum('PUBMED', 'CLINICALTRIALS', 'EUROPEPMC', name='studysource', native_enum=False, length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('study_type', sa.Enum('META_ANALYSIS', 'SYSTEMATIC_REVIEW', 'RCT', 'COHORT', 'CASE_CONTROL', 'PRECLINICAL', name='studytype', native_enum=False, length=30), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('interventions',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.Enum('HERB', 'NUTRACEUTICAL', 'LIFESTYLE', 'PEPTIDE', 'NAD_PRECURSOR', 'FOOD', 'PHYTOCHEMICAL', 'MEDICATION', 'HORMONE', 'ENVIRONMENTAL', 'BEHAVIOR', name='interventioncategory', native_enum=False, length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mechanism', sa.Text(), nullable=True),
    sa.Column('is_regulated', sa.Boolean(), nullable=False),
    sa.Column('regulation_note', sa.Text(), nullable=True),
    sa.Column('id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pathways',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('drug_interactions',
    sa.Column('intervention_id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('drug_name', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CONTRAINDICATED', name='safetyrisklevel', native_enum=False, length=20), nullable=False),
    sa.Column('mechanism', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_claims',
    sa.Column('intervention_id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('biomarker_name', sa.String(length=100), nullable=True),
    sa.Column('pathway_code', sa.String(length=50), nullable=True),
    sa.Column('effect', sa.String(length=50), nullable=False),
    sa.Column('evidence_level', sa.Enum('HIGH', 'MODERATE', 'LOW', 'PRECLINICAL', name='evidencelevel', native_enum=False, length=20), nullable=False),
    sa.Column('pmid', sa.String(length=30), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_compound_sources',
    sa.Column('food_intervention_id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('compound_intervention_id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('richness', sa.Enum('HIGH', 'MODERATE', 'LOW', name='richness', native_enum=False, length=20), nullable=False),
    sa.Column('typical_serving', sa.String(length=150), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['compound_intervention_id'], ['interventions.id'], ),
    sa.ForeignKeyConstraint(['food_intervention_id'], ['interventions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_profiles',
    sa.Column('user_id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('age_range', sa.String(length=20), nullable=True),
    sa.Column('biological_sex', sa.String(length=10), nullable=True),
    sa.Column('health_goals', sa.JSON(), nullable=False),
    sa.Column('current_medications', sa.JSON(), nullable=False),
    sa.Column('current_supplements', sa.JSON(), nullable=False),
    sa.Column('known_conditions', sa.JSON(), nullable=False),
    sa.Column('id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('lab_reports',
    sa.Column('user_id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('encrypted_file_path', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETE', 'FAILED', name='labreportstatus', native_enum=False, length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safety_flags',
    sa.Column('intervention_id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('condition', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('CAUTION', 'CONTRAINDICATION', name='flagseverity', native_enum=False, length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_results',
    sa.Column('lab_report_id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('biomarker_name', sa.String(length=100), nullable=False),
    sa.Column('raw_test_name', sa.String(length=150), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('reference_range_low', sa.Float(), nullable=True),
    sa.Column('reference_range_high', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('CRITICAL_LOW', 'LOW', 'OPTIMAL', 'NORMAL', 'HIGH', 'CRITICAL_HIGH', name='labresultstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lab_report_id'], ['lab_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendation_reports',
    sa.Column('lab_report_id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('user_id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=30), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('biomarker_summary', sa.JSON(), nullable=False),
    sa.Column('pathway_activations', sa.JSON(), nullable=False),
    sa.Column('clinician_questions', sa.JSON(), nullable=False),
    sa.Column('safety_summary', sa.JSON(), nullable=False),
    sa.Column('disclaimer', sa.Text(), nullable=False),
    sa.Column('id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lab_report_id'], ['lab_reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('report_id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('intervention_name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.Enum('HERB', 'NUTRACEUTICAL', 'LIFESTYLE', 'PEPTIDE', 'NAD_PRECURSOR', 'FOOD', 'PHYTOCHEMICAL', 'MEDICATION', 'HORMONE', 'ENVIRONMENTAL', 'BEHAVIOR', name='interventioncategory', native_enum=False, length=30), nullable=False),
    sa.Column('mechanism', sa.Text(), nullable=True),
    sa.Column('evidence_level', sa.Enum('HIGH', 'MODERATE', 'LOW', 'PRECLINICAL', name='evidencelevel', native_enum=False, length=20), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('typical_dose', sa.String(length=255), nullable=True),
    sa.Column('safety_risk', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CONTRAINDICATED', name='safetyrisklevel', native_enum=False, length=20), nullable=False),
    sa.Column('safety_notes', sa.JSON(), nullable=False),
    sa.Column('interactions', sa.JSON(), nullable=False),
    sa.Column('is_regulated', sa.Boolean(), nullable=False),
    sa.Column('cited_study_ids', sa.JSON(), nullable=False),
    sa.Column('cited_urls', sa.JSON(), nullable=False),
    sa.Column('food_sources', sa.JSON(), nullable=True),
    sa.Column('id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['recommendation_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_citations',
    sa.Column('report_id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('study_type', sa.String(length=30), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['recommendation_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_citations')
    op.drop_table('recommendations')
    op.drop_table('recommendation_reports')
    op.drop_table('lab_results')
    op.drop_table('safety_flags')
    op.drop_table('lab_reports')
    op.drop_table('health_profiles')
    op.drop_table('food_compound_sources')
    op.drop_table('evidence_claims')
    op.drop_table('drug_interactions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('pathways')
    op.drop_table('interventions')
    op.drop_table('citations')
    op.drop_table('biomarkers')
    # ### end Alembic commands ###
