"""phase3/4 infra: patient, feedback, user role, lab report patient_id

Revision ID: 8046599e8d21
Revises: c0e36b9c4f3e
Create Date: 2026-07-06 06:43:18.408985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.mixins

# revision identifiers, used by Alembic.
revision: str = '8046599e8d21'
down_revision: Union[str, None] = 'c0e36b9c4f3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('user_id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('biological_sex', sa.String(length=10), nullable=True),
    sa.Column('id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('report_id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('user_id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='feedback_rating_range'),
    sa.ForeignKeyConstraint(['report_id'], ['recommendation_reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lab_reports') as batch_op:
        batch_op.add_column(sa.Column('patient_id', app.models.mixins.GUID(length=36), nullable=True))
        batch_op.create_foreign_key('fk_lab_reports_patient_id', 'patients', ['patient_id'], ['id'])
    with op.batch_alter_table('users') as batch_op:
        # server_default backfills existing rows; SQLAlchemy's Enum(native_enum=False) stores
        # the member *name* ("INDIVIDUAL"), not its .value ("individual").
        batch_op.add_column(
            sa.Column(
                'role',
                sa.Enum('INDIVIDUAL', 'CLINICIAN', name='userrole', native_enum=False, length=20),
                nullable=False,
                server_default='INDIVIDUAL',
            )
        )
        batch_op.add_column(sa.Column('clinic_name', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('clinic_name')
        batch_op.drop_column('role')
    with op.batch_alter_table('lab_reports') as batch_op:
        batch_op.drop_constraint('fk_lab_reports_patient_id', type_='foreignkey')
        batch_op.drop_column('patient_id')
    op.drop_table('feedback')
    op.drop_table('patients')
    # ### end Alembic commands ###
