"""phase1 evidence tiers, compound target layer, ontology expansion

Revision ID: a5d2514aca70
Revises: 44ad2f4e104a
Create Date: 2026-07-06 05:32:33.377729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.mixins

# revision identifiers, used by Alembic.
revision: str = 'a5d2514aca70'
down_revision: Union[str, None] = '44ad2f4e104a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compounds',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('primary_target', sa.String(length=150), nullable=True),
    sa.Column('pubchem_cid', sa.Integer(), nullable=True),
    sa.Column('id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('intervention_compounds',
    sa.Column('intervention_id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('compound_id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.id'], ),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('recommendation_reports', sa.Column('biomarker_interpretations', sa.JSON(), nullable=False))
    op.add_column('recommendations', sa.Column('rationale', sa.Text(), nullable=True))
    op.add_column('recommendations', sa.Column('limitations', sa.Text(), nullable=True))
    op.add_column('recommendations', sa.Column('evidence_tier', sa.Enum('ESTABLISHED', 'EMERGING', 'PRECLINICAL', 'RESEARCH_HYPOTHESIS', 'TRADITIONAL_USE', 'HISTORICAL_ETHNOBOTANICAL', name='evidencetier', native_enum=False, length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'evidence_tier')
    op.drop_column('recommendations', 'limitations')
    op.drop_column('recommendations', 'rationale')
    op.drop_column('recommendation_reports', 'biomarker_interpretations')
    op.drop_table('intervention_compounds')
    op.drop_table('compounds')
    # ### end Alembic commands ###
