"""mvp rescope: 25 biomarkers, biological systems rollup

Revision ID: c0e36b9c4f3e
Revises: a5d2514aca70
Create Date: 2026-07-06 06:23:03.809293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0e36b9c4f3e'
down_revision: Union[str, None] = 'a5d2514aca70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation_reports', sa.Column('biological_systems', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendation_reports', 'biological_systems')
    # ### end Alembic commands ###
