"""response tracking module

Revision ID: c170693719b3
Revises: 8046599e8d21
Create Date: 2026-07-06 13:19:51.470279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.mixins

# revision identifiers, used by Alembic.
revision: str = 'c170693719b3'
down_revision: Union[str, None] = '8046599e8d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_tracking',
    sa.Column('user_id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('patient_id', app.models.mixins.GUID(length=36), nullable=True),
    sa.Column('intervention_name', sa.String(length=150), nullable=False),
    sa.Column('baseline_lab_report_id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('follow_up_lab_report_id', app.models.mixins.GUID(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.mixins.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['baseline_lab_report_id'], ['lab_reports.id'], ),
    sa.ForeignKeyConstraint(['follow_up_lab_report_id'], ['lab_reports.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response_tracking')
    # ### end Alembic commands ###
