"""Classify uploaded lab documents by originating portal / lab vendor."""

from __future__ import annotations

import enum
import re


class LabDocumentProvider(str, enum.Enum):
    HEALOW = "healow"
    MYCHART = "mychart"
    LABCORP = "labcorp"
    QUEST = "quest"
    CLEVELAND_HEARTLAB = "cleveland_heartlab"
    GENERIC = "generic"


_HEALOW_MARKERS = (
    "healow",
    "eclinicalworks",
    "eclinical works",
    "ecw",
    "summary generated by eclinicalworks",
)

_MYCHART_MARKERS = (
    "mychart",
    "my chart",
    "powered by epic",
    "epic systems",
    "epic mychart",
    "compare result trends",
    "result trends",
    "standard range",  # Epic UI label (weigh with other cues)
)

_LABCORP_MARKERS = (
    "labcorp",
    "laboratory corporation of america",
    "laboratory corporation",
)

_QUEST_MARKERS = (
    "quest diagnostics",
    "questdiagnostics",
    "quest lab",
)

_CLEVELAND_MARKERS = (
    "cleveland heartlab",
    "cleveland heart lab",
    "clevelandheartlab",
)


def detect_lab_document_provider(text: str, filename: str = "") -> LabDocumentProvider:
    """Best-effort provider detection from document text and optional filename."""
    haystack = f"{filename}\n{text}".lower()
    fname = (filename or "").lower()

    if any(marker in haystack for marker in _HEALOW_MARKERS):
        return LabDocumentProvider.HEALOW

    # MyChart Result Trends PDFs are often named "Result Trends - CBC..."
    if "result trends" in fname or "mychart" in fname:
        return LabDocumentProvider.MYCHART
    # Strong MyChart branding
    if any(m in haystack for m in ("mychart", "my chart", "powered by epic", "epic systems", "compare result trends")):
        return LabDocumentProvider.MYCHART
    # Epic "Standard Range" + Component layout (common portal export)
    if "standard range" in haystack and (
        "component" in haystack or "test results" in haystack or "result trends" in haystack
    ):
        return LabDocumentProvider.MYCHART

    if any(marker in haystack for marker in _LABCORP_MARKERS):
        return LabDocumentProvider.LABCORP
    if any(marker in haystack for marker in _QUEST_MARKERS):
        return LabDocumentProvider.QUEST
    if any(marker in haystack for marker in _CLEVELAND_MARKERS):
        return LabDocumentProvider.CLEVELAND_HEARTLAB

    # Healow lipid/HbA1c rows often use F-column without explicit branding on excerpt exports.
    if re.search(r"(?m)^F\s+[A-Za-z]", text) and re.search(
        r"(?m)(?:<=\s*\d|<\s*\d|\d+\.\d+\s*[-–]\s*\d+)", text
    ):
        return LabDocumentProvider.HEALOW

    return LabDocumentProvider.GENERIC