"""Stage 7: Report Generator.

Applies the composite confidence scoring formula, ranks surviving
recommendations, and assembles the final structured report.
"""

from app.knowledge_graph.food_seed_data import COMPOUND_TO_FOOD_SOURCES
from app.models.enums import EvidenceLevel, SafetyRiskLevel
from app.schemas.evidence import FoodSourceRead
from app.schemas.pipeline import EvidenceSnippet, NormalizedLabResult, PathwayActivation, SafetyReport, ScoredRecommendation

DISCLAIMER = (
    "⚠️ IMPORTANT DISCLAIMER: This report is generated by an AI system that reasons over "
    "published scientific literature. It is a clinical decision support and research tool, not a medical "
    "device, and does not constitute medical advice, diagnosis, or treatment. Always consult a qualified "
    "healthcare provider before starting, modifying, or stopping any supplement, medication, or lifestyle "
    "intervention."
)

MODEL_VERSION = "0.1.0"

_EVIDENCE_STRENGTH: dict[EvidenceLevel, float] = {
    EvidenceLevel.HIGH: 0.95,
    EvidenceLevel.MODERATE: 0.65,
    EvidenceLevel.LOW: 0.35,
    EvidenceLevel.PRECLINICAL: 0.20,
}

_SAFETY_RISK_SCORE: dict[SafetyRiskLevel, float] = {
    SafetyRiskLevel.LOW: 0.00,
    SafetyRiskLevel.MODERATE: 0.40,
    SafetyRiskLevel.HIGH: 0.75,
    SafetyRiskLevel.CONTRAINDICATED: 1.00,
}


def _study_quality(recommendation: ScoredRecommendation, evidence_by_id: dict[str, EvidenceSnippet]) -> float:
    scores = [
        evidence_by_id[cid].quality_score for cid in recommendation.cited_study_ids if cid in evidence_by_id
    ]
    return sum(scores) / len(scores) if scores else 0.0


def _pathway_relevance(
    recommendation: ScoredRecommendation,
    pathway_activations: list[PathwayActivation],
    intervention_pathways: dict[str, list[str]],
) -> float:
    codes = intervention_pathways.get(recommendation.intervention_name, [])
    if not codes:
        return 0.0
    scores = [a.activation_score for a in pathway_activations if a.pathway_code in codes]
    return sum(scores) / len(scores) if scores else 0.0


def _biomarker_relevance(
    recommendation: ScoredRecommendation,
    pathway_activations: list[PathwayActivation],
    intervention_pathways: dict[str, list[str]],
    total_abnormal: int,
) -> float:
    if total_abnormal == 0:
        return 0.0
    codes = set(intervention_pathways.get(recommendation.intervention_name, []))
    biomarkers: set[str] = set()
    for activation in pathway_activations:
        if activation.pathway_code in codes:
            biomarkers.update(activation.contributing_biomarkers)
    return min(len(biomarkers) / total_abnormal, 1.0)


def score_confidence(
    recommendation: ScoredRecommendation,
    evidence_snippets: list[EvidenceSnippet],
    pathway_activations: list[PathwayActivation],
    intervention_pathways: dict[str, list[str]],
    total_abnormal_biomarkers: int,
) -> float:
    """score = 0.35*evidence_strength + 0.25*study_quality + 0.20*biomarker_relevance
    + 0.10*pathway_relevance + 0.10*(1 - safety_risk)"""
    evidence_by_id = {e.external_id: e for e in evidence_snippets}

    evidence_strength = _EVIDENCE_STRENGTH[recommendation.evidence_level]
    study_quality = _study_quality(recommendation, evidence_by_id)
    biomarker_relevance = _biomarker_relevance(
        recommendation, pathway_activations, intervention_pathways, total_abnormal_biomarkers
    )
    pathway_relevance = _pathway_relevance(recommendation, pathway_activations, intervention_pathways)
    safety_deduction = _SAFETY_RISK_SCORE[recommendation.safety_risk]

    score = (
        0.35 * evidence_strength
        + 0.25 * study_quality
        + 0.20 * biomarker_relevance
        + 0.10 * pathway_relevance
        + 0.10 * (1 - safety_deduction)
    )
    return round(min(max(score, 0.0), 1.0), 4)


def _attach_food_sources(recommendation: ScoredRecommendation) -> list[FoodSourceRead] | None:
    sources = COMPOUND_TO_FOOD_SOURCES.get(recommendation.intervention_name)
    if not sources:
        return None
    return [FoodSourceRead(**s) for s in sources]


def _biomarker_summary(normalized_labs: list[NormalizedLabResult]) -> dict:
    total = len(normalized_labs)
    abnormal = [lab for lab in normalized_labs if lab.status.value not in ("normal", "optimal")]
    normal = total - len(abnormal)
    categories: dict[str, int] = {}
    for lab in abnormal:
        if lab.category:
            categories[lab.category] = categories.get(lab.category, 0) + 1
    return {
        "total_biomarkers": total,
        "abnormal_count": len(abnormal),
        "normal_count": normal,
        "categories_affected": categories,
    }


def _executive_summary(biomarker_pattern_analysis: str, biomarker_summary: dict) -> str:
    if biomarker_pattern_analysis:
        return biomarker_pattern_analysis
    if biomarker_summary["abnormal_count"] == 0:
        return "All measured biomarkers fell within normal reference ranges."
    return (
        f"Your labs show {biomarker_summary['abnormal_count']} of {biomarker_summary['total_biomarkers']} "
        "biomarkers outside their reference range, implicating one or more biological pathways addressed below."
    )


def generate_report(
    normalized_labs: list[NormalizedLabResult],
    pathway_activations: list[PathwayActivation],
    evidence_snippets: list[EvidenceSnippet],
    safety_report: SafetyReport,
    biomarker_pattern_analysis: str,
    clinician_questions: list[str],
    intervention_pathways: dict[str, list[str]],
) -> dict:
    """Stage 7 entry point: score, rank, and assemble the final report payload (pre-persistence)."""
    biomarker_summary = _biomarker_summary(normalized_labs)
    total_abnormal = biomarker_summary["abnormal_count"]

    scored: list[ScoredRecommendation] = []
    for rec in safety_report.approved_recommendations:
        confidence = score_confidence(
            rec, evidence_snippets, pathway_activations, intervention_pathways, total_abnormal
        )
        rec = rec.model_copy(
            update={
                "confidence_score": confidence,
                "cited_urls": [
                    e.url
                    for e in evidence_snippets
                    if e.external_id in rec.cited_study_ids and e.url
                ],
                "food_sources": _attach_food_sources(rec),
            }
        )
        scored.append(rec)

    scored.sort(key=lambda r: r.confidence_score or 0.0, reverse=True)

    ranked_recommendations = []
    for rank, rec in enumerate(scored, start=1):
        ranked_recommendations.append({**rec.model_dump(mode="json"), "rank": rank})

    overall_confidence = (
        round(sum(r["confidence_score"] for r in ranked_recommendations) / len(ranked_recommendations), 4)
        if ranked_recommendations
        else 0.0
    )

    cited_ids = {cid for rec in scored for cid in rec.cited_study_ids}
    citations = [
        {
            "id": e.external_id,
            "source": e.source.value,
            "title": e.title,
            "year": e.year,
            "study_type": e.study_type.value if e.study_type else None,
            "quality_score": e.quality_score,
        }
        for e in evidence_snippets
        if e.external_id in cited_ids
    ]
    # dedupe citations by id, preserving first occurrence
    seen_ids: set[str] = set()
    deduped_citations = []
    for citation in citations:
        if citation["id"] in seen_ids:
            continue
        seen_ids.add(citation["id"])
        deduped_citations.append(citation)

    high_risk_names = [
        rec.intervention_name
        for rec in scored
        if rec.safety_risk in (SafetyRiskLevel.MODERATE, SafetyRiskLevel.HIGH)
    ]

    return {
        "overall_confidence": overall_confidence,
        "model_version": MODEL_VERSION,
        "executive_summary": _executive_summary(biomarker_pattern_analysis, biomarker_summary),
        "biomarker_summary": biomarker_summary,
        "pathway_activations": [p.model_dump(mode="json") for p in pathway_activations],
        "recommendations": ranked_recommendations,
        "citations": deduped_citations,
        "clinician_questions": clinician_questions,
        "safety_summary": {
            "overall_note": safety_report.overall_note,
            "requires_clinician_review": safety_report.requires_clinician_review,
            "high_risk_interventions": high_risk_names,
        },
        "disclaimer": DISCLAIMER,
    }
