"""Document intelligence pipeline: provider detection, Healow parser, confidence."""

from pathlib import Path

import pytest

from app.pipeline.document_detection import LabDocumentProvider, detect_lab_document_provider
from app.pipeline.lab_parser import parse_lab_document, parse_lab_line
from app.pipeline.parsers.healow import parse_healow_text
from app.pipeline.parse_confidence import score_parsed_result
from app.schemas.pipeline import ParsedLabResult

pytestmark = pytest.mark.unit

_HEALOW_HBA1C = Path(__file__).resolve().parents[1] / "fixtures" / "healow_hba1c_excerpt.txt"
_HEALOW_PDF = Path("/Users/immanuellewis/Downloads/Healow (2).pdf")


def test_detect_healow_from_eclinicalworks_footer():
    text = "Hemoglobin A1c\nF HbA1c 5.9 H < 5.70 (%)\nSummary generated by eClinicalWorks"
    assert detect_lab_document_provider(text) == LabDocumentProvider.HEALOW


def test_detect_labcorp_marker():
    assert detect_lab_document_provider("Laboratory Corporation of America") == LabDocumentProvider.LABCORP


def test_healow_vertical_ferritin_stack_parses():
    text = """
Ferritin
14
L
38-380
ng/mL
"""
    outcome = parse_healow_text(text)
    assert len(outcome.results) == 1
    row = outcome.results[0]
    assert row.raw_test_name == "Ferritin"
    assert row.value == 14.0
    assert row.reference_range_low == 38.0
    assert row.reference_range_high == 380.0
    assert row.parser_pattern == "healow_sliding_window"


def test_healow_merge_wrapped_crp_name():
    text = """
High Sensitivity C-Reactive Protein
1.2
mg/L
0.0-3.0
"""
    outcome = parse_healow_text(text)
    assert outcome.results
    assert outcome.results[0].value == 1.2


def test_healow_ref_phrase_normalization():
    text = "Ferritin 10 ng/mL\nNormal value: 30-100"
    outcome = parse_healow_text(text)
    assert outcome.results


def test_standard_row_regex_pattern():
    parsed = parse_lab_line("Glucose 102 mg/dL 65-99")
    assert parsed is not None
    assert parsed.raw_test_name == "Glucose"
    assert parsed.value == 102.0


def test_flagged_row_regex_pattern():
    parsed = parse_lab_line("Ferritin 12 L ng/mL 38-380")
    assert parsed is not None
    assert parsed.raw_test_name == "Ferritin"
    assert parsed.value == 12.0


def test_inline_reference_range_pattern():
    parsed = parse_lab_line("Vitamin D 25 ng/mL Reference Range: 30-100")
    assert parsed is not None
    assert parsed.reference_range_low == 30.0
    assert parsed.reference_range_high == 100.0


def test_parse_confidence_higher_for_catalog_match():
    row = ParsedLabResult(
        raw_test_name="HbA1c",
        value=5.9,
        unit="%",
        reference_range_low=0.0,
        reference_range_high=5.7,
        parser_pattern="healow_line",
    )
    assert score_parsed_result(row) >= 0.85


def test_document_pipeline_healow_hba1c_excerpt():
    text = _HEALOW_HBA1C.read_text(encoding="utf-8")
    doc = parse_lab_document(text.encode(), "healow_hba1c.txt")
    assert doc.provider == LabDocumentProvider.HEALOW
    assert any(r.raw_test_name == "HbA1c" for r in doc.results)
    assert "healow_parser" in doc.passes_used or "generic_regex" in doc.passes_used


@pytest.mark.skipif(not _HEALOW_PDF.is_file(), reason="Local Healow (2).pdf not available")
def test_document_pipeline_healow_pdf():
    doc = parse_lab_document(_HEALOW_PDF.read_bytes(), _HEALOW_PDF.name)
    assert doc.provider == LabDocumentProvider.HEALOW
    assert any(r.raw_test_name == "HbA1c" for r in doc.results)
    assert doc.results[0].parse_confidence is not None