#!/usr/bin/env python3
"""Pull new intervention *names* from external catalog APIs into HerbaGraph.

Unlike PMID growth (which attaches literature to *existing* catalog names), this
script discovers candidates from:
  - USDA FoodData Central (foods) — needs USDA_KEY for reliable access
  - PubChem autocomplete (compounds / nutrients)
  - ClinicalTrials.gov interventions

Writes:
  - app/knowledge_graph/api_imported_catalog.py  (merged into seed catalogs)
  - ops/intervention_import_last_run.json        (run summary)

Optional:
  - --enqueue-enrichment  queue canonical registry deep enrichment (needs DB)

Examples:
  python3 scripts/import_interventions_from_apis.py --dry-run --limit 80
  python3 scripts/import_interventions_from_apis.py --write --sources usda,pubchem --limit 200
  python3 scripts/import_interventions_from_apis.py --write --sources all --limit 300

Never invents PMIDs. New rows are import candidates until PMID growth / review.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import httpx  # noqa: E402

from app.integrations.intervention_discovery import (  # noqa: E402
    discover_all,
)
from app.knowledge_graph.food_catalog import FOOD_INTERVENTIONS  # noqa: E402
from app.knowledge_graph.herb_catalog import HERB_INTERVENTIONS  # noqa: E402
from app.knowledge_graph.lifestyle_methods_catalog import LIFESTYLE_INTERVENTIONS  # noqa: E402
from app.knowledge_graph.peptide_catalog import PEPTIDE_INTERVENTIONS  # noqa: E402
from app.knowledge_graph.phytochemical_catalog import PHYTOCHEMICAL_COMPOUNDS  # noqa: E402
from app.knowledge_graph.seed_data import INTERVENTIONS  # noqa: E402
from app.knowledge_graph.supplement_catalog import SUPPLEMENT_INTERVENTIONS  # noqa: E402

CATALOG_PATH = ROOT / "app" / "knowledge_graph" / "api_imported_catalog.py"
SUMMARY_PATH = ROOT / "ops" / "intervention_import_last_run.json"


def _existing_names() -> set[str]:
    names: set[str] = set()
    for catalog in (
        INTERVENTIONS,
        FOOD_INTERVENTIONS,
        PHYTOCHEMICAL_COMPOUNDS,
        PEPTIDE_INTERVENTIONS,
        LIFESTYLE_INTERVENTIONS,
        HERB_INTERVENTIONS,
        SUPPLEMENT_INTERVENTIONS,
    ):
        for row in catalog:
            n = row.get("name")
            if n:
                names.add(str(n).strip().lower())
    # Also load current api_imported file if present
    try:
        ns: dict = {}
        exec(CATALOG_PATH.read_text(encoding="utf-8"), ns)
        for row in ns.get("API_IMPORTED_INTERVENTIONS") or []:
            n = row.get("name")
            if n:
                names.add(str(n).strip().lower())
    except Exception:
        pass
    return names


def _load_existing_imported() -> list[dict]:
    if not CATALOG_PATH.is_file():
        return []
    ns: dict = {}
    exec(CATALOG_PATH.read_text(encoding="utf-8"), ns)
    return list(ns.get("API_IMPORTED_INTERVENTIONS") or [])


def _write_catalog(rows: list[dict]) -> None:
    lines = [
        '"""API-imported intervention candidates.',
        "",
        "Auto-generated by scripts/import_interventions_from_apis.py.",
        "Do not invent PMIDs here — run pmid_growth_batch after import.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "API_IMPORTED_INTERVENTIONS: list[dict] = [",
    ]
    for row in rows:
        # Compact but readable single-line dicts
        parts = [
            f"\"name\": {row['name']!r}",
            f"\"category\": {row.get('category', 'supplement')!r}",
            f"\"description\": {row.get('description')!r}",
            f"\"mechanism\": {row.get('mechanism')!r}",
            f"\"is_regulated\": {bool(row.get('is_regulated', False))!r}",
            f"\"compounds\": {row.get('compounds') or []!r}",
            f"\"safety_flags\": {row.get('safety_flags') or []!r}",
            f"\"drug_interactions\": {row.get('drug_interactions') or []!r}",
        ]
        if row.get("import_source"):
            parts.append(f"\"import_source\": {row['import_source']!r}")
        if row.get("import_external_id"):
            parts.append(f"\"import_external_id\": {row['import_external_id']!r}")
        lines.append("    {" + ", ".join(parts) + "},")
    lines.append("]")
    lines.append("")
    CATALOG_PATH.write_text("\n".join(lines), encoding="utf-8")


async def _maybe_enqueue(names: list[str], *, limit: int) -> int:
    from app.database import AsyncSessionLocal
    from app.knowledge_graph.enrichment_worker import enqueue_enrichment

    n = 0
    async with AsyncSessionLocal() as db:
        for name in names[:limit]:
            await enqueue_enrichment(db, query_name=name, priority=60, requested_by="api_import")
            n += 1
        await db.commit()
    return n


async def run(
    *,
    sources: set[str],
    limit: int,
    dry_run: bool,
    enqueue: bool,
    max_per_source: int,
) -> dict:
    existing = _existing_names()
    async with httpx.AsyncClient(timeout=90.0, headers={"User-Agent": "herbagraph-import/1.0"}) as client:
        discovered = await discover_all(
            client, sources=sources, max_per_source=max_per_source
        )

    new_rows: list[dict] = []
    skipped_existing = 0
    by_source: dict[str, int] = {}
    for item in discovered:
        if item.name.lower() in existing:
            skipped_existing += 1
            continue
        row = item.to_catalog_row()
        new_rows.append(row)
        existing.add(item.name.lower())
        by_source[item.source] = by_source.get(item.source, 0) + 1
        if len(new_rows) >= limit:
            break

    merged = _load_existing_imported()
    if not dry_run and new_rows:
        # Merge: keep prior imports, append new
        prior_keys = {str(r.get("name", "")).lower() for r in merged}
        for row in new_rows:
            if row["name"].lower() not in prior_keys:
                merged.append(row)
                prior_keys.add(row["name"].lower())
        _write_catalog(merged)

    enqueued = 0
    if enqueue and not dry_run and new_rows:
        try:
            enqueued = await _maybe_enqueue([r["name"] for r in new_rows], limit=min(limit, 100))
        except Exception as exc:  # noqa: BLE001
            enqueued = -1
            enqueue_error = str(exc)[:200]
        else:
            enqueue_error = None
    else:
        enqueue_error = None

    summary = {
        "sources": sorted(sources),
        "dry_run": dry_run,
        "discovered_raw": len(discovered),
        "skipped_existing": skipped_existing,
        "new_accepted": len(new_rows),
        "by_source": by_source,
        "catalog_total_after": len(merged) if not dry_run else len(_load_existing_imported()),
        "written": not dry_run and bool(new_rows),
        "enqueued_enrichment": enqueued,
        "enqueue_error": enqueue_error,
        "sample_new": [
            {"name": r["name"], "category": r["category"], "source": r.get("import_source")}
            for r in new_rows[:15]
        ],
        "usda_key_hint": "Set USDA_KEY for better FoodData Central results",
    }
    SUMMARY_PATH.parent.mkdir(parents=True, exist_ok=True)
    SUMMARY_PATH.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    return summary


def main() -> int:
    parser = argparse.ArgumentParser(description="Import interventions from external catalog APIs")
    parser.add_argument(
        "--sources",
        default="all",
        help="Comma list: usda,pubchem,clinicaltrials or all (default all)",
    )
    parser.add_argument("--limit", type=int, default=150, help="Max *new* interventions this run")
    parser.add_argument(
        "--max-per-source",
        type=int,
        default=150,
        help="Cap discoveries per API source before dedupe",
    )
    parser.add_argument("--dry-run", action="store_true", help="Discover only; do not write catalog")
    parser.add_argument("--write", action="store_true", help="Write api_imported_catalog.py")
    parser.add_argument(
        "--enqueue-enrichment",
        action="store_true",
        help="Also enqueue new names on enrichment queue (requires DATABASE_URL)",
    )
    args = parser.parse_args()

    if not args.dry_run and not args.write:
        # Safe default
        args.dry_run = True
        print("No --write flag: defaulting to --dry-run")

    raw = args.sources.strip().lower()
    if raw == "all":
        sources = {"usda", "pubchem", "clinicaltrials"}
    else:
        sources = {s.strip() for s in raw.split(",") if s.strip()}

    print(
        f"Intervention API import: sources={sorted(sources)} limit={args.limit} "
        f"write={args.write and not args.dry_run} enqueue={args.enqueue_enrichment}"
    )
    summary = asyncio.run(
        run(
            sources=sources,
            limit=args.limit,
            dry_run=args.dry_run or not args.write,
            enqueue=args.enqueue_enrichment,
            max_per_source=args.max_per_source,
        )
    )
    print(f"Discovered (raw):     {summary['discovered_raw']}")
    print(f"Skipped existing:     {summary['skipped_existing']}")
    print(f"New accepted:         {summary['new_accepted']}")
    print(f"By source:            {summary['by_source']}")
    print(f"Catalog total after:  {summary['catalog_total_after']}")
    print(f"Written:              {summary['written']}")
    if summary.get("sample_new"):
        print("Sample new:")
        for s in summary["sample_new"][:8]:
            print(f"  - [{s['source']}|{s['category']}] {s['name']}")
    print(f"Summary JSON: {SUMMARY_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
