"""200 whole-food interventions."""

FOOD_INTERVENTIONS: list[dict] = [{'name': 'Blueberries',
  'category': 'food',
  'description': 'Vaccinium corymbosum berries.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Kale',
  'category': 'food',
  'description': 'Brassica oleracea acephala.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Broccoli Sprouts',
  'category': 'food',
  'description': 'Young cruciferous sprouts — highest dietary sulforaphane precursor content.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Turmeric Root',
  'category': 'food',
  'description': 'Fresh or dried turmeric rhizome for cooking.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Green Tea',
  'category': 'food',
  'description': 'Brewed Camellia sinensis tea.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Pomegranate',
  'category': 'food',
  'description': 'Punica granatum arils or juice.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Onions',
  'category': 'food',
  'description': 'Allium cepa bulbs.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Blackberries',
  'category': 'food',
  'description': 'Rubus fruticosus berries.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Cooked Tomatoes',
  'category': 'food',
  'description': 'Heat-processed tomato products.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Spinach',
  'category': 'food',
  'description': 'Spinacia oleracea leafy green.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Brussels Sprouts',
  'category': 'food',
  'description': 'Brassica oleracea gemmifera.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Broccoli',
  'category': 'food',
  'description': 'Brassica oleracea florets.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Carrots',
  'category': 'food',
  'description': 'Daucus carota root.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Ginger Root',
  'category': 'food',
  'description': 'Culinary ginger rhizome.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Garlic',
  'category': 'food',
  'description': 'Culinary whole garlic bulb.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Swiss Chard',
  'category': 'food',
  'description': 'Whole food source: Swiss Chard.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Collard Greens',
  'category': 'food',
  'description': 'Whole food source: Collard Greens.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Bok Choy',
  'category': 'food',
  'description': 'Whole food source: Bok Choy.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Arugula',
  'category': 'food',
  'description': 'Whole food source: Arugula.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Watercress',
  'category': 'food',
  'description': 'Whole food source: Watercress.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Cabbage',
  'category': 'food',
  'description': 'Whole food source: Cabbage.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Cauliflower',
  'category': 'food',
  'description': 'Whole food source: Cauliflower.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Kohlrabi',
  'category': 'food',
  'description': 'Whole food source: Kohlrabi.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Turnip Greens',
  'category': 'food',
  'description': 'Whole food source: Turnip Greens.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Mustard Greens',
  'category': 'food',
  'description': 'Whole food source: Mustard Greens.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Beet Greens',
  'category': 'food',
  'description': 'Whole food source: Beet Greens.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Romaine Lettuce',
  'category': 'food',
  'description': 'Whole food source: Romaine Lettuce.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Iceberg Lettuce',
  'category': 'food',
  'description': 'Whole food source: Iceberg Lettuce.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Endive',
  'category': 'food',
  'description': 'Whole food source: Endive.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Escarole',
  'category': 'food',
  'description': 'Whole food source: Escarole.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Radicchio',
  'category': 'food',
  'description': 'Whole food source: Radicchio.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Beets',
  'category': 'food',
  'description': 'Whole food source: Beets.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Sweet Potato',
  'category': 'food',
  'description': 'Whole food source: Sweet Potato.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Yam',
  'category': 'food',
  'description': 'Whole food source: Yam.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Potato',
  'category': 'food',
  'description': 'Whole food source: Potato.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Parsnip',
  'category': 'food',
  'description': 'Whole food source: Parsnip.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Rutabaga',
  'category': 'food',
  'description': 'Whole food source: Rutabaga.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Turnip',
  'category': 'food',
  'description': 'Whole food source: Turnip.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Radish',
  'category': 'food',
  'description': 'Whole food source: Radish.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Daikon',
  'category': 'food',
  'description': 'Whole food source: Daikon.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Celery',
  'category': 'food',
  'description': 'Whole food source: Celery.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Cucumber',
  'category': 'food',
  'description': 'Whole food source: Cucumber.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Zucchini',
  'category': 'food',
  'description': 'Whole food source: Zucchini.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Yellow Squash',
  'category': 'food',
  'description': 'Whole food source: Yellow Squash.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Butternut Squash',
  'category': 'food',
  'description': 'Whole food source: Butternut Squash.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Acorn Squash',
  'category': 'food',
  'description': 'Whole food source: Acorn Squash.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Pumpkin',
  'category': 'food',
  'description': 'Whole food source: Pumpkin.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Eggplant',
  'category': 'food',
  'description': 'Whole food source: Eggplant.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Bell Pepper',
  'category': 'food',
  'description': 'Whole food source: Bell Pepper.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Jalapeño',
  'category': 'food',
  'description': 'Whole food source: Jalapeño.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Tomato',
  'category': 'food',
  'description': 'Whole food source: Tomato.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Cherry Tomatoes',
  'category': 'food',
  'description': 'Whole food source: Cherry Tomatoes.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Red Onion',
  'category': 'food',
  'description': 'Whole food source: Red Onion.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Shallots',
  'category': 'food',
  'description': 'Whole food source: Shallots.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Leeks',
  'category': 'food',
  'description': 'Whole food source: Leeks.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Scallions',
  'category': 'food',
  'description': 'Whole food source: Scallions.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Asparagus',
  'category': 'food',
  'description': 'Whole food source: Asparagus.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Green Beans',
  'category': 'food',
  'description': 'Whole food source: Green Beans.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Snap Peas',
  'category': 'food',
  'description': 'Whole food source: Snap Peas.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Snow Peas',
  'category': 'food',
  'description': 'Whole food source: Snow Peas.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Edamame',
  'category': 'food',
  'description': 'Whole food source: Edamame.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Lima Beans',
  'category': 'food',
  'description': 'Whole food source: Lima Beans.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Black Beans',
  'category': 'food',
  'description': 'Whole food source: Black Beans.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Kidney Beans',
  'category': 'food',
  'description': 'Whole food source: Kidney Beans.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Pinto Beans',
  'category': 'food',
  'description': 'Whole food source: Pinto Beans.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Navy Beans',
  'category': 'food',
  'description': 'Whole food source: Navy Beans.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Chickpeas',
  'category': 'food',
  'description': 'Whole food source: Chickpeas.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Lentils',
  'category': 'food',
  'description': 'Whole food source: Lentils.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Split Peas',
  'category': 'food',
  'description': 'Whole food source: Split Peas.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Tofu',
  'category': 'food',
  'description': 'Whole food source: Tofu.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Tempeh',
  'category': 'food',
  'description': 'Whole food source: Tempeh.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Miso',
  'category': 'food',
  'description': 'Whole food source: Miso.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Natto',
  'category': 'food',
  'description': 'Whole food source: Natto.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Raspberries',
  'category': 'food',
  'description': 'Whole food source: Raspberries.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Strawberries',
  'category': 'food',
  'description': 'Whole food source: Strawberries.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Cranberries',
  'category': 'food',
  'description': 'Whole food source: Cranberries.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Goji Berries',
  'category': 'food',
  'description': 'Whole food source: Goji Berries.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Acai',
  'category': 'food',
  'description': 'Whole food source: Acai.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Mango',
  'category': 'food',
  'description': 'Whole food source: Mango.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Papaya',
  'category': 'food',
  'description': 'Whole food source: Papaya.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Pineapple',
  'category': 'food',
  'description': 'Whole food source: Pineapple.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Banana',
  'category': 'food',
  'description': 'Whole food source: Banana.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Apple',
  'category': 'food',
  'description': 'Whole food source: Apple.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Pear',
  'category': 'food',
  'description': 'Whole food source: Pear.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Grapes',
  'category': 'food',
  'description': 'Whole food source: Grapes.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Purple Grapes',
  'category': 'food',
  'description': 'Whole food source: Purple Grapes.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Red Grapes',
  'category': 'food',
  'description': 'Whole food source: Red Grapes.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Orange',
  'category': 'food',
  'description': 'Whole food source: Orange.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Grapefruit',
  'category': 'food',
  'description': 'Whole food source: Grapefruit.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Lemon',
  'category': 'food',
  'description': 'Whole food source: Lemon.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Lime',
  'category': 'food',
  'description': 'Whole food source: Lime.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Kiwi',
  'category': 'food',
  'description': 'Whole food source: Kiwi.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Cherries',
  'category': 'food',
  'description': 'Whole food source: Cherries.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Peaches',
  'category': 'food',
  'description': 'Whole food source: Peaches.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Plums',
  'category': 'food',
  'description': 'Whole food source: Plums.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Apricots',
  'category': 'food',
  'description': 'Whole food source: Apricots.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Figs',
  'category': 'food',
  'description': 'Whole food source: Figs.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Dates',
  'category': 'food',
  'description': 'Whole food source: Dates.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Prunes',
  'category': 'food',
  'description': 'Whole food source: Prunes.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Avocado',
  'category': 'food',
  'description': 'Whole food source: Avocado.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Coconut',
  'category': 'food',
  'description': 'Whole food source: Coconut.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Olives',
  'category': 'food',
  'description': 'Whole food source: Olives.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Olive Oil',
  'category': 'food',
  'description': 'Whole food source: Olive Oil.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Walnuts',
  'category': 'food',
  'description': 'Whole food source: Walnuts.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Almonds',
  'category': 'food',
  'description': 'Whole food source: Almonds.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Cashews',
  'category': 'food',
  'description': 'Whole food source: Cashews.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Pistachios',
  'category': 'food',
  'description': 'Whole food source: Pistachios.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Pecans',
  'category': 'food',
  'description': 'Whole food source: Pecans.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Hazelnuts',
  'category': 'food',
  'description': 'Whole food source: Hazelnuts.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Brazil Nuts',
  'category': 'food',
  'description': 'Whole food source: Brazil Nuts.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Macadamia Nuts',
  'category': 'food',
  'description': 'Whole food source: Macadamia Nuts.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Pine Nuts',
  'category': 'food',
  'description': 'Whole food source: Pine Nuts.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Sunflower Seeds',
  'category': 'food',
  'description': 'Whole food source: Sunflower Seeds.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Pumpkin Seeds',
  'category': 'food',
  'description': 'Whole food source: Pumpkin Seeds.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Chia Seeds',
  'category': 'food',
  'description': 'Whole food source: Chia Seeds.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Flax Seeds',
  'category': 'food',
  'description': 'Whole food source: Flax Seeds.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Hemp Seeds',
  'category': 'food',
  'description': 'Whole food source: Hemp Seeds.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Sesame Seeds',
  'category': 'food',
  'description': 'Whole food source: Sesame Seeds.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Tahini',
  'category': 'food',
  'description': 'Whole food source: Tahini.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Peanuts',
  'category': 'food',
  'description': 'Whole food source: Peanuts.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Peanut Butter',
  'category': 'food',
  'description': 'Whole food source: Peanut Butter.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Almond Butter',
  'category': 'food',
  'description': 'Whole food source: Almond Butter.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Oats',
  'category': 'food',
  'description': 'Whole food source: Oats.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Steel Cut Oats',
  'category': 'food',
  'description': 'Whole food source: Steel Cut Oats.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Quinoa',
  'category': 'food',
  'description': 'Whole food source: Quinoa.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Brown Rice',
  'category': 'food',
  'description': 'Whole food source: Brown Rice.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Wild Rice',
  'category': 'food',
  'description': 'Whole food source: Wild Rice.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Barley',
  'category': 'food',
  'description': 'Whole food source: Barley.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Buckwheat',
  'category': 'food',
  'description': 'Whole food source: Buckwheat.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Millet',
  'category': 'food',
  'description': 'Whole food source: Millet.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Amaranth',
  'category': 'food',
  'description': 'Whole food source: Amaranth.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Farro',
  'category': 'food',
  'description': 'Whole food source: Farro.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Bulgur',
  'category': 'food',
  'description': 'Whole food source: Bulgur.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Whole Wheat',
  'category': 'food',
  'description': 'Whole food source: Whole Wheat.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Sourdough Bread',
  'category': 'food',
  'description': 'Whole food source: Sourdough Bread.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Rye Bread',
  'category': 'food',
  'description': 'Whole food source: Rye Bread.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Salmon',
  'category': 'food',
  'description': 'Whole food source: Salmon.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Sardines',
  'category': 'food',
  'description': 'Whole food source: Sardines.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Mackerel',
  'category': 'food',
  'description': 'Whole food source: Mackerel.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Anchovies',
  'category': 'food',
  'description': 'Whole food source: Anchovies.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Herring',
  'category': 'food',
  'description': 'Whole food source: Herring.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Trout',
  'category': 'food',
  'description': 'Whole food source: Trout.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Tuna',
  'category': 'food',
  'description': 'Whole food source: Tuna.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Cod',
  'category': 'food',
  'description': 'Whole food source: Cod.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Shrimp',
  'category': 'food',
  'description': 'Whole food source: Shrimp.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Mussels',
  'category': 'food',
  'description': 'Whole food source: Mussels.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Oysters',
  'category': 'food',
  'description': 'Whole food source: Oysters.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Clams',
  'category': 'food',
  'description': 'Whole food source: Clams.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Scallops',
  'category': 'food',
  'description': 'Whole food source: Scallops.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Chicken Breast',
  'category': 'food',
  'description': 'Whole food source: Chicken Breast.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Turkey',
  'category': 'food',
  'description': 'Whole food source: Turkey.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Grass-Fed Beef',
  'category': 'food',
  'description': 'Whole food source: Grass-Fed Beef.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Lamb',
  'category': 'food',
  'description': 'Whole food source: Lamb.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Pork Loin',
  'category': 'food',
  'description': 'Whole food source: Pork Loin.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Eggs',
  'category': 'food',
  'description': 'Whole food source: Eggs.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Greek Yogurt',
  'category': 'food',
  'description': 'Whole food source: Greek Yogurt.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Kefir',
  'category': 'food',
  'description': 'Whole food source: Kefir.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Cottage Cheese',
  'category': 'food',
  'description': 'Whole food source: Cottage Cheese.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Mozzarella',
  'category': 'food',
  'description': 'Whole food source: Mozzarella.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Cheddar',
  'category': 'food',
  'description': 'Whole food source: Cheddar.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Parmesan',
  'category': 'food',
  'description': 'Whole food source: Parmesan.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Feta',
  'category': 'food',
  'description': 'Whole food source: Feta.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Goat Cheese',
  'category': 'food',
  'description': 'Whole food source: Goat Cheese.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Butter',
  'category': 'food',
  'description': 'Whole food source: Butter.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Ghee',
  'category': 'food',
  'description': 'Whole food source: Ghee.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Coconut Oil',
  'category': 'food',
  'description': 'Whole food source: Coconut Oil.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Avocado Oil',
  'category': 'food',
  'description': 'Whole food source: Avocado Oil.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Extra Virgin Olive Oil',
  'category': 'food',
  'description': 'Whole food source: Extra Virgin Olive Oil.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Black Tea',
  'category': 'food',
  'description': 'Whole food source: Black Tea.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'White Tea',
  'category': 'food',
  'description': 'Whole food source: White Tea.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Oolong Tea',
  'category': 'food',
  'description': 'Whole food source: Oolong Tea.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Matcha',
  'category': 'food',
  'description': 'Whole food source: Matcha.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Coffee',
  'category': 'food',
  'description': 'Whole food source: Coffee.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Cocoa',
  'category': 'food',
  'description': 'Whole food source: Cocoa.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Dark Chocolate',
  'category': 'food',
  'description': 'Whole food source: Dark Chocolate.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Horseradish',
  'category': 'food',
  'description': 'Whole food source: Horseradish.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Wasabi',
  'category': 'food',
  'description': 'Whole food source: Wasabi.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Kimchi',
  'category': 'food',
  'description': 'Whole food source: Kimchi.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Sauerkraut',
  'category': 'food',
  'description': 'Whole food source: Sauerkraut.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Pickles',
  'category': 'food',
  'description': 'Whole food source: Pickles.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Kombucha',
  'category': 'food',
  'description': 'Whole food source: Kombucha.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Miso Soup',
  'category': 'food',
  'description': 'Whole food source: Miso Soup.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Bone Broth',
  'category': 'food',
  'description': 'Whole food source: Bone Broth.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Chicken Broth',
  'category': 'food',
  'description': 'Whole food source: Chicken Broth.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Vegetable Broth',
  'category': 'food',
  'description': 'Whole food source: Vegetable Broth.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Seaweed',
  'category': 'food',
  'description': 'Whole food source: Seaweed.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Nori',
  'category': 'food',
  'description': 'Whole food source: Nori.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Wakame',
  'category': 'food',
  'description': 'Whole food source: Wakame.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Kelp',
  'category': 'food',
  'description': 'Whole food source: Kelp.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Dulse',
  'category': 'food',
  'description': 'Whole food source: Dulse.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Spirulina Powder',
  'category': 'food',
  'description': 'Whole food source: Spirulina Powder.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Chlorella Powder',
  'category': 'food',
  'description': 'Whole food source: Chlorella Powder.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Nutritional Yeast',
  'category': 'food',
  'description': 'Whole food source: Nutritional Yeast.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Mushrooms',
  'category': 'food',
  'description': 'Whole food source: Mushrooms.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Shiitake Mushrooms',
  'category': 'food',
  'description': 'Whole food source: Shiitake Mushrooms.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Oyster Mushrooms',
  'category': 'food',
  'description': 'Whole food source: Oyster Mushrooms.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Portobello',
  'category': 'food',
  'description': 'Whole food source: Portobello.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Cremini',
  'category': 'food',
  'description': 'Whole food source: Cremini.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Enoki',
  'category': 'food',
  'description': 'Whole food source: Enoki.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'King Oyster Mushroom',
  'category': 'food',
  'description': 'Whole food source: King Oyster Mushroom.',
  'mechanism': None,
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []}]
