"""Food to phytochemical source links."""

FOOD_COMPOUND_SOURCES: list[tuple] = [('Broccoli Sprouts',
  'Sulforaphane',
  'high',
  '1/4 cup fresh sprouts',
  'Roughly 10-100x the glucoraphanin concentration of mature broccoli.'),
 ('Broccoli', 'Sulforaphane', 'moderate', '1 cup steamed', 'Light steaming preserves myrosinase.'),
 ('Brussels Sprouts', 'Sulforaphane', 'moderate', '1 cup cooked', None),
 ('Kale', 'Sulforaphane', 'low', '1-2 cups raw', None),
 ('Garlic',
  'Allicin',
  'high',
  '1-2 cloves crushed, raw',
  'Allicin forms only after crushing/chopping raw garlic; cooking deactivates allinase.'),
 ('Turmeric Root', 'Curcumin', 'high', '1 tsp in cooking or golden milk', None),
 ('Green Tea', 'EGCG', 'high', '2-3 cups brewed', 'Brewed tea; concentrated extracts carry different safety data.'),
 ('Blueberries', 'Anthocyanins', 'high', '1 cup fresh', None),
 ('Blackberries', 'Anthocyanins', 'high', '1 cup fresh', None),
 ('Pomegranate', 'Ellagic Acid', 'high', '1 cup arils or 8oz juice', None),
 ('Cooked Tomatoes',
  'Lycopene',
  'high',
  '1/2 cup tomato sauce',
  'Cooking with oil increases lycopene bioavailability.'),
 ('Onions', 'Quercetin', 'moderate', '1/2 cup raw', 'Red/yellow onions contain more quercetin than white onions.'),
 ('Ginger Root', 'Gingerol', 'moderate', '1 tbsp fresh grated', None),
 ('Carrots', 'Beta-Carotene', 'high', '1 cup raw', None),
 ('Spinach', 'Luteolin', 'low', '2 cups raw', None),
 ('Blueberries', 'Luteolin', 'high', '1 typical serving', None),
 ('Blueberries', 'Myricetin', 'low', 'as part of mixed diet', None),
 ('Kale', 'Lycopene', 'moderate', '1 typical serving', None),
 ('Kale', 'Rutin', 'low', 'as part of mixed diet', None),
 ('Broccoli Sprouts', 'Allicin', 'low', '1 typical serving', None),
 ('Broccoli Sprouts', 'Hesperidin', 'low', 'as part of mixed diet', None),
 ('Turmeric Root', 'Beta-Carotene', 'high', '1 typical serving', None),
 ('Turmeric Root', 'Catechin', 'low', 'as part of mixed diet', None),
 ('Green Tea', 'Piperine', 'moderate', '1 typical serving', None),
 ('Green Tea', 'Epicatechin', 'low', 'as part of mixed diet', None),
 ('Pomegranate', 'Sulforaphane', 'low', '1 typical serving', None),
 ('Pomegranate', 'Procyanidins', 'low', 'as part of mixed diet', None),
 ('Onions', 'Naringenin', 'high', '1 typical serving', None),
 ('Onions', 'Pterostilbene', 'low', 'as part of mixed diet', None),
 ('Blackberries', 'Resveratrol', 'moderate', '1 typical serving', None),
 ('Blackberries', 'Piceatannol', 'low', 'as part of mixed diet', None),
 ('Cooked Tomatoes', 'Anthocyanins', 'low', '1 typical serving', None),
 ('Cooked Tomatoes', 'Boswellic Acids', 'low', 'as part of mixed diet', None),
 ('Spinach', 'Ellagic Acid', 'high', '1 typical serving', None),
 ('Spinach', 'Withanolides', 'low', 'as part of mixed diet', None),
 ('Brussels Sprouts', 'Curcumin', 'moderate', '1 typical serving', None),
 ('Brussels Sprouts', 'Ginsenosides', 'low', 'as part of mixed diet', None),
 ('Broccoli', 'Quercetin', 'low', '1 typical serving', None),
 ('Broccoli', 'Astragalosides', 'low', 'as part of mixed diet', None),
 ('Carrots', 'EGCG', 'high', '1 typical serving', None),
 ('Carrots', 'Palmatine', 'low', 'as part of mixed diet', None),
 ('Ginger Root', 'Silymarin', 'moderate', '1 typical serving', None),
 ('Ginger Root', 'Coptisine', 'low', 'as part of mixed diet', None),
 ('Garlic', 'Apigenin', 'low', '1 typical serving', None),
 ('Garlic', 'Silybin', 'low', 'as part of mixed diet', None),
 ('Swiss Chard', 'Gingerol', 'high', '1 typical serving', None),
 ('Swiss Chard', 'Chlorogenic Acid', 'low', 'as part of mixed diet', None),
 ('Collard Greens', 'Kaempferol', 'moderate', '1 typical serving', None),
 ('Collard Greens', 'Caffeic Acid', 'low', 'as part of mixed diet', None),
 ('Bok Choy', 'Myricetin', 'low', '1 typical serving', None),
 ('Bok Choy', 'Ferulic Acid', 'low', 'as part of mixed diet', None),
 ('Arugula', 'Rutin', 'high', '1 typical serving', None),
 ('Arugula', 'Rosmarinic Acid', 'low', 'as part of mixed diet', None),
 ('Watercress', 'Hesperidin', 'moderate', '1 typical serving', None),
 ('Watercress', 'Carnosic Acid', 'low', 'as part of mixed diet', None),
 ('Cabbage', 'Catechin', 'low', '1 typical serving', None),
 ('Cabbage', 'Carnosol', 'low', 'as part of mixed diet', None),
 ('Cauliflower', 'Epicatechin', 'high', '1 typical serving', None),
 ('Cauliflower', 'Ursolic Acid', 'low', 'as part of mixed diet', None),
 ('Kohlrabi', 'Procyanidins', 'moderate', '1 typical serving', None),
 ('Kohlrabi', 'Oleanolic Acid', 'low', 'as part of mixed diet', None),
 ('Turnip Greens', 'Pterostilbene', 'low', '1 typical serving', None),
 ('Turnip Greens', 'Betulinic Acid', 'low', 'as part of mixed diet', None),
 ('Mustard Greens', 'Piceatannol', 'high', '1 typical serving', None),
 ('Mustard Greens', 'Glycyrrhizin', 'low', 'as part of mixed diet', None),
 ('Beet Greens', 'Boswellic Acids', 'moderate', '1 typical serving', None),
 ('Beet Greens', 'Glabridin', 'low', 'as part of mixed diet', None),
 ('Romaine Lettuce', 'Withanolides', 'low', '1 typical serving', None),
 ('Romaine Lettuce', 'Honokiol', 'low', 'as part of mixed diet', None),
 ('Iceberg Lettuce', 'Ginsenosides', 'high', '1 typical serving', None),
 ('Iceberg Lettuce', 'Magnolol', 'low', 'as part of mixed diet', None),
 ('Endive', 'Astragalosides', 'moderate', '1 typical serving', None),
 ('Endive', 'Baicalin', 'low', 'as part of mixed diet', None),
 ('Escarole', 'Palmatine', 'low', '1 typical serving', None),
 ('Escarole', 'Baicalein', 'low', 'as part of mixed diet', None),
 ('Radicchio', 'Coptisine', 'high', '1 typical serving', None),
 ('Radicchio', 'Wogonin', 'low', 'as part of mixed diet', None),
 ('Beets', 'Silybin', 'moderate', '1 typical serving', None),
 ('Beets', 'Andrographolide', 'low', 'as part of mixed diet', None),
 ('Sweet Potato', 'Chlorogenic Acid', 'low', '1 typical serving', None),
 ('Sweet Potato', 'Picrorhiza Kurroin', 'low', 'as part of mixed diet', None),
 ('Yam', 'Caffeic Acid', 'high', '1 typical serving', None),
 ('Yam', 'Phyllanthin', 'low', 'as part of mixed diet', None),
 ('Potato', 'Ferulic Acid', 'moderate', '1 typical serving', None),
 ('Potato', 'Gymnemic Acids', 'low', 'as part of mixed diet', None),
 ('Parsnip', 'Rosmarinic Acid', 'low', '1 typical serving', None),
 ('Parsnip', 'Gymnemosides', 'low', 'as part of mixed diet', None),
 ('Rutabaga', 'Carnosic Acid', 'high', '1 typical serving', None),
 ('Rutabaga', 'Mangiferin', 'low', 'as part of mixed diet', None),
 ('Turnip', 'Carnosol', 'moderate', '1 typical serving', None),
 ('Turnip', 'Morin', 'low', 'as part of mixed diet', None),
 ('Radish', 'Ursolic Acid', 'low', '1 typical serving', None),
 ('Radish', 'Fisetin', 'low', 'as part of mixed diet', None),
 ('Daikon', 'Oleanolic Acid', 'high', '1 typical serving', None),
 ('Daikon', 'Lutein', 'low', 'as part of mixed diet', None),
 ('Celery', 'Betulinic Acid', 'moderate', '1 typical serving', None),
 ('Celery', 'Zeaxanthin', 'low', 'as part of mixed diet', None),
 ('Cucumber', 'Glycyrrhizin', 'low', '1 typical serving', None),
 ('Cucumber', 'Astaxanthin', 'low', 'as part of mixed diet', None),
 ('Zucchini', 'Glabridin', 'high', '1 typical serving', None),
 ('Zucchini', 'Canthaxanthin', 'low', 'as part of mixed diet', None),
 ('Yellow Squash', 'Honokiol', 'moderate', '1 typical serving', None),
 ('Yellow Squash', 'Capsaicin', 'low', 'as part of mixed diet', None),
 ('Butternut Squash', 'Magnolol', 'low', '1 typical serving', None),
 ('Butternut Squash', 'Dihydrocapsaicin', 'low', 'as part of mixed diet', None),
 ('Acorn Squash', 'Baicalin', 'high', '1 typical serving', None),
 ('Acorn Squash', 'Gingerols', 'low', 'as part of mixed diet', None),
 ('Pumpkin', 'Baicalein', 'moderate', '1 typical serving', None),
 ('Pumpkin', 'Shogaols', 'low', 'as part of mixed diet', None),
 ('Eggplant', 'Wogonin', 'low', '1 typical serving', None),
 ('Eggplant', '6-Gingerol', 'low', 'as part of mixed diet', None),
 ('Bell Pepper', 'Andrographolide', 'high', '1 typical serving', None),
 ('Bell Pepper', 'Allyl Isothiocyanate', 'low', 'as part of mixed diet', None),
 ('Jalapeño', 'Picrorhiza Kurroin', 'moderate', '1 typical serving', None),
 ('Jalapeño', 'Indole-3-Carbinol', 'low', 'as part of mixed diet', None),
 ('Tomato', 'Phyllanthin', 'low', '1 typical serving', None),
 ('Tomato', 'DIM', 'low', 'as part of mixed diet', None),
 ('Cherry Tomatoes', 'Gymnemic Acids', 'high', '1 typical serving', None),
 ('Cherry Tomatoes', 'Sulforaphane Nitrile', 'low', 'as part of mixed diet', None),
 ('Red Onion', 'Gymnemosides', 'moderate', '1 typical serving', None),
 ('Red Onion', 'Glucoraphanin', 'low', 'as part of mixed diet', None),
 ('Shallots', 'Mangiferin', 'low', '1 typical serving', None),
 ('Shallots', 'Sinigrin', 'low', 'as part of mixed diet', None),
 ('Leeks', 'Morin', 'high', '1 typical serving', None),
 ('Leeks', 'Allicin-Derived Diallyl Sulfides', 'low', 'as part of mixed diet', None),
 ('Scallions', 'Fisetin', 'moderate', '1 typical serving', None),
 ('Scallions', 'Diallyl Disulfide', 'low', 'as part of mixed diet', None),
 ('Asparagus', 'Lutein', 'low', '1 typical serving', None),
 ('Asparagus', 'S-Allyl Cysteine', 'low', 'as part of mixed diet', None),
 ('Green Beans', 'Zeaxanthin', 'high', '1 typical serving', None),
 ('Green Beans', 'Theaflavins', 'low', 'as part of mixed diet', None),
 ('Snap Peas', 'Astaxanthin', 'moderate', '1 typical serving', None),
 ('Snap Peas', 'Thearubigins', 'low', 'as part of mixed diet', None),
 ('Snow Peas', 'Canthaxanthin', 'low', '1 typical serving', None),
 ('Snow Peas', 'Chlorophyll', 'low', 'as part of mixed diet', None),
 ('Edamame', 'Capsaicin', 'high', '1 typical serving', None),
 ('Edamame', 'Phycocyanin', 'low', 'as part of mixed diet', None),
 ('Lima Beans', 'Dihydrocapsaicin', 'moderate', '1 typical serving', None),
 ('Lima Beans', 'Phycoerythrin', 'low', 'as part of mixed diet', None),
 ('Black Beans', 'Gingerols', 'low', '1 typical serving', None),
 ('Black Beans', 'Betalains', 'low', 'as part of mixed diet', None),
 ('Kidney Beans', 'Shogaols', 'high', '1 typical serving', None),
 ('Kidney Beans', 'Betanin', 'low', 'as part of mixed diet', None),
 ('Pinto Beans', '6-Gingerol', 'moderate', '1 typical serving', None),
 ('Pinto Beans', 'Phytosterols', 'low', 'as part of mixed diet', None),
 ('Navy Beans', 'Allyl Isothiocyanate', 'low', '1 typical serving', None),
 ('Navy Beans', 'Beta-Sitosterol', 'low', 'as part of mixed diet', None),
 ('Chickpeas', 'Indole-3-Carbinol', 'high', '1 typical serving', None),
 ('Chickpeas', 'Stigmasterol', 'low', 'as part of mixed diet', None),
 ('Lentils', 'DIM', 'moderate', '1 typical serving', None),
 ('Lentils', 'Campesterol', 'low', 'as part of mixed diet', None),
 ('Split Peas', 'Sulforaphane Nitrile', 'low', '1 typical serving', None),
 ('Split Peas', 'Saponins', 'low', 'as part of mixed diet', None),
 ('Tofu', 'Glucoraphanin', 'high', '1 typical serving', None),
 ('Tofu', 'Ginseng Saponins', 'low', 'as part of mixed diet', None),
 ('Tempeh', 'Sinigrin', 'moderate', '1 typical serving', None),
 ('Tempeh', 'Triterpenoid Saponins', 'low', 'as part of mixed diet', None),
 ('Miso', 'Allicin-Derived Diallyl Sulfides', 'low', '1 typical serving', None),
 ('Miso', 'Steroidal Saponins', 'low', 'as part of mixed diet', None),
 ('Natto', 'Diallyl Disulfide', 'high', '1 typical serving', None),
 ('Natto', 'Tannins', 'low', 'as part of mixed diet', None),
 ('Raspberries', 'S-Allyl Cysteine', 'moderate', '1 typical serving', None),
 ('Raspberries', 'Proanthocyanidins', 'low', 'as part of mixed diet', None),
 ('Strawberries', 'Theaflavins', 'low', '1 typical serving', None),
 ('Strawberries', 'OPC', 'low', 'as part of mixed diet', None),
 ('Cranberries', 'Thearubigins', 'high', '1 typical serving', None),
 ('Cranberries', 'Punicalagins', 'low', 'as part of mixed diet', None),
 ('Goji Berries', 'Chlorophyll', 'moderate', '1 typical serving', None),
 ('Goji Berries', 'Delphinidin', 'low', 'as part of mixed diet', None),
 ('Acai', 'Phycocyanin', 'low', '1 typical serving', None),
 ('Acai', 'Cyanidin', 'low', 'as part of mixed diet', None),
 ('Mango', 'Phycoerythrin', 'high', '1 typical serving', None),
 ('Mango', 'Malvidin', 'low', 'as part of mixed diet', None),
 ('Papaya', 'Betalains', 'moderate', '1 typical serving', None),
 ('Papaya', 'Pelargonidin', 'low', 'as part of mixed diet', None),
 ('Pineapple', 'Betanin', 'low', '1 typical serving', None),
 ('Pineapple', 'Peonidin', 'low', 'as part of mixed diet', None),
 ('Banana', 'Phytosterols', 'high', '1 typical serving', None),
 ('Banana', 'Petunidin', 'low', 'as part of mixed diet', None),
 ('Apple', 'Beta-Sitosterol', 'moderate', '1 typical serving', None),
 ('Apple', 'Galangin', 'low', 'as part of mixed diet', None),
 ('Pear', 'Stigmasterol', 'low', '1 typical serving', None),
 ('Pear', 'Chrysin', 'low', 'as part of mixed diet', None),
 ('Grapes', 'Campesterol', 'high', '1 typical serving', None),
 ('Grapes', 'Baicalein-7-Glucuronide', 'low', 'as part of mixed diet', None),
 ('Purple Grapes', 'Saponins', 'moderate', '1 typical serving', None),
 ('Purple Grapes', 'Salidroside', 'low', 'as part of mixed diet', None),
 ('Red Grapes', 'Ginseng Saponins', 'low', '1 typical serving', None),
 ('Red Grapes', 'Rosavin', 'low', 'as part of mixed diet', None),
 ('Orange', 'Triterpenoid Saponins', 'high', '1 typical serving', None),
 ('Orange', 'Tyrosol', 'low', 'as part of mixed diet', None),
 ('Grapefruit', 'Steroidal Saponins', 'moderate', '1 typical serving', None),
 ('Grapefruit', 'Hydroxytyrosol', 'low', 'as part of mixed diet', None),
 ('Lemon', 'Tannins', 'low', '1 typical serving', None),
 ('Lemon', 'Oleuropein', 'low', 'as part of mixed diet', None),
 ('Lime', 'Proanthocyanidins', 'high', '1 typical serving', None),
 ('Lime', 'Oleocanthal', 'low', 'as part of mixed diet', None),
 ('Kiwi', 'OPC', 'moderate', '1 typical serving', None),
 ('Kiwi', 'Oleacein', 'low', 'as part of mixed diet', None),
 ('Cherries', 'Punicalagins', 'low', '1 typical serving', None),
 ('Cherries', 'Verbascoside', 'low', 'as part of mixed diet', None),
 ('Lentils', 'Quercetin', 'low', '1 cup cooked', 'Legumes contribute modest polyphenol intake in whole-food patterns.'),
 ('Black Beans', 'Quercetin', 'low', '1 cup cooked', None),
 ('Sardines', 'Astaxanthin', 'moderate', '3 oz canned', 'Fatty fish provide marine carotenoids alongside EPA/DHA.'),
 ('Oysters', 'Zinc Carnosine', 'low', '3 oz cooked', 'Shellfish are whole-food mineral sources; not equivalent to supplemental zinc carnosine.'),
 ('Eggs', 'Lutein', 'moderate', '2 large eggs', 'Egg yolks are a common dietary lutein source.'),
 ('Nutritional Yeast', 'Beta-Glucans', 'low', '2 tbsp', 'Fortified yeast is used in food-first patterns; check product labels for B12 fortification.'),
 ('Walnuts', 'Ellagic Acid', 'low', '1 oz', None),
 ('Chickpeas', 'Quercetin', 'low', '1 cup cooked', None),
 ('Kefir',
  'Lactoferrin',
  'moderate',
  '1 cup',
  'Fermented dairy provides dietary lactoferrin alongside probiotic cultures.'),
 ('Greek Yogurt',
  'Lactoferrin',
  'low',
  '1 cup',
  'Dairy yogurt is a modest whole-food lactoferrin source; colostrum supplements are more concentrated.')]
