"""Peer-reviewed evidence claims for lifestyle and regulated-context interventions."""

from __future__ import annotations

LIFESTYLE_EVIDENCE_CLAIMS: list[dict] = [
    # Exercise
    {"intervention_name": "HIIT", "biomarker_name": "HbA1c", "pathway_code": "AMPK",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "42222064",
     "recommendation_intent": "primary",
     "summary": "Meta-analysis of RCTs found HIIT improves glycemic control and HbA1c."},
    {"intervention_name": "Tabata Protocol HIIT", "biomarker_name": None, "pathway_code": "AMPK",
     "effect": "increases", "evidence_level": "moderate", "pmid": "8897392",
     "recommendation_intent": "primary",
     "summary": "Original Tabata study demonstrated large gains in aerobic and anaerobic capacity."},
    {"intervention_name": "Sprint Interval Training", "biomarker_name": "Glucose", "pathway_code": "INSULIN_PI3K_AKT",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "27115137",
     "recommendation_intent": "primary",
     "summary": "Low-volume SIT improved insulin sensitivity comparable to traditional endurance training."},
    {"intervention_name": "Norwegian 4×4 HIIT", "biomarker_name": None, "pathway_code": "AMPK",
     "effect": "increases", "evidence_level": "moderate", "pmid": "17414804",
     "recommendation_intent": "primary",
     "summary": "4×4 interval protocol significantly increased VO₂max in controlled trials."},
    {"intervention_name": "Moderate Continuous Training", "biomarker_name": "CRP", "pathway_code": "NF_KB",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "42218635",
     "recommendation_intent": "primary",
     "summary": "Systematic review found regular aerobic exercise reduces systemic inflammation."},
    {"intervention_name": "Resistance Training (Progressive Overload)", "biomarker_name": "Glucose", "pathway_code": "INSULIN_PI3K_AKT",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "42248329",
     "recommendation_intent": "primary",
     "summary": "Resistance training improves insulin sensitivity and glycemic control in meta-analysis."},
    {"intervention_name": "Zone 2 Aerobic Training", "biomarker_name": "Triglycerides", "pathway_code": "HEPATIC_LIPID",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "26726802",
     "recommendation_intent": "collateral",
     "summary": "Moderate aerobic training reduces triglycerides and improves lipid oxidation."},
    {"intervention_name": "Concurrent Aerobic + Resistance Training", "biomarker_name": "HbA1c", "pathway_code": "AMPK",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "29355852",
     "recommendation_intent": "primary",
     "summary": "Combined training improved HbA1c more than either modality alone in T2DM trials."},
    {"intervention_name": "Low-Volume HIIT", "biomarker_name": None, "pathway_code": "AMPK",
     "effect": "increases", "evidence_level": "moderate", "pmid": "27115137",
     "recommendation_intent": "primary",
     "summary": "Brief HIIT sessions improved cardiorespiratory fitness with minimal weekly time."},
    {"intervention_name": "Yoga (Hatha, Structured Sessions)", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "42329542",
     "recommendation_intent": "primary",
     "summary": "Meta-analysis found yoga reduces perceived stress and cortisol markers."},
    {"intervention_name": "Nordic Walking", "biomarker_name": None, "pathway_code": "AMPK",
     "effect": "increases", "evidence_level": "moderate", "pmid": "23418444",
     "recommendation_intent": "collateral",
     "summary": "RCTs show Nordic walking improves VO₂max and functional capacity vs. standard walking."},
    # Sleep
    {"intervention_name": "Sleep Hygiene Optimization", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "42325726",
     "recommendation_intent": "primary",
     "summary": "Sleep hygiene components improve sleep quality as part of multicomponent insomnia care."},
    {"intervention_name": "Cognitive Behavioral Therapy for Insomnia (CBT-I)", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "decreases", "evidence_level": "high", "pmid": "26054060",
     "recommendation_intent": "primary",
     "summary": "AASM guideline: CBT-I is first-line treatment for chronic insomnia."},
    {"intervention_name": "Stimulus Control Therapy", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "26054060",
     "recommendation_intent": "primary",
     "summary": "Stimulus control is an evidence-based CBT-I component for sleep-onset and maintenance insomnia."},
    {"intervention_name": "Sleep Restriction Therapy", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "decreases", "evidence_level": "high", "pmid": "26054060",
     "recommendation_intent": "primary",
     "summary": "Sleep restriction consolidates sleep and improves efficiency in insomnia RCTs."},
    {"intervention_name": "Progressive Muscle Relaxation for Sleep", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "41633054",
     "recommendation_intent": "collateral",
     "summary": "PMR reduced sleep latency and improved sleep quality in insomnia trials."},
    {"intervention_name": "4-7-8 Breathing for Sleep Onset", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "decreases", "evidence_level": "low", "pmid": "42385999",
     "recommendation_intent": "collateral",
     "summary": "Slow-paced breathing techniques reduce pre-sleep arousal in relaxation trials."},
    {"intervention_name": "Bright Light Therapy (Morning)", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "increases", "evidence_level": "moderate", "pmid": "41088238",
     "recommendation_intent": "primary",
     "summary": "Morning bright light therapy advances circadian phase and improves insomnia symptoms."},
    {"intervention_name": "Chronotherapy (Fixed Sleep-Wake Schedule)", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "increases", "evidence_level": "moderate", "pmid": "42226561",
     "recommendation_intent": "primary",
     "summary": "Regular sleep-wake timing is a core behavioral intervention for circadian rhythm disorders."},
    {"intervention_name": "Temperature Regulation for Sleep", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "increases", "evidence_level": "moderate", "pmid": "31102877",
     "recommendation_intent": "collateral",
     "summary": "Warm bath before bed improved sleep onset via distal-proximal temperature gradient."},
    {"intervention_name": "Digital CBT-I (Sleepio/shleep)", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "decreases", "evidence_level": "high", "pmid": "42354226",
     "recommendation_intent": "primary",
     "summary": "Digital CBT-I demonstrated efficacy comparable to in-person CBT-I in RCTs."},
    {"intervention_name": "Mindfulness-Based Therapy for Insomnia (MBTI)", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "25142566",
     "recommendation_intent": "primary",
     "summary": "MBTI improved insomnia severity and sleep quality in randomized trials."},
    # Stress reduction
    {"intervention_name": "Mindfulness-Based Stress Reduction", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "24395196",
     "recommendation_intent": "primary",
     "summary": "Meta-analysis of MBSR RCTs demonstrated stress and anxiety reduction."},
    {"intervention_name": "Box Breathing (4-4-4-4)", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "decreases", "evidence_level": "low", "pmid": "42385999",
     "recommendation_intent": "collateral",
     "summary": "Paced equal-ratio breathing reduces acute stress and improves HRV in controlled studies."},
    {"intervention_name": "4-7-8 Breathing (Paced Relaxation)", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "decreases", "evidence_level": "low", "pmid": "42385999",
     "recommendation_intent": "collateral",
     "summary": "Extended-exhale paced breathing activates parasympathetic responses."},
    {"intervention_name": "Diaphragmatic Breathing (6 breaths/minute)", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "18425203",
     "recommendation_intent": "primary",
     "summary": "Resonance-frequency breathing at 6 breaths/min maximizes HRV and reduces anxiety."},
    {"intervention_name": "Transcendental Meditation", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "24107199",
     "recommendation_intent": "primary",
     "summary": "Meta-analysis found TM reduces psychological stress and blood pressure."},
    {"intervention_name": "Loving-Kindness Meditation (Metta)", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "41906043",
     "recommendation_intent": "collateral",
     "summary": "Loving-kindness meditation increased positive affect and reduced pain in trials."},
    {"intervention_name": "Body Scan Meditation (MBSR)", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "24395196",
     "recommendation_intent": "collateral",
     "summary": "Body scan practice within MBSR reduces stress and improves interoceptive awareness."},
    {"intervention_name": "HRV Biofeedback", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "18425203",
     "recommendation_intent": "primary",
     "summary": "HRV biofeedback reduces anxiety and improves autonomic balance in meta-analyses."},
    {"intervention_name": "Yoga Nidra (Guided Deep Relaxation)", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "42329542",
     "recommendation_intent": "collateral",
     "summary": "Yogic relaxation practices reduce perceived stress in controlled trials."},
    {"intervention_name": "Progressive Muscle Relaxation (Jacobson)", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "41633054",
     "recommendation_intent": "primary",
     "summary": "PMR reduces anxiety and somatic tension in meta-analyses of RCTs."},
    {"intervention_name": "Mindfulness-Based Cognitive Therapy (MBCT)", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "22351472",
     "recommendation_intent": "primary",
     "summary": "MBCT reduces depression relapse and stress-related symptoms in RCTs."},
    # Behavior
    {"intervention_name": "Intermittent Fasting", "biomarker_name": "Insulin", "pathway_code": "AMPK",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "29754952",
     "recommendation_intent": "primary",
     "summary": "Time-restricted eating improved fasting insulin in controlled feeding trials."},
    {"intervention_name": "5:2 Intermittent Fasting", "biomarker_name": "Glucose", "pathway_code": "AMPK",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "41928885",
     "recommendation_intent": "primary",
     "summary": "5:2 intermittent fasting improved insulin sensitivity in overweight women."},
    {"intervention_name": "Alternate-Day Fasting", "biomarker_name": "CRP", "pathway_code": "NF_KB",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "37139450",
     "recommendation_intent": "primary",
     "summary": "Systematic review of human IF trials reported reductions in circulating inflammatory markers including CRP."},
    {"intervention_name": "Mediterranean Diet (PREDIMED Protocol)", "biomarker_name": "CRP", "pathway_code": "NF_KB",
     "effect": "decreases", "evidence_level": "high", "pmid": "29897866",
     "recommendation_intent": "primary",
     "summary": "PREDIMED trial demonstrated cardiovascular and inflammatory benefits of Mediterranean diet."},
    {"intervention_name": "DASH Diet", "biomarker_name": None, "pathway_code": "RENAL_FILTRATION",
     "effect": "decreases", "evidence_level": "high", "pmid": "11136953",
     "recommendation_intent": "primary",
     "summary": "Original DASH trial showed significant blood pressure reduction."},
    {"intervention_name": "Low FODMAP Diet (3-Phase Monash)", "biomarker_name": None, "pathway_code": "GI_MUCOSAL_BARRIER",
     "effect": "decreases", "evidence_level": "high", "pmid": "42297316",
     "recommendation_intent": "primary",
     "summary": "Low FODMAP diet reduced IBS symptoms in randomized controlled trials."},
    {"intervention_name": "Gluten Elimination Diet", "biomarker_name": None, "pathway_code": "FOOD_ANTIGEN_EXPOSURE",
     "effect": "decreases", "evidence_level": "high", "pmid": "42353892",
     "recommendation_intent": "primary",
     "summary": "Strict gluten elimination is the only effective treatment for celiac disease."},
    {"intervention_name": "Early Time-Restricted Eating", "biomarker_name": "Glucose", "pathway_code": "INSULIN_PI3K_AKT",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "29754952",
     "recommendation_intent": "primary",
     "summary": "Early TRE improved insulin sensitivity and blood pressure in prediabetic adults."},
    {"intervention_name": "Caloric Restriction (25% Deficit)", "biomarker_name": "CRP", "pathway_code": "NF_KB",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "26187233",
     "recommendation_intent": "collateral",
     "summary": "CALERIE trial showed sustained caloric restriction improved cardiometabolic markers."},
    {"intervention_name": "Whole-Food Plant-Based Diet", "biomarker_name": "LDL", "pathway_code": "HEPATIC_LIPID",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "26739038",
     "recommendation_intent": "primary",
     "summary": "Plant-based dietary patterns reduced LDL and cardiovascular risk factors in trials."},
    {"intervention_name": "Portfolio Diet", "biomarker_name": "LDL", "pathway_code": "HEPATIC_LIPID",
     "effect": "decreases", "evidence_level": "high", "pmid": "15337784",
     "recommendation_intent": "primary",
     "summary": "Portfolio diet reduced LDL comparable to low-dose statin in original RCT."},
    # Medication context (context_only)
    {"intervention_name": "Metformin", "biomarker_name": "HbA1c", "pathway_code": "AMPK",
     "effect": "decreases", "evidence_level": "high", "pmid": "42396722",
     "recommendation_intent": "context_only",
     "summary": "Metformin is first-line pharmacotherapy for type 2 diabetes per ADA guidelines."},
    {"intervention_name": "Atorvastatin", "biomarker_name": "LDL", "pathway_code": "HEPATIC_LIPID",
     "effect": "decreases", "evidence_level": "high", "pmid": "15325833",
     "recommendation_intent": "context_only",
     "summary": "Statin therapy reduces LDL and major adverse cardiovascular events."},
    {"intervention_name": "Lisinopril", "biomarker_name": None, "pathway_code": "RENAL_FILTRATION",
     "effect": "decreases", "evidence_level": "high", "pmid": "42262532",
     "recommendation_intent": "context_only",
     "summary": "ACE inhibitors reduce blood pressure and provide renal protection in diabetes."},
    {"intervention_name": "Losartan", "biomarker_name": None, "pathway_code": "RENAL_FILTRATION",
     "effect": "decreases", "evidence_level": "high", "pmid": "29907995",
     "recommendation_intent": "context_only",
     "summary": "ARBs reduce cardiovascular events in hypertension trials."},
    {"intervention_name": "Empagliflozin", "biomarker_name": "HbA1c", "pathway_code": "GLP1_INCRETINS",
     "effect": "decreases", "evidence_level": "high", "pmid": "38777127",
     "recommendation_intent": "context_only",
     "summary": "EMPAREG-OUTCOME trial established empagliflozin cardiovascular benefits."},
    {"intervention_name": "Omeprazole", "biomarker_name": None, "pathway_code": "GI_MUCOSAL_BARRIER",
     "effect": "increases", "evidence_level": "high", "pmid": "24448652",
     "recommendation_intent": "context_only",
     "summary": "PPI therapy heals erosive esophagitis and controls GERD symptoms in trials."},
    {"intervention_name": "Sertraline", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "decreases", "evidence_level": "high", "pmid": "41062142",
     "recommendation_intent": "context_only",
     "summary": "SSRIs are first-line pharmacotherapy for major depressive disorder."},
    {"intervention_name": "Levothyroxine", "biomarker_name": "TSH", "pathway_code": "THYROID_HPT",
     "effect": "decreases", "evidence_level": "high", "pmid": "42363246",
     "recommendation_intent": "context_only",
     "summary": "Levothyroxine normalizes TSH in hypothyroidism per ATA guidelines."},
    {"intervention_name": "Low-Dose Aspirin", "biomarker_name": None, "pathway_code": "NF_KB",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "41698380",
     "recommendation_intent": "context_only",
     "summary": "Low-dose aspirin reduces cardiovascular events in select high-risk populations."},
    {"intervention_name": "Warfarin", "biomarker_name": None, "pathway_code": "NF_KB",
     "effect": "decreases", "evidence_level": "high", "pmid": "42322916",
     "recommendation_intent": "context_only",
     "summary": "Warfarin anticoagulation prevents stroke in atrial fibrillation trials."},
    {"intervention_name": "Ezetimibe", "biomarker_name": "LDL", "pathway_code": "HEPATIC_LIPID",
     "effect": "decreases", "evidence_level": "high", "pmid": "36763180",
     "recommendation_intent": "context_only",
     "summary": "IMPROVE-IT trial showed ezetimibe plus statin reduced cardiovascular events."},
    # Hormone context
    {"intervention_name": "GLP-1 Receptor Agonists (Class)", "biomarker_name": "HbA1c", "pathway_code": "GLP1_INCRETINS",
     "effect": "decreases", "evidence_level": "high", "pmid": "42406865",
     "recommendation_intent": "context_only",
     "summary": "GLP-1 RAs reduce HbA1c and body weight in large cardiovascular outcome trials."},
    {"intervention_name": "GLP-1/GIP Dual Agonists (Class)", "biomarker_name": "HbA1c", "pathway_code": "GLP1_INCRETINS",
     "effect": "decreases", "evidence_level": "high", "pmid": "42233555",
     "recommendation_intent": "context_only",
     "summary": "Tirzepatide demonstrated superior glycemic and weight outcomes in SURPASS trials."},
    {"intervention_name": "Testosterone Replacement Therapy", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "increases", "evidence_level": "moderate", "pmid": "24151264",
     "recommendation_intent": "context_only",
     "summary": "TRT improves symptoms and lean mass in men with confirmed hypogonadism."},
    {"intervention_name": "Estradiol Hormone Therapy", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "42304170",
     "recommendation_intent": "context_only",
     "summary": "Menopausal hormone therapy reduces vasomotor symptoms per NAMS evidence review."},
    {"intervention_name": "Somatropin (Growth Hormone)", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "increases", "evidence_level": "moderate", "pmid": "20119884",
     "recommendation_intent": "context_only",
     "summary": "GH replacement improves body composition in adult GH deficiency trials."},
    {"intervention_name": "Desiccated Thyroid (NDT)", "biomarker_name": "TSH", "pathway_code": "THYROID_HPT",
     "effect": "decreases", "evidence_level": "low", "pmid": "42363246",
     "recommendation_intent": "context_only",
     "summary": "Thyroid hormone replacement normalizes TSH; NDT is an alternative formulation in some patients."},
    {"intervention_name": "Progesterone (Bioidentical)", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "42304170",
     "recommendation_intent": "context_only",
     "summary": "Micronized progesterone protects endometrium during estrogen therapy."},
    {"intervention_name": "DHEA Supplementation", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "increases", "evidence_level": "low", "pmid": "41485982",
     "recommendation_intent": "context_only",
     "summary": "DHEA replacement studied in adrenal insufficiency and aging populations."},
    {"intervention_name": "Insulin (Basal-Bolus Regimen)", "biomarker_name": "HbA1c", "pathway_code": "INSULIN_PI3K_AKT",
     "effect": "decreases", "evidence_level": "high", "pmid": "42306490",
     "recommendation_intent": "context_only",
     "summary": "Intensive insulin therapy achieves glycemic targets in type 1 and advanced T2DM."},
    {"intervention_name": "Combined Oral Contraceptives", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "decreases", "evidence_level": "high", "pmid": "41988925",
     "recommendation_intent": "context_only",
     "summary": "Combined OCPs are highly effective contraception with cycle-regulating benefits."},
    {"intervention_name": "Hydrocortisone (Physiologic Replacement)", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "increases", "evidence_level": "moderate", "pmid": "41552007",
     "recommendation_intent": "context_only",
     "summary": "Physiologic hydrocortisone replacement restores cortisol in adrenal insufficiency."},
    # Environmental
    {"intervention_name": "HEPA Air Filtration", "biomarker_name": None, "pathway_code": "NF_KB",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "42146735",
     "recommendation_intent": "collateral",
     "summary": "HEPA filtration reduced indoor PM2.5 and improved cardiovascular markers in trials."},
    {"intervention_name": "Indoor PM2.5 Reduction Protocol", "biomarker_name": None, "pathway_code": "NF_KB",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "42146735",
     "recommendation_intent": "collateral",
     "summary": "Reducing indoor particulate exposure lowers systemic inflammation in intervention studies."},
    {"intervention_name": "Mold Remediation (Professional)", "biomarker_name": None, "pathway_code": "RESPIRATORY_PATHOGEN",
     "effect": "decreases", "evidence_level": "low", "pmid": "39162373",
     "recommendation_intent": "collateral",
     "summary": "Remediation of water-damaged buildings reduces respiratory symptoms in observational studies."},
    {"intervention_name": "Low-VOC Interior Environment", "biomarker_name": None, "pathway_code": "NF_KB",
     "effect": "decreases", "evidence_level": "low", "pmid": "42335033",
     "recommendation_intent": "collateral",
     "summary": "Reducing indoor VOC exposure improves respiratory and irritant symptoms."},
    {"intervention_name": "Nature Exposure (120 min/week)", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "31197192",
     "recommendation_intent": "collateral",
     "summary": "≥120 min/week nature exposure associated with good health and well-being."},
    {"intervention_name": "Morning Daylight Exposure", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "increases", "evidence_level": "moderate", "pmid": "41088238",
     "recommendation_intent": "collateral",
     "summary": "Morning light exposure advances circadian phase and improves mood and alertness."},
    {"intervention_name": "Noise Reduction for Sleep", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "26483933",
     "recommendation_intent": "collateral",
     "summary": "Environmental noise reduction improves sleep quality and reduces awakenings."},
    {"intervention_name": "Water Filtration (Carbon + RO)", "biomarker_name": None, "pathway_code": "RENAL_FILTRATION",
     "effect": "decreases", "evidence_level": "low", "pmid": "42341005",
     "recommendation_intent": "collateral",
     "summary": "Point-of-use filtration reduces drinking-water contaminant exposure."},
    {"intervention_name": "Radon Mitigation", "biomarker_name": None, "pathway_code": "RESPIRATORY_PATHOGEN",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "42245357",
     "recommendation_intent": "collateral",
     "summary": "Radon mitigation reduces lung cancer risk in residential exposure studies."},
    {"intervention_name": "Thermal Comfort Optimization", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "decreases", "evidence_level": "low", "pmid": "31102877",
     "recommendation_intent": "collateral",
     "summary": "Thermal environment optimization supports sleep quality and comfort."},
    {"intervention_name": "Blue-Light Reduction (Evening)", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "increases", "evidence_level": "moderate", "pmid": "30311830",
     "recommendation_intent": "collateral",
     "summary": "Evening blue-light blocking improved sleep quality and melatonin onset in trials."},
]