"""200 phytochemical compound interventions."""

PHYTOCHEMICAL_COMPOUNDS: list[dict] = [{'name': 'Luteolin',
  'category': 'phytochemical',
  'description': 'Flavone with mast cell stabilizing properties.',
  'mechanism': 'NF-κB inhibition and mast cell modulation.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Lycopene',
  'category': 'phytochemical',
  'description': 'Carotenoid from cooked tomatoes.',
  'mechanism': 'LDL oxidation inhibition.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Allicin',
  'category': 'phytochemical',
  'description': 'Organosulfur compound from crushed raw garlic.',
  'mechanism': 'NF-κB inhibition and lipid effects.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': [{'drug_name': 'Warfarin',
                         'severity': 'moderate',
                         'mechanism': 'Antiplatelet activity.',
                         'note': None}]},
 {'name': 'Beta-Carotene',
  'category': 'phytochemical',
  'description': 'Provitamin A carotenoid from carrots.',
  'mechanism': 'Nrf2 activation and vitamin A precursor.',
  'is_regulated': False,
  'safety_flags': [{'condition': 'smoking',
                    'severity': 'contraindication',
                    'note': 'Supplement doses increased lung cancer risk in smokers (ATBC trial).'}],
  'drug_interactions': []},
 {'name': 'Piperine',
  'category': 'phytochemical',
  'description': 'Alkaloid from black pepper.',
  'mechanism': 'Bioavailability enhancer via glucuronidation inhibition.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': [{'drug_name': 'Many medications',
                         'severity': 'moderate',
                         'mechanism': 'CYP and P-gp inhibition.',
                         'note': 'May raise drug levels.'}]},
 {'name': 'Sulforaphane',
  'category': 'phytochemical',
  'description': 'Isothiocyanate from cruciferous glucoraphanin.',
  'mechanism': 'Activates Nrf2 and modulates NF-κB.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Naringenin',
  'category': 'phytochemical',
  'description': 'Flavanone from citrus.',
  'mechanism': 'AMPK and hepatic lipid metabolism.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Resveratrol',
  'category': 'phytochemical',
  'description': 'Stilbene from grapes and berries.',
  'mechanism': 'SIRT1 and AMPK modulation.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Anthocyanins',
  'category': 'phytochemical',
  'description': 'Polyphenol class from berries and purple produce.',
  'mechanism': 'Nrf2 and endothelial function.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Ellagic Acid',
  'category': 'phytochemical',
  'description': 'Polyphenol from pomegranate.',
  'mechanism': 'Nrf2 activation via urolithin metabolites.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Curcumin',
  'category': 'phytochemical',
  'description': 'Curcuminoid from turmeric.',
  'mechanism': 'NF-κB and COX-2 inhibition.',
  'is_regulated': False,
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'High-dose not well studied in pregnancy.'}],
  'drug_interactions': [{'drug_name': 'Warfarin',
                         'severity': 'moderate',
                         'mechanism': 'Antiplatelet activity.',
                         'note': None}]},
 {'name': 'Quercetin',
  'category': 'phytochemical',
  'description': 'Flavonol abundant in onions and apples.',
  'mechanism': 'NF-κB and mast cell stabilization.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'EGCG',
  'category': 'phytochemical',
  'description': 'Epigallocatechin gallate from green tea.',
  'mechanism': 'AMPK activation and NF-κB inhibition.',
  'is_regulated': False,
  'safety_flags': [{'condition': 'liver_disease',
                    'severity': 'caution',
                    'note': 'High-dose extracts rarely hepatotoxic.'}],
  'drug_interactions': []},
 {'name': 'Silymarin',
  'category': 'phytochemical',
  'description': 'Flavonolignan complex from milk thistle.',
  'mechanism': 'Nrf2-mediated hepatocyte protection.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Apigenin',
  'category': 'phytochemical',
  'description': 'Flavone from chamomile and parsley.',
  'mechanism': 'GABA-A modulation and anti-inflammatory effects.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Gingerol',
  'category': 'phytochemical',
  'description': 'Pungent phenolic compound from ginger.',
  'mechanism': 'NF-κB inhibition and GI motility modulation.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Kaempferol',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Kaempferol.',
  'mechanism': 'Affects hepatic lipid metabolism pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Myricetin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Myricetin.',
  'mechanism': 'Supports one-carbon/methylation cycle function.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Rutin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Rutin.',
  'mechanism': 'Influences incretin/GLP-1 signaling pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Hesperidin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Hesperidin.',
  'mechanism': 'Supports mitochondrial NAD+ metabolism.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Catechin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Catechin.',
  'mechanism': 'May influence renal filtration-related pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Epicatechin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Epicatechin.',
  'mechanism': 'Modulates NF-κB inflammatory signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Procyanidins',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Procyanidins.',
  'mechanism': 'Modulates IL-6/JAK-STAT3 inflammatory signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Pterostilbene',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Pterostilbene.',
  'mechanism': 'Influences insulin/PI3K-Akt metabolic signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Piceatannol',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Piceatannol.',
  'mechanism': 'Activates Nrf2 antioxidant response element signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Boswellic Acids',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Boswellic Acids.',
  'mechanism': 'Modulates mTOR/autophagy balance.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Withanolides',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Withanolides.',
  'mechanism': 'Modulates HPA axis stress-response signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Ginsenosides',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Ginsenosides.',
  'mechanism': 'Interacts with thyroid hormone axis signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Astragalosides',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Astragalosides.',
  'mechanism': 'Affects hepatic lipid metabolism pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Palmatine',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Palmatine.',
  'mechanism': 'Supports one-carbon/methylation cycle function.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Coptisine',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Coptisine.',
  'mechanism': 'Influences incretin/GLP-1 signaling pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Silybin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Silybin.',
  'mechanism': 'Influences iron/hepcidin regulation.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Chlorogenic Acid',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Chlorogenic Acid.',
  'mechanism': 'Modulates purine and uric acid metabolism.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Caffeic Acid',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Caffeic Acid.',
  'mechanism': 'Interacts with vitamin D receptor signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Ferulic Acid',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Ferulic Acid.',
  'mechanism': 'May influence renal filtration-related pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Rosmarinic Acid',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Rosmarinic Acid.',
  'mechanism': 'Modulates NF-κB inflammatory signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Carnosic Acid',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Carnosic Acid.',
  'mechanism': 'Modulates IL-6/JAK-STAT3 inflammatory signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Carnosol',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Carnosol.',
  'mechanism': 'Engages AMPK energy-sensing pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Ursolic Acid',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Ursolic Acid.',
  'mechanism': 'Influences insulin/PI3K-Akt metabolic signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Oleanolic Acid',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Oleanolic Acid.',
  'mechanism': 'Activates Nrf2 antioxidant response element signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Betulinic Acid',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Betulinic Acid.',
  'mechanism': 'Modulates mTOR/autophagy balance.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Glycyrrhizin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Glycyrrhizin.',
  'mechanism': 'Modulates HPA axis stress-response signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Glabridin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Glabridin.',
  'mechanism': 'Interacts with thyroid hormone axis signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Honokiol',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Honokiol.',
  'mechanism': 'Affects hepatic lipid metabolism pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Magnolol',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Magnolol.',
  'mechanism': 'Supports one-carbon/methylation cycle function.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Baicalin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Baicalin.',
  'mechanism': 'Influences incretin/GLP-1 signaling pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Baicalein',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Baicalein.',
  'mechanism': 'Supports mitochondrial NAD+ metabolism.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Wogonin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Wogonin.',
  'mechanism': 'Influences iron/hepcidin regulation.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Andrographolide',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Andrographolide.',
  'mechanism': 'Modulates purine and uric acid metabolism.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Picrorhiza Kurroin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Picrorhiza Kurroin.',
  'mechanism': 'Interacts with vitamin D receptor signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Phyllanthin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Phyllanthin.',
  'mechanism': 'May influence renal filtration-related pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Gymnemic Acids',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Gymnemic Acids.',
  'mechanism': 'Modulates NF-κB inflammatory signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Gymnemosides',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Gymnemosides.',
  'mechanism': 'Modulates IL-6/JAK-STAT3 inflammatory signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Mangiferin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Mangiferin.',
  'mechanism': 'Engages AMPK energy-sensing pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Morin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Morin.',
  'mechanism': 'Influences insulin/PI3K-Akt metabolic signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Fisetin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Fisetin.',
  'mechanism': 'Activates Nrf2 antioxidant response element signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Lutein',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Lutein.',
  'mechanism': 'Modulates mTOR/autophagy balance.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Zeaxanthin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Zeaxanthin.',
  'mechanism': 'Modulates HPA axis stress-response signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Astaxanthin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Astaxanthin.',
  'mechanism': 'Interacts with thyroid hormone axis signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Canthaxanthin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Canthaxanthin.',
  'mechanism': 'Affects hepatic lipid metabolism pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Capsaicin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Capsaicin.',
  'mechanism': 'Supports one-carbon/methylation cycle function.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Dihydrocapsaicin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Dihydrocapsaicin.',
  'mechanism': 'Influences incretin/GLP-1 signaling pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Gingerols',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Gingerols.',
  'mechanism': 'Influences iron/hepcidin regulation.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Shogaols',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Shogaols.',
  'mechanism': 'Modulates purine and uric acid metabolism.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': '6-Gingerol',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: 6-Gingerol.',
  'mechanism': 'Interacts with vitamin D receptor signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Allyl Isothiocyanate',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Allyl Isothiocyanate.',
  'mechanism': 'May influence renal filtration-related pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Indole-3-Carbinol',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Indole-3-Carbinol.',
  'mechanism': 'Modulates NF-κB inflammatory signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'DIM',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: DIM.',
  'mechanism': 'Modulates IL-6/JAK-STAT3 inflammatory signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Sulforaphane Nitrile',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Sulforaphane Nitrile.',
  'mechanism': 'Engages AMPK energy-sensing pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Glucoraphanin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Glucoraphanin.',
  'mechanism': 'Influences insulin/PI3K-Akt metabolic signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Sinigrin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Sinigrin.',
  'mechanism': 'Activates Nrf2 antioxidant response element signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Allicin-Derived Diallyl Sulfides',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Allicin-Derived Diallyl Sulfides.',
  'mechanism': 'Modulates mTOR/autophagy balance.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Diallyl Disulfide',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Diallyl Disulfide.',
  'mechanism': 'Modulates HPA axis stress-response signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'S-Allyl Cysteine',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: S-Allyl Cysteine.',
  'mechanism': 'Interacts with thyroid hormone axis signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Theaflavins',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Theaflavins.',
  'mechanism': 'Affects hepatic lipid metabolism pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Thearubigins',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Thearubigins.',
  'mechanism': 'Supports one-carbon/methylation cycle function.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Chlorophyll',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Chlorophyll.',
  'mechanism': 'Influences incretin/GLP-1 signaling pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Phycocyanin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Phycocyanin.',
  'mechanism': 'Supports mitochondrial NAD+ metabolism.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Phycoerythrin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Phycoerythrin.',
  'mechanism': 'Influences iron/hepcidin regulation.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Betalains',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Betalains.',
  'mechanism': 'Modulates purine and uric acid metabolism.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Betanin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Betanin.',
  'mechanism': 'Interacts with vitamin D receptor signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Phytosterols',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Phytosterols.',
  'mechanism': 'May influence renal filtration-related pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Beta-Sitosterol',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Beta-Sitosterol.',
  'mechanism': 'Modulates NF-κB inflammatory signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Stigmasterol',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Stigmasterol.',
  'mechanism': 'Modulates IL-6/JAK-STAT3 inflammatory signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Campesterol',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Campesterol.',
  'mechanism': 'Engages AMPK energy-sensing pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Saponins',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Saponins.',
  'mechanism': 'Influences insulin/PI3K-Akt metabolic signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Ginseng Saponins',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Ginseng Saponins.',
  'mechanism': 'Activates Nrf2 antioxidant response element signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Triterpenoid Saponins',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Triterpenoid Saponins.',
  'mechanism': 'Modulates mTOR/autophagy balance.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Steroidal Saponins',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Steroidal Saponins.',
  'mechanism': 'Modulates HPA axis stress-response signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Tannins',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Tannins.',
  'mechanism': 'Interacts with thyroid hormone axis signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Proanthocyanidins',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Proanthocyanidins.',
  'mechanism': 'Affects hepatic lipid metabolism pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'OPC',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: OPC.',
  'mechanism': 'Supports one-carbon/methylation cycle function.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Punicalagins',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Punicalagins.',
  'mechanism': 'Influences incretin/GLP-1 signaling pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Delphinidin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Delphinidin.',
  'mechanism': 'Supports mitochondrial NAD+ metabolism.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Cyanidin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Cyanidin.',
  'mechanism': 'Influences iron/hepcidin regulation.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Malvidin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Malvidin.',
  'mechanism': 'Modulates purine and uric acid metabolism.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Pelargonidin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Pelargonidin.',
  'mechanism': 'Interacts with vitamin D receptor signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Peonidin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Peonidin.',
  'mechanism': 'May influence renal filtration-related pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Petunidin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Petunidin.',
  'mechanism': 'Modulates NF-κB inflammatory signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Galangin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Galangin.',
  'mechanism': 'Modulates IL-6/JAK-STAT3 inflammatory signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Chrysin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Chrysin.',
  'mechanism': 'Engages AMPK energy-sensing pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Baicalein-7-Glucuronide',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Baicalein-7-Glucuronide.',
  'mechanism': 'Influences insulin/PI3K-Akt metabolic signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Salidroside',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Salidroside.',
  'mechanism': 'Activates Nrf2 antioxidant response element signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Rosavin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Rosavin.',
  'mechanism': 'Modulates mTOR/autophagy balance.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Tyrosol',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Tyrosol.',
  'mechanism': 'Modulates HPA axis stress-response signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Hydroxytyrosol',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Hydroxytyrosol.',
  'mechanism': 'Interacts with thyroid hormone axis signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Oleuropein',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Oleuropein.',
  'mechanism': 'Affects hepatic lipid metabolism pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Oleocanthal',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Oleocanthal.',
  'mechanism': 'Supports one-carbon/methylation cycle function.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Oleacein',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Oleacein.',
  'mechanism': 'Influences incretin/GLP-1 signaling pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Verbascoside',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Verbascoside.',
  'mechanism': 'Supports mitochondrial NAD+ metabolism.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Acteoside',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Acteoside.',
  'mechanism': 'Influences iron/hepcidin regulation.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Chlorophyllin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Chlorophyllin.',
  'mechanism': 'Modulates purine and uric acid metabolism.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Phytic Acid',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Phytic Acid.',
  'mechanism': 'Interacts with vitamin D receptor signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Inositol',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Inositol.',
  'mechanism': 'May influence renal filtration-related pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'D-Chiro-Inositol',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: D-Chiro-Inositol.',
  'mechanism': 'Modulates NF-κB inflammatory signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Myo-Inositol',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Myo-Inositol.',
  'mechanism': 'Modulates IL-6/JAK-STAT3 inflammatory signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Alpha-Lipoic Acid',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Alpha-Lipoic Acid.',
  'mechanism': 'Engages AMPK energy-sensing pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Coenzyme Q10',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Coenzyme Q10.',
  'mechanism': 'Influences insulin/PI3K-Akt metabolic signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'PQQ',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: PQQ.',
  'mechanism': 'Activates Nrf2 antioxidant response element signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Ergothioneine',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Ergothioneine.',
  'mechanism': 'Modulates mTOR/autophagy balance.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Glutathione',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Glutathione.',
  'mechanism': 'Modulates HPA axis stress-response signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'S-Adenosylmethionine',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: S-Adenosylmethionine.',
  'mechanism': 'Interacts with thyroid hormone axis signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Betaine',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Betaine.',
  'mechanism': 'Affects hepatic lipid metabolism pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Trimethylglycine',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Trimethylglycine.',
  'mechanism': 'Supports one-carbon/methylation cycle function.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Carnitine',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Carnitine.',
  'mechanism': 'Influences incretin/GLP-1 signaling pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Acetyl-L-Carnitine',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Acetyl-L-Carnitine.',
  'mechanism': 'Supports mitochondrial NAD+ metabolism.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Taurine',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Taurine.',
  'mechanism': 'Influences iron/hepcidin regulation.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Theanine',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Theanine.',
  'mechanism': 'Modulates purine and uric acid metabolism.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'GABA',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: GABA.',
  'mechanism': 'Interacts with vitamin D receptor signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': '5-HTP',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: 5-HTP.',
  'mechanism': 'May influence renal filtration-related pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Melatonin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Melatonin.',
  'mechanism': 'Modulates NF-κB inflammatory signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Phosphatidylserine',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Phosphatidylserine.',
  'mechanism': 'Modulates IL-6/JAK-STAT3 inflammatory signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Phosphatidylcholine',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Phosphatidylcholine.',
  'mechanism': 'Engages AMPK energy-sensing pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Alpha-GPC',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Alpha-GPC.',
  'mechanism': 'Influences insulin/PI3K-Akt metabolic signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Citicoline',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Citicoline.',
  'mechanism': 'Activates Nrf2 antioxidant response element signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Uridine',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Uridine.',
  'mechanism': 'Modulates mTOR/autophagy balance.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Inulin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Inulin.',
  'mechanism': 'Modulates HPA axis stress-response signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Fructooligosaccharides',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Fructooligosaccharides.',
  'mechanism': 'Interacts with thyroid hormone axis signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Beta-Glucans',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Beta-Glucans.',
  'mechanism': 'Affects hepatic lipid metabolism pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Lentinan',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Lentinan.',
  'mechanism': 'Supports one-carbon/methylation cycle function.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'PSK',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: PSK.',
  'mechanism': 'Influences incretin/GLP-1 signaling pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Ergosterol',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Ergosterol.',
  'mechanism': 'Supports mitochondrial NAD+ metabolism.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Vitamin K2 MK-7',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Vitamin K2 MK-7.',
  'mechanism': 'Influences iron/hepcidin regulation.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Menaquinone',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Menaquinone.',
  'mechanism': 'Modulates purine and uric acid metabolism.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Pyrroloquinoline Quinone',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Pyrroloquinoline Quinone.',
  'mechanism': 'Interacts with vitamin D receptor signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Pterostilbene Analog',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Pterostilbene Analog.',
  'mechanism': 'May influence renal filtration-related pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Stilbenoids',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Stilbenoids.',
  'mechanism': 'Modulates NF-κB inflammatory signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Lignans',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Lignans.',
  'mechanism': 'Modulates IL-6/JAK-STAT3 inflammatory signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Secoisolariciresinol',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Secoisolariciresinol.',
  'mechanism': 'Engages AMPK energy-sensing pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Enterolactone',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Enterolactone.',
  'mechanism': 'Influences insulin/PI3K-Akt metabolic signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Coumarins',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Coumarins.',
  'mechanism': 'Activates Nrf2 antioxidant response element signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Umbelliferone',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Umbelliferone.',
  'mechanism': 'Modulates mTOR/autophagy balance.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Psoralen',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Psoralen.',
  'mechanism': 'Modulates HPA axis stress-response signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Furanocoumarins',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Furanocoumarins.',
  'mechanism': 'Interacts with thyroid hormone axis signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Alkaloids',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Alkaloids.',
  'mechanism': 'Affects hepatic lipid metabolism pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Vinpocetine',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Vinpocetine.',
  'mechanism': 'Supports one-carbon/methylation cycle function.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Huperzine A',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Huperzine A.',
  'mechanism': 'Influences incretin/GLP-1 signaling pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Berbamine',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Berbamine.',
  'mechanism': 'Supports mitochondrial NAD+ metabolism.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Lactoferrin',
  'category': 'phytochemical',
  'description': 'Iron-binding glycoprotein from bovine milk and colostrum.',
  'mechanism': 'Supports iron absorption; studied for biofilm disruption in infection models.',
  'is_regulated': False,
  'safety_flags': [{'condition': 'dairy_allergy', 'severity': 'contraindication', 'note': 'Avoid if cow milk protein allergy.'}],
  'drug_interactions': []},
 {'name': 'Caffeine',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Caffeine.',
  'mechanism': 'Modulates purine and uric acid metabolism.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Theobromine',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Theobromine.',
  'mechanism': 'Interacts with vitamin D receptor signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Theophylline',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Theophylline.',
  'mechanism': 'May influence renal filtration-related pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Nicotine Trace',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Nicotine Trace.',
  'mechanism': 'Modulates NF-κB inflammatory signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Capsiate',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Capsiate.',
  'mechanism': 'Modulates IL-6/JAK-STAT3 inflammatory signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Evodiamine',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Evodiamine.',
  'mechanism': 'Engages AMPK energy-sensing pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Synephrine',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Synephrine.',
  'mechanism': 'Influences insulin/PI3K-Akt metabolic signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Hordenine',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Hordenine.',
  'mechanism': 'Activates Nrf2 antioxidant response element signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Tyramine',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Tyramine.',
  'mechanism': 'Modulates mTOR/autophagy balance.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Phenylethylamine',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Phenylethylamine.',
  'mechanism': 'Modulates HPA axis stress-response signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Tryptophan',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Tryptophan.',
  'mechanism': 'Interacts with thyroid hormone axis signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': '5-HTP Precursor',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: 5-HTP Precursor.',
  'mechanism': 'Affects hepatic lipid metabolism pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Melatonin Precursor',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Melatonin Precursor.',
  'mechanism': 'Supports one-carbon/methylation cycle function.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Serotonin Precursor',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Serotonin Precursor.',
  'mechanism': 'Influences incretin/GLP-1 signaling pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Dopamine Precursor',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Dopamine Precursor.',
  'mechanism': 'Supports mitochondrial NAD+ metabolism.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'N-Acetyl Cysteine',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: N-Acetyl Cysteine.',
  'mechanism': 'Influences iron/hepcidin regulation.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Glucosamine',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Glucosamine.',
  'mechanism': 'Modulates purine and uric acid metabolism.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Chondroitin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Chondroitin.',
  'mechanism': 'Interacts with vitamin D receptor signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Hyaluronic Acid',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Hyaluronic Acid.',
  'mechanism': 'May influence renal filtration-related pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Gelatin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Gelatin.',
  'mechanism': 'Modulates NF-κB inflammatory signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Keratin',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Keratin.',
  'mechanism': 'Modulates IL-6/JAK-STAT3 inflammatory signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Silica',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Silica.',
  'mechanism': 'Engages AMPK energy-sensing pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Boron',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Boron.',
  'mechanism': 'Influences insulin/PI3K-Akt metabolic signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Vanadium',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Vanadium.',
  'mechanism': 'Activates Nrf2 antioxidant response element signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Chromium Picolinate',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Chromium Picolinate.',
  'mechanism': 'Modulates mTOR/autophagy balance.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Molybdenum',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Molybdenum.',
  'mechanism': 'Modulates HPA axis stress-response signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Selenium Methionine',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Selenium Methionine.',
  'mechanism': 'Interacts with thyroid hormone axis signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Selenomethionine',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Selenomethionine.',
  'mechanism': 'Affects hepatic lipid metabolism pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Zinc Carnosine',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Zinc Carnosine.',
  'mechanism': 'Supports one-carbon/methylation cycle function.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Zinc Picolinate',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Zinc Picolinate.',
  'mechanism': 'Influences incretin/GLP-1 signaling pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Magnesium Glycinate',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Magnesium Glycinate.',
  'mechanism': 'Supports mitochondrial NAD+ metabolism.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Magnesium Threonate',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Magnesium Threonate.',
  'mechanism': 'Influences iron/hepcidin regulation.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Calcium Citrate',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Calcium Citrate.',
  'mechanism': 'Modulates purine and uric acid metabolism.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Potassium Citrate',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Potassium Citrate.',
  'mechanism': 'Interacts with vitamin D receptor signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Sodium Bicarbonate',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Sodium Bicarbonate.',
  'mechanism': 'May influence renal filtration-related pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Bicarbonate',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Bicarbonate.',
  'mechanism': 'Modulates NF-κB inflammatory signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Citrate',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Citrate.',
  'mechanism': 'Modulates IL-6/JAK-STAT3 inflammatory signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Malate',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Malate.',
  'mechanism': 'Engages AMPK energy-sensing pathways.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Orotate',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Orotate.',
  'mechanism': 'Influences insulin/PI3K-Akt metabolic signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Aspartate',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Aspartate.',
  'mechanism': 'Activates Nrf2 antioxidant response element signaling.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Glycinate',
  'category': 'phytochemical',
  'description': 'Bioactive phytochemical compound: Glycinate.',
  'mechanism': 'Modulates mTOR/autophagy balance.',
  'is_regulated': False,
  'safety_flags': [],
  'drug_interactions': []}]
