"""200 supplement interventions."""

SUPPLEMENT_INTERVENTIONS: list[dict] = [{'name': 'Iron',
  'category': 'supplement',
  'description': 'Ferrous bisglycinate or sulfate for iron repletion.',
  'mechanism': 'Replenishes iron stores supporting hemoglobin synthesis.',
  'is_regulated': False,
  'compounds': [{'name': 'Ferrous bisglycinate',
                 'primary_target': 'iron stores',
                 'role': 'bioavailable form',
                 'pubchem_cid': None}],
  'safety_flags': [{'condition': 'hemochromatosis',
                    'severity': 'contraindication',
                    'note': 'Do not supplement without confirmed deficiency.'}],
  'drug_interactions': [{'drug_name': 'Levothyroxine',
                         'severity': 'moderate',
                         'mechanism': 'Reduces thyroid hormone absorption.',
                         'note': 'Separate by 4 hours.'}]},
 {'name': 'Zinc Carnosine',
  'category': 'supplement',
  'description': 'Zinc L-carnosine chelate studied for gastric mucosal support.',
  'mechanism': 'Adheres to gastric mucosa and supports ulcer healing in clinical trials.',
  'is_regulated': False,
  'compounds': [{'name': 'Zinc L-carnosine',
                 'primary_target': 'gastric mucosa',
                 'role': 'primary active constituent',
                 'pubchem_cid': None}],
  'safety_flags': [],
  'drug_interactions': [{'drug_name': 'Antibiotics',
                         'severity': 'low',
                         'mechanism': 'Zinc may reduce absorption of fluoroquinolones/tetracyclines.',
                         'note': 'Separate by 2 hours.'}]},
 {'name': 'Zinc',
  'category': 'supplement',
  'description': 'Zinc picolinate or gluconate supplementation.',
  'mechanism': 'Cofactor for immune and mucosal repair enzymes.',
  'is_regulated': False,
  'compounds': [{'name': 'Zinc gluconate',
                 'primary_target': 'zinc-dependent enzymes',
                 'role': 'primary active constituent',
                 'pubchem_cid': '443148'}],
  'safety_flags': [{'condition': 'copper_deficiency',
                    'severity': 'caution',
                    'note': 'Chronic high-dose zinc can induce copper deficiency.'}],
  'drug_interactions': []},
 {'name': 'Omega-3',
  'category': 'supplement',
  'description': 'EPA/DHA marine or algal oil.',
  'mechanism': 'Specialized pro-resolving mediators reduce NF-κB-driven inflammation.',
  'is_regulated': False,
  'compounds': [{'name': 'EPA',
                 'primary_target': 'Pro-resolving mediator synthesis',
                 'role': 'primary active constituent',
                 'pubchem_cid': '446284'},
                {'name': 'DHA',
                 'primary_target': 'Membrane phospholipid remodeling',
                 'role': 'primary active constituent',
                 'pubchem_cid': '445580'}],
  'safety_flags': [],
  'drug_interactions': [{'drug_name': 'Warfarin',
                         'severity': 'moderate',
                         'mechanism': 'Additive antiplatelet effect at high doses.',
                         'note': 'Monitor INR above 3g/day.'}]},
 {'name': 'Vitamin D',
  'category': 'supplement',
  'description': 'Cholecalciferol (D3) supplementation.',
  'mechanism': 'VDR signaling regulates calcium homeostasis and immune function.',
  'is_regulated': False,
  'compounds': [{'name': 'Cholecalciferol (D3)',
                 'primary_target': 'Vitamin D receptor',
                 'role': 'primary active constituent',
                 'pubchem_cid': '5280795'}],
  'safety_flags': [{'condition': 'severe_ckd',
                    'severity': 'caution',
                    'note': 'High-dose D3 may worsen hyperphosphatemia in advanced CKD.'}],
  'drug_interactions': []},
 {'name': 'B12',
  'category': 'supplement',
  'description': 'Methylcobalamin or cyanocobalamin supplementation.',
  'mechanism': 'Cofactor for methionine synthase and homocysteine clearance.',
  'is_regulated': False,
  'compounds': [{'name': 'Methylcobalamin',
                 'primary_target': 'methionine synthase',
                 'role': 'active form',
                 'pubchem_cid': '10898549'}],
  'safety_flags': [],
  'drug_interactions': [{'drug_name': 'Metformin',
                         'severity': 'low',
                         'mechanism': 'Long-term metformin may lower B12.',
                         'note': 'Monitor B12 on metformin.'}]},
 {'name': 'Glutamine',
  'category': 'supplement',
  'description': 'Conditionally essential amino acid for enterocyte fuel.',
  'mechanism': 'Primary energy source for intestinal epithelial cells; supports mucosal barrier.',
  'is_regulated': False,
  'compounds': [{'name': 'L-Glutamine',
                 'primary_target': 'intestinal epithelium',
                 'role': 'primary active constituent',
                 'pubchem_cid': '5961'}],
  'safety_flags': [{'condition': 'severe_hepatic_encephalopathy',
                    'severity': 'contraindication',
                    'note': 'May worsen ammonia in advanced liver disease.'}],
  'drug_interactions': []},
 {'name': 'Folate',
  'category': 'supplement',
  'description': 'Methylfolate (5-MTHF) or folic acid supplementation.',
  'mechanism': 'One-carbon donor for methylation cycle and homocysteine clearance.',
  'is_regulated': False,
  'compounds': [{'name': 'L-Methylfolate',
                 'primary_target': 'methylation cycle',
                 'role': 'active form',
                 'pubchem_cid': '135398586'}],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'NAD+ Precursors (NR/NMN)',
  'category': 'supplement',
  'description': 'Nicotinamide riboside / NMN NAD+ precursors.',
  'mechanism': 'Replenishes intracellular NAD+ pools supporting mitochondrial function.',
  'is_regulated': False,
  'compounds': [{'name': 'Nicotinamide Riboside',
                 'primary_target': 'NAD+ salvage pathway',
                 'role': 'NAD+ precursor',
                 'pubchem_cid': '439924'}],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Berberine',
  'category': 'supplement',
  'description': 'Isoquinoline alkaloid from Berberis species.',
  'mechanism': 'Activates AMPK; studied for glycemic and lipid effects and antimicrobial properties.',
  'is_regulated': False,
  'compounds': [{'name': 'Berberine hydrochloride',
                 'primary_target': 'AMPK',
                 'role': 'primary active constituent',
                 'pubchem_cid': '72322'}],
  'safety_flags': [{'condition': 'pregnancy', 'severity': 'contraindication', 'note': 'Crosses placenta; avoid.'}],
  'drug_interactions': [{'drug_name': 'Metformin',
                         'severity': 'moderate',
                         'mechanism': 'Additive glucose lowering.',
                         'note': 'Monitor for hypoglycemia.'},
                        {'drug_name': 'Cyclosporine',
                         'severity': 'high',
                         'mechanism': 'CYP3A4/P-gp inhibition.',
                         'note': 'Avoid without supervision.'}]},
 {'name': 'NAC',
  'category': 'supplement',
  'description': 'N-acetylcysteine — glutathione precursor.',
  'mechanism': 'Replenishes glutathione; studied for oxidative stress and biofilm contexts.',
  'is_regulated': False,
  'compounds': [{'name': 'N-acetylcysteine',
                 'primary_target': 'glutathione synthesis',
                 'role': 'primary active constituent',
                 'pubchem_cid': '12035'}],
  'safety_flags': [],
  'drug_interactions': [{'drug_name': 'Nitroglycerin',
                         'severity': 'moderate',
                         'mechanism': 'May potentiate hypotensive effect.',
                         'note': None}]},
 {'name': 'CoQ10',
  'category': 'supplement',
  'description': 'Coenzyme Q10 mitochondrial cofactor.',
  'mechanism': 'Supports mitochondrial ATP production; depleted by statin therapy.',
  'is_regulated': False,
  'compounds': [{'name': 'Ubiquinol',
                 'primary_target': 'Mitochondrial electron transport',
                 'role': 'reduced form',
                 'pubchem_cid': '5281915'}],
  'safety_flags': [],
  'drug_interactions': [{'drug_name': 'Warfarin',
                         'severity': 'low',
                         'mechanism': 'Structural similarity to vitamin K.',
                         'note': 'Monitor INR.'}]},
 {'name': 'Alpha Lipoic Acid',
  'category': 'supplement',
  'description': 'Mitochondrial cofactor and antioxidant (ALA).',
  'mechanism': 'Regenerates glutathione; activates AMPK and improves insulin signaling.',
  'is_regulated': False,
  'compounds': [{'name': 'R-alpha lipoic acid',
                 'primary_target': 'AMPK',
                 'role': 'primary active constituent',
                 'pubchem_cid': '6112'}],
  'safety_flags': [],
  'drug_interactions': [{'drug_name': 'Insulin/antidiabetics',
                         'severity': 'moderate',
                         'mechanism': 'Additive glucose lowering.',
                         'note': 'Monitor for hypoglycemia.'}]},
 {'name': 'Magnesium',
  'category': 'supplement',
  'description': 'Essential mineral (glycinate/citrate forms preferred).',
  'mechanism': 'Cofactor for ATP-dependent enzymes; modulates insulin signaling.',
  'is_regulated': False,
  'compounds': [{'name': 'Magnesium glycinate',
                 'primary_target': 'NMDA receptor',
                 'role': 'bioavailable form',
                 'pubchem_cid': None}],
  'safety_flags': [{'condition': 'severe_ckd', 'severity': 'contraindication', 'note': 'Risk of hypermagnesemia.'}],
  'drug_interactions': []},
 {'name': 'Vitamin C',
  'category': 'supplement',
  'description': 'Dietary supplement: Vitamin C.',
  'mechanism': 'Modulates NF-κB inflammatory signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'Supplement safety in pregnancy varies; consult a clinician.'}],
  'drug_interactions': []},
 {'name': 'Vitamin E',
  'category': 'supplement',
  'description': 'Dietary supplement: Vitamin E.',
  'mechanism': 'Modulates IL-6/JAK-STAT3 inflammatory signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Vitamin K2',
  'category': 'supplement',
  'description': 'Dietary supplement: Vitamin K2.',
  'mechanism': 'Engages AMPK energy-sensing pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Vitamin A',
  'category': 'supplement',
  'description': 'Dietary supplement: Vitamin A.',
  'mechanism': 'Influences insulin/PI3K-Akt metabolic signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Vitamin B6',
  'category': 'supplement',
  'description': 'Dietary supplement: Vitamin B6.',
  'mechanism': 'Activates Nrf2 antioxidant response element signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Vitamin B1',
  'category': 'supplement',
  'description': 'Dietary supplement: Vitamin B1.',
  'mechanism': 'Modulates mTOR/autophagy balance.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Vitamin B2',
  'category': 'supplement',
  'description': 'Dietary supplement: Vitamin B2.',
  'mechanism': 'Modulates HPA axis stress-response signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'Supplement safety in pregnancy varies; consult a clinician.'}],
  'drug_interactions': []},
 {'name': 'Vitamin B3',
  'category': 'supplement',
  'description': 'Dietary supplement: Vitamin B3.',
  'mechanism': 'Interacts with thyroid hormone axis signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Vitamin B5',
  'category': 'supplement',
  'description': 'Dietary supplement: Vitamin B5.',
  'mechanism': 'Affects hepatic lipid metabolism pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Biotin',
  'category': 'supplement',
  'description': 'Dietary supplement: Biotin.',
  'mechanism': 'Supports one-carbon/methylation cycle function.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Choline',
  'category': 'supplement',
  'description': 'Dietary supplement: Choline.',
  'mechanism': 'Influences incretin/GLP-1 signaling pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Inositol',
  'category': 'supplement',
  'description': 'Dietary supplement: Inositol.',
  'mechanism': 'Supports mitochondrial NAD+ metabolism.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'SAMe',
  'category': 'supplement',
  'description': 'Dietary supplement: SAMe.',
  'mechanism': 'Influences iron/hepcidin regulation.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'Supplement safety in pregnancy varies; consult a clinician.'}],
  'drug_interactions': []},
 {'name': 'MSM',
  'category': 'supplement',
  'description': 'Dietary supplement: MSM.',
  'mechanism': 'Modulates purine and uric acid metabolism.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'DIM',
  'category': 'supplement',
  'description': 'Dietary supplement: DIM.',
  'mechanism': 'Interacts with vitamin D receptor signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Calcium',
  'category': 'supplement',
  'description': 'Dietary supplement: Calcium.',
  'mechanism': 'May influence renal filtration-related pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Potassium',
  'category': 'supplement',
  'description': 'Dietary supplement: Potassium.',
  'mechanism': 'Modulates NF-κB inflammatory signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Selenium',
  'category': 'supplement',
  'description': 'Dietary supplement: Selenium.',
  'mechanism': 'Modulates IL-6/JAK-STAT3 inflammatory signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Copper',
  'category': 'supplement',
  'description': 'Dietary supplement: Copper.',
  'mechanism': 'Engages AMPK energy-sensing pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'Supplement safety in pregnancy varies; consult a clinician.'}],
  'drug_interactions': []},
 {'name': 'Manganese',
  'category': 'supplement',
  'description': 'Dietary supplement: Manganese.',
  'mechanism': 'Influences insulin/PI3K-Akt metabolic signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Chromium',
  'category': 'supplement',
  'description': 'Dietary supplement: Chromium.',
  'mechanism': 'Activates Nrf2 antioxidant response element signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Iodine',
  'category': 'supplement',
  'description': 'Dietary supplement: Iodine.',
  'mechanism': 'Modulates mTOR/autophagy balance.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Molybdenum',
  'category': 'supplement',
  'description': 'Dietary supplement: Molybdenum.',
  'mechanism': 'Modulates HPA axis stress-response signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Boron',
  'category': 'supplement',
  'description': 'Dietary supplement: Boron.',
  'mechanism': 'Interacts with thyroid hormone axis signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Silica',
  'category': 'supplement',
  'description': 'Dietary supplement: Silica.',
  'mechanism': 'Affects hepatic lipid metabolism pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'Supplement safety in pregnancy varies; consult a clinician.'}],
  'drug_interactions': []},
 {'name': 'Strontium',
  'category': 'supplement',
  'description': 'Dietary supplement: Strontium.',
  'mechanism': 'Supports one-carbon/methylation cycle function.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Vanadium',
  'category': 'supplement',
  'description': 'Dietary supplement: Vanadium.',
  'mechanism': 'Influences incretin/GLP-1 signaling pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Probiotics',
  'category': 'supplement',
  'description': 'Dietary supplement: Probiotics.',
  'mechanism': 'Supports mitochondrial NAD+ metabolism.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Saccharomyces boulardii',
  'category': 'supplement',
  'description': 'Dietary supplement: Saccharomyces boulardii.',
  'mechanism': 'Influences iron/hepcidin regulation.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Lactobacillus rhamnosus',
  'category': 'supplement',
  'description': 'Dietary supplement: Lactobacillus rhamnosus.',
  'mechanism': 'Modulates purine and uric acid metabolism.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Bifidobacterium longum',
  'category': 'supplement',
  'description': 'Dietary supplement: Bifidobacterium longum.',
  'mechanism': 'Interacts with vitamin D receptor signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'Supplement safety in pregnancy varies; consult a clinician.'}],
  'drug_interactions': []},
 {'name': 'Multi-Strain Probiotic',
  'category': 'supplement',
  'description': 'Dietary supplement: Multi-Strain Probiotic.',
  'mechanism': 'May influence renal filtration-related pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Prebiotic Fiber',
  'category': 'supplement',
  'description': 'Dietary supplement: Prebiotic Fiber.',
  'mechanism': 'Modulates NF-κB inflammatory signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Psyllium',
  'category': 'supplement',
  'description': 'Dietary supplement: Psyllium.',
  'mechanism': 'Modulates IL-6/JAK-STAT3 inflammatory signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Glucomannan',
  'category': 'supplement',
  'description': 'Dietary supplement: Glucomannan.',
  'mechanism': 'Engages AMPK energy-sensing pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Pectin',
  'category': 'supplement',
  'description': 'Dietary supplement: Pectin.',
  'mechanism': 'Influences insulin/PI3K-Akt metabolic signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Apple Cider Vinegar Capsules',
  'category': 'supplement',
  'description': 'Dietary supplement: Apple Cider Vinegar Capsules.',
  'mechanism': 'Activates Nrf2 antioxidant response element signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'Supplement safety in pregnancy varies; consult a clinician.'}],
  'drug_interactions': []},
 {'name': 'Betaine HCl',
  'category': 'supplement',
  'description': 'Dietary supplement: Betaine HCl.',
  'mechanism': 'Modulates mTOR/autophagy balance.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Digestive Enzymes',
  'category': 'supplement',
  'description': 'Dietary supplement: Digestive Enzymes.',
  'mechanism': 'Modulates HPA axis stress-response signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Pancreatin',
  'category': 'supplement',
  'description': 'Dietary supplement: Pancreatin.',
  'mechanism': 'Interacts with thyroid hormone axis signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Bromelain',
  'category': 'supplement',
  'description': 'Dietary supplement: Bromelain.',
  'mechanism': 'Affects hepatic lipid metabolism pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Papain',
  'category': 'supplement',
  'description': 'Dietary supplement: Papain.',
  'mechanism': 'Supports one-carbon/methylation cycle function.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Quercetin Supplement',
  'category': 'supplement',
  'description': 'Dietary supplement: Quercetin Supplement.',
  'mechanism': 'Influences incretin/GLP-1 signaling pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'Supplement safety in pregnancy varies; consult a clinician.'}],
  'drug_interactions': []},
 {'name': 'Resveratrol Supplement',
  'category': 'supplement',
  'description': 'Dietary supplement: Resveratrol Supplement.',
  'mechanism': 'Supports mitochondrial NAD+ metabolism.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Pterostilbene',
  'category': 'supplement',
  'description': 'Dietary supplement: Pterostilbene.',
  'mechanism': 'Influences iron/hepcidin regulation.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'PQQ Supplement',
  'category': 'supplement',
  'description': 'Dietary supplement: PQQ Supplement.',
  'mechanism': 'Modulates purine and uric acid metabolism.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Astaxanthin',
  'category': 'supplement',
  'description': 'Dietary supplement: Astaxanthin.',
  'mechanism': 'Interacts with vitamin D receptor signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Lutein Supplement',
  'category': 'supplement',
  'description': 'Dietary supplement: Lutein Supplement.',
  'mechanism': 'May influence renal filtration-related pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Zeaxanthin',
  'category': 'supplement',
  'description': 'Dietary supplement: Zeaxanthin.',
  'mechanism': 'Modulates NF-κB inflammatory signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'Supplement safety in pregnancy varies; consult a clinician.'}],
  'drug_interactions': []},
 {'name': 'Lycopene Supplement',
  'category': 'supplement',
  'description': 'Dietary supplement: Lycopene Supplement.',
  'mechanism': 'Modulates IL-6/JAK-STAT3 inflammatory signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Green Tea Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Green Tea Extract.',
  'mechanism': 'Engages AMPK energy-sensing pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Caffeine Anhydrous',
  'category': 'supplement',
  'description': 'Dietary supplement: Caffeine Anhydrous.',
  'mechanism': 'Influences insulin/PI3K-Akt metabolic signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'L-Theanine',
  'category': 'supplement',
  'description': 'Dietary supplement: L-Theanine.',
  'mechanism': 'Activates Nrf2 antioxidant response element signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'GABA Supplement',
  'category': 'supplement',
  'description': 'Dietary supplement: GABA Supplement.',
  'mechanism': 'Modulates mTOR/autophagy balance.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': '5-HTP',
  'category': 'supplement',
  'description': 'Dietary supplement: 5-HTP.',
  'mechanism': 'Modulates HPA axis stress-response signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'Supplement safety in pregnancy varies; consult a clinician.'}],
  'drug_interactions': []},
 {'name': 'Melatonin Supplement',
  'category': 'supplement',
  'description': 'Dietary supplement: Melatonin Supplement.',
  'mechanism': 'Interacts with thyroid hormone axis signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Valerian Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Valerian Extract.',
  'mechanism': 'Affects hepatic lipid metabolism pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Passionflower Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Passionflower Extract.',
  'mechanism': 'Supports one-carbon/methylation cycle function.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Lemon Balm Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Lemon Balm Extract.',
  'mechanism': 'Influences incretin/GLP-1 signaling pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Kava Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Kava Extract.',
  'mechanism': 'Supports mitochondrial NAD+ metabolism.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': "St. John's Wort Extract",
  'category': 'supplement',
  'description': "Dietary supplement: St. John's Wort Extract.",
  'mechanism': 'Influences iron/hepcidin regulation.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'Supplement safety in pregnancy varies; consult a clinician.'}],
  'drug_interactions': []},
 {'name': 'Saffron Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Saffron Extract.',
  'mechanism': 'Modulates purine and uric acid metabolism.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Rhodiola Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Rhodiola Extract.',
  'mechanism': 'Interacts with vitamin D receptor signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Ginseng Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Ginseng Extract.',
  'mechanism': 'May influence renal filtration-related pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Cordyceps Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Cordyceps Extract.',
  'mechanism': 'Modulates NF-κB inflammatory signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': "Lion's Mane Extract",
  'category': 'supplement',
  'description': "Dietary supplement: Lion's Mane Extract.",
  'mechanism': 'Modulates IL-6/JAK-STAT3 inflammatory signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Reishi Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Reishi Extract.',
  'mechanism': 'Engages AMPK energy-sensing pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'Supplement safety in pregnancy varies; consult a clinician.'}],
  'drug_interactions': []},
 {'name': 'Chaga Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Chaga Extract.',
  'mechanism': 'Influences insulin/PI3K-Akt metabolic signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Turkey Tail Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Turkey Tail Extract.',
  'mechanism': 'Activates Nrf2 antioxidant response element signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Maitake Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Maitake Extract.',
  'mechanism': 'Modulates mTOR/autophagy balance.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Shiitake Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Shiitake Extract.',
  'mechanism': 'Modulates HPA axis stress-response signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Agaricus blazei',
  'category': 'supplement',
  'description': 'Dietary supplement: Agaricus blazei.',
  'mechanism': 'Interacts with thyroid hormone axis signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Poria cocos',
  'category': 'supplement',
  'description': 'Dietary supplement: Poria cocos.',
  'mechanism': 'Affects hepatic lipid metabolism pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'Supplement safety in pregnancy varies; consult a clinician.'}],
  'drug_interactions': []},
 {'name': 'Polyporus umbellatus',
  'category': 'supplement',
  'description': 'Dietary supplement: Polyporus umbellatus.',
  'mechanism': 'Supports one-carbon/methylation cycle function.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Astragalus Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Astragalus Extract.',
  'mechanism': 'Influences incretin/GLP-1 signaling pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Eleuthero Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Eleuthero Extract.',
  'mechanism': 'Supports mitochondrial NAD+ metabolism.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Schisandra Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Schisandra Extract.',
  'mechanism': 'Influences iron/hepcidin regulation.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Gymnema Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Gymnema Extract.',
  'mechanism': 'Modulates purine and uric acid metabolism.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Banaba Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Banaba Extract.',
  'mechanism': 'Interacts with vitamin D receptor signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'Supplement safety in pregnancy varies; consult a clinician.'}],
  'drug_interactions': []},
 {'name': 'Bitter Melon Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Bitter Melon Extract.',
  'mechanism': 'May influence renal filtration-related pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Fenugreek Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Fenugreek Extract.',
  'mechanism': 'Modulates NF-κB inflammatory signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Cinnamon Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Cinnamon Extract.',
  'mechanism': 'Modulates IL-6/JAK-STAT3 inflammatory signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Chromium Picolinate',
  'category': 'supplement',
  'description': 'Dietary supplement: Chromium Picolinate.',
  'mechanism': 'Engages AMPK energy-sensing pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Alpha-GPC',
  'category': 'supplement',
  'description': 'Dietary supplement: Alpha-GPC.',
  'mechanism': 'Influences insulin/PI3K-Akt metabolic signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Citicoline',
  'category': 'supplement',
  'description': 'Dietary supplement: Citicoline.',
  'mechanism': 'Activates Nrf2 antioxidant response element signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'Supplement safety in pregnancy varies; consult a clinician.'}],
  'drug_interactions': []},
 {'name': 'Phosphatidylserine',
  'category': 'supplement',
  'description': 'Dietary supplement: Phosphatidylserine.',
  'mechanism': 'Modulates mTOR/autophagy balance.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Phosphatidylcholine',
  'category': 'supplement',
  'description': 'Dietary supplement: Phosphatidylcholine.',
  'mechanism': 'Modulates HPA axis stress-response signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Huperzine A',
  'category': 'supplement',
  'description': 'Dietary supplement: Huperzine A.',
  'mechanism': 'Interacts with thyroid hormone axis signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Vinpocetine',
  'category': 'supplement',
  'description': 'Dietary supplement: Vinpocetine.',
  'mechanism': 'Affects hepatic lipid metabolism pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Bacopa Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Bacopa Extract.',
  'mechanism': 'Supports one-carbon/methylation cycle function.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Ginkgo Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Ginkgo Extract.',
  'mechanism': 'Influences incretin/GLP-1 signaling pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'Supplement safety in pregnancy varies; consult a clinician.'}],
  'drug_interactions': []},
 {'name': "Lion's Mane Powder",
  'category': 'supplement',
  'description': "Dietary supplement: Lion's Mane Powder.",
  'mechanism': 'Supports mitochondrial NAD+ metabolism.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Creatine Monohydrate',
  'category': 'supplement',
  'description': 'Dietary supplement: Creatine Monohydrate.',
  'mechanism': 'Influences iron/hepcidin regulation.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Creatine HCl',
  'category': 'supplement',
  'description': 'Dietary supplement: Creatine HCl.',
  'mechanism': 'Modulates purine and uric acid metabolism.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Beta-Alanine',
  'category': 'supplement',
  'description': 'Dietary supplement: Beta-Alanine.',
  'mechanism': 'Interacts with vitamin D receptor signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Citrulline Malate',
  'category': 'supplement',
  'description': 'Dietary supplement: Citrulline Malate.',
  'mechanism': 'May influence renal filtration-related pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Beetroot Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Beetroot Extract.',
  'mechanism': 'Modulates NF-κB inflammatory signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'Supplement safety in pregnancy varies; consult a clinician.'}],
  'drug_interactions': []},
 {'name': 'Nitrate Supplement',
  'category': 'supplement',
  'description': 'Dietary supplement: Nitrate Supplement.',
  'mechanism': 'Modulates IL-6/JAK-STAT3 inflammatory signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'HMB',
  'category': 'supplement',
  'description': 'Dietary supplement: HMB.',
  'mechanism': 'Engages AMPK energy-sensing pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'BCAA',
  'category': 'supplement',
  'description': 'Dietary supplement: BCAA.',
  'mechanism': 'Influences insulin/PI3K-Akt metabolic signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'EAAs',
  'category': 'supplement',
  'description': 'Dietary supplement: EAAs.',
  'mechanism': 'Activates Nrf2 antioxidant response element signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Whey Protein',
  'category': 'supplement',
  'description': 'Dietary supplement: Whey Protein.',
  'mechanism': 'Modulates mTOR/autophagy balance.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Casein Protein',
  'category': 'supplement',
  'description': 'Dietary supplement: Casein Protein.',
  'mechanism': 'Modulates HPA axis stress-response signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'Supplement safety in pregnancy varies; consult a clinician.'}],
  'drug_interactions': []},
 {'name': 'Plant Protein Blend',
  'category': 'supplement',
  'description': 'Dietary supplement: Plant Protein Blend.',
  'mechanism': 'Interacts with thyroid hormone axis signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Collagen Type II',
  'category': 'supplement',
  'description': 'Dietary supplement: Collagen Type II.',
  'mechanism': 'Affects hepatic lipid metabolism pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Glucosamine Sulfate',
  'category': 'supplement',
  'description': 'Dietary supplement: Glucosamine Sulfate.',
  'mechanism': 'Supports one-carbon/methylation cycle function.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Chondroitin Sulfate',
  'category': 'supplement',
  'description': 'Dietary supplement: Chondroitin Sulfate.',
  'mechanism': 'Influences incretin/GLP-1 signaling pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'MSM Joint Formula',
  'category': 'supplement',
  'description': 'Dietary supplement: MSM Joint Formula.',
  'mechanism': 'Supports mitochondrial NAD+ metabolism.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Hyaluronic Acid Oral',
  'category': 'supplement',
  'description': 'Dietary supplement: Hyaluronic Acid Oral.',
  'mechanism': 'Influences iron/hepcidin regulation.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'Supplement safety in pregnancy varies; consult a clinician.'}],
  'drug_interactions': []},
 {'name': 'UC-II Collagen',
  'category': 'supplement',
  'description': 'Dietary supplement: UC-II Collagen.',
  'mechanism': 'Modulates purine and uric acid metabolism.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Boswellia Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Boswellia Extract.',
  'mechanism': 'Interacts with vitamin D receptor signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Turmeric Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Turmeric Extract.',
  'mechanism': 'May influence renal filtration-related pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Curcumin Phytosome',
  'category': 'supplement',
  'description': 'Dietary supplement: Curcumin Phytosome.',
  'mechanism': 'Modulates NF-κB inflammatory signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Ginger Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Ginger Extract.',
  'mechanism': 'Modulates IL-6/JAK-STAT3 inflammatory signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': "Devil's Claw",
  'category': 'supplement',
  'description': "Dietary supplement: Devil's Claw.",
  'mechanism': 'Engages AMPK energy-sensing pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'Supplement safety in pregnancy varies; consult a clinician.'}],
  'drug_interactions': []},
 {'name': 'White Willow Bark',
  'category': 'supplement',
  'description': 'Dietary supplement: White Willow Bark.',
  'mechanism': 'Influences insulin/PI3K-Akt metabolic signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Capsaicin Supplement',
  'category': 'supplement',
  'description': 'Dietary supplement: Capsaicin Supplement.',
  'mechanism': 'Activates Nrf2 antioxidant response element signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Arnica Oral',
  'category': 'supplement',
  'description': 'Dietary supplement: Arnica Oral.',
  'mechanism': 'Modulates mTOR/autophagy balance.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Bromelain Anti-Inflammatory',
  'category': 'supplement',
  'description': 'Dietary supplement: Bromelain Anti-Inflammatory.',
  'mechanism': 'Modulates HPA axis stress-response signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Fish Oil',
  'category': 'supplement',
  'description': 'Dietary supplement: Fish Oil.',
  'mechanism': 'Interacts with thyroid hormone axis signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Krill Oil',
  'category': 'supplement',
  'description': 'Dietary supplement: Krill Oil.',
  'mechanism': 'Affects hepatic lipid metabolism pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'Supplement safety in pregnancy varies; consult a clinician.'}],
  'drug_interactions': []},
 {'name': 'Algal DHA',
  'category': 'supplement',
  'description': 'Dietary supplement: Algal DHA.',
  'mechanism': 'Supports one-carbon/methylation cycle function.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Flaxseed Oil',
  'category': 'supplement',
  'description': 'Dietary supplement: Flaxseed Oil.',
  'mechanism': 'Influences incretin/GLP-1 signaling pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Evening Primrose Oil',
  'category': 'supplement',
  'description': 'Dietary supplement: Evening Primrose Oil.',
  'mechanism': 'Supports mitochondrial NAD+ metabolism.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Borage Oil',
  'category': 'supplement',
  'description': 'Dietary supplement: Borage Oil.',
  'mechanism': 'Influences iron/hepcidin regulation.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Black Seed Oil',
  'category': 'supplement',
  'description': 'Dietary supplement: Black Seed Oil.',
  'mechanism': 'Modulates purine and uric acid metabolism.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Pumpkin Seed Oil',
  'category': 'supplement',
  'description': 'Dietary supplement: Pumpkin Seed Oil.',
  'mechanism': 'Interacts with vitamin D receptor signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'Supplement safety in pregnancy varies; consult a clinician.'}],
  'drug_interactions': []},
 {'name': 'Sea Buckthorn Oil',
  'category': 'supplement',
  'description': 'Dietary supplement: Sea Buckthorn Oil.',
  'mechanism': 'May influence renal filtration-related pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Cod Liver Oil',
  'category': 'supplement',
  'description': 'Dietary supplement: Cod Liver Oil.',
  'mechanism': 'Modulates NF-κB inflammatory signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'MCT Oil Powder',
  'category': 'supplement',
  'description': 'Dietary supplement: MCT Oil Powder.',
  'mechanism': 'Modulates IL-6/JAK-STAT3 inflammatory signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Caprylic Acid',
  'category': 'supplement',
  'description': 'Dietary supplement: Caprylic Acid.',
  'mechanism': 'Engages AMPK energy-sensing pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Capric Acid',
  'category': 'supplement',
  'description': 'Dietary supplement: Capric Acid.',
  'mechanism': 'Influences insulin/PI3K-Akt metabolic signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Butyrate',
  'category': 'supplement',
  'description': 'Dietary supplement: Butyrate.',
  'mechanism': 'Activates Nrf2 antioxidant response element signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'Supplement safety in pregnancy varies; consult a clinician.'}],
  'drug_interactions': []},
 {'name': 'Tributyrin',
  'category': 'supplement',
  'description': 'Dietary supplement: Tributyrin.',
  'mechanism': 'Modulates mTOR/autophagy balance.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Postbiotic',
  'category': 'supplement',
  'description': 'Dietary supplement: Postbiotic.',
  'mechanism': 'Modulates HPA axis stress-response signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Colostrum',
  'category': 'supplement',
  'description': 'Dietary supplement: Colostrum.',
  'mechanism': 'Interacts with thyroid hormone axis signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Lactoferrin',
  'category': 'supplement',
  'description': 'Dietary supplement: Lactoferrin.',
  'mechanism': 'Affects hepatic lipid metabolism pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Immunoglobulin G',
  'category': 'supplement',
  'description': 'Dietary supplement: Immunoglobulin G.',
  'mechanism': 'Supports one-carbon/methylation cycle function.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Beta-Glucan',
  'category': 'supplement',
  'description': 'Dietary supplement: Beta-Glucan.',
  'mechanism': 'Influences incretin/GLP-1 signaling pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'Supplement safety in pregnancy varies; consult a clinician.'}],
  'drug_interactions': []},
 {'name': 'Echinacea Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Echinacea Extract.',
  'mechanism': 'Supports mitochondrial NAD+ metabolism.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Elderberry Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Elderberry Extract.',
  'mechanism': 'Influences iron/hepcidin regulation.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Andrographis Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Andrographis Extract.',
  'mechanism': 'Modulates purine and uric acid metabolism.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Pelargonium sidoides',
  'category': 'supplement',
  'description': 'Dietary supplement: Pelargonium sidoides.',
  'mechanism': 'Interacts with vitamin D receptor signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Umckaloabo',
  'category': 'supplement',
  'description': 'Dietary supplement: Umckaloabo.',
  'mechanism': 'May influence renal filtration-related pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Oregano Oil',
  'category': 'supplement',
  'description': 'Dietary supplement: Oregano Oil.',
  'mechanism': 'Modulates NF-κB inflammatory signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'Supplement safety in pregnancy varies; consult a clinician.'}],
  'drug_interactions': []},
 {'name': 'Monolaurin',
  'category': 'supplement',
  'description': 'Dietary supplement: Monolaurin.',
  'mechanism': 'Modulates IL-6/JAK-STAT3 inflammatory signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Lauricidin',
  'category': 'supplement',
  'description': 'Dietary supplement: Lauricidin.',
  'mechanism': 'Engages AMPK energy-sensing pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Silver Colloid',
  'category': 'supplement',
  'description': 'Dietary supplement: Silver Colloid.',
  'mechanism': 'Influences insulin/PI3K-Akt metabolic signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Iodine Supplement',
  'category': 'supplement',
  'description': 'Dietary supplement: Iodine Supplement.',
  'mechanism': 'Activates Nrf2 antioxidant response element signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Potassium Iodide',
  'category': 'supplement',
  'description': 'Dietary supplement: Potassium Iodide.',
  'mechanism': 'Modulates mTOR/autophagy balance.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': "Lugol's Iodine",
  'category': 'supplement',
  'description': "Dietary supplement: Lugol's Iodine.",
  'mechanism': 'Modulates HPA axis stress-response signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'Supplement safety in pregnancy varies; consult a clinician.'}],
  'drug_interactions': []},
 {'name': 'DHEA',
  'category': 'supplement',
  'description': 'Dietary supplement: DHEA.',
  'mechanism': 'Interacts with thyroid hormone axis signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Pregnenolone',
  'category': 'supplement',
  'description': 'Dietary supplement: Pregnenolone.',
  'mechanism': 'Affects hepatic lipid metabolism pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': '7-Keto DHEA',
  'category': 'supplement',
  'description': 'Dietary supplement: 7-Keto DHEA.',
  'mechanism': 'Supports one-carbon/methylation cycle function.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'DIM Supplement',
  'category': 'supplement',
  'description': 'Dietary supplement: DIM Supplement.',
  'mechanism': 'Influences incretin/GLP-1 signaling pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Calcium D-Glucarate',
  'category': 'supplement',
  'description': 'Dietary supplement: Calcium D-Glucarate.',
  'mechanism': 'Supports mitochondrial NAD+ metabolism.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Indole-3-Carbinol',
  'category': 'supplement',
  'description': 'Dietary supplement: Indole-3-Carbinol.',
  'mechanism': 'Influences iron/hepcidin regulation.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'Supplement safety in pregnancy varies; consult a clinician.'}],
  'drug_interactions': []},
 {'name': 'Broccoli Extract',
  'category': 'supplement',
  'description': 'Dietary supplement: Broccoli Extract.',
  'mechanism': 'Modulates purine and uric acid metabolism.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Sulforaphane Supplement',
  'category': 'supplement',
  'description': 'Dietary supplement: Sulforaphane Supplement.',
  'mechanism': 'Interacts with vitamin D receptor signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'NAC Supplement',
  'category': 'supplement',
  'description': 'Dietary supplement: NAC Supplement.',
  'mechanism': 'May influence renal filtration-related pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Glutathione Liposomal',
  'category': 'supplement',
  'description': 'Dietary supplement: Glutathione Liposomal.',
  'mechanism': 'Modulates NF-κB inflammatory signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Liposomal Vitamin C',
  'category': 'supplement',
  'description': 'Dietary supplement: Liposomal Vitamin C.',
  'mechanism': 'Modulates IL-6/JAK-STAT3 inflammatory signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Liposomal Glutathione',
  'category': 'supplement',
  'description': 'Dietary supplement: Liposomal Glutathione.',
  'mechanism': 'Engages AMPK energy-sensing pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'Supplement safety in pregnancy varies; consult a clinician.'}],
  'drug_interactions': []},
 {'name': 'R-Lipoic Acid',
  'category': 'supplement',
  'description': 'Dietary supplement: R-Lipoic Acid.',
  'mechanism': 'Influences insulin/PI3K-Akt metabolic signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Benfotiamine',
  'category': 'supplement',
  'description': 'Dietary supplement: Benfotiamine.',
  'mechanism': 'Activates Nrf2 antioxidant response element signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Thiamine',
  'category': 'supplement',
  'description': 'Dietary supplement: Thiamine.',
  'mechanism': 'Modulates mTOR/autophagy balance.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Riboflavin-5-Phosphate',
  'category': 'supplement',
  'description': 'Dietary supplement: Riboflavin-5-Phosphate.',
  'mechanism': 'Modulates HPA axis stress-response signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'P5P',
  'category': 'supplement',
  'description': 'Dietary supplement: P5P.',
  'mechanism': 'Interacts with thyroid hormone axis signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Methylcobalamin B12',
  'category': 'supplement',
  'description': 'Dietary supplement: Methylcobalamin B12.',
  'mechanism': 'Affects hepatic lipid metabolism pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'Supplement safety in pregnancy varies; consult a clinician.'}],
  'drug_interactions': []},
 {'name': 'Adenosylcobalamin',
  'category': 'supplement',
  'description': 'Dietary supplement: Adenosylcobalamin.',
  'mechanism': 'Supports one-carbon/methylation cycle function.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Hydroxocobalamin',
  'category': 'supplement',
  'description': 'Dietary supplement: Hydroxocobalamin.',
  'mechanism': 'Influences incretin/GLP-1 signaling pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Methylfolate',
  'category': 'supplement',
  'description': 'Dietary supplement: Methylfolate.',
  'mechanism': 'Supports mitochondrial NAD+ metabolism.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Folinic Acid',
  'category': 'supplement',
  'description': 'Dietary supplement: Folinic Acid.',
  'mechanism': 'Influences iron/hepcidin regulation.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Trimethylglycine',
  'category': 'supplement',
  'description': 'Dietary supplement: Trimethylglycine.',
  'mechanism': 'Modulates purine and uric acid metabolism.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Choline Bitartrate',
  'category': 'supplement',
  'description': 'Dietary supplement: Choline Bitartrate.',
  'mechanism': 'Interacts with vitamin D receptor signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'Supplement safety in pregnancy varies; consult a clinician.'}],
  'drug_interactions': []},
 {'name': 'CDP-Choline',
  'category': 'supplement',
  'description': 'Dietary supplement: CDP-Choline.',
  'mechanism': 'May influence renal filtration-related pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Uridine Monophosphate',
  'category': 'supplement',
  'description': 'Dietary supplement: Uridine Monophosphate.',
  'mechanism': 'Modulates NF-κB inflammatory signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'D-Ribose',
  'category': 'supplement',
  'description': 'Dietary supplement: D-Ribose.',
  'mechanism': 'Modulates IL-6/JAK-STAT3 inflammatory signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'CoQ10 Ubiquinol',
  'category': 'supplement',
  'description': 'Dietary supplement: CoQ10 Ubiquinol.',
  'mechanism': 'Engages AMPK energy-sensing pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'PQQ',
  'category': 'supplement',
  'description': 'Dietary supplement: PQQ.',
  'mechanism': 'Influences insulin/PI3K-Akt metabolic signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Fulvic Acid',
  'category': 'supplement',
  'description': 'Dietary supplement: Fulvic Acid.',
  'mechanism': 'Activates Nrf2 antioxidant response element signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [{'condition': 'pregnancy',
                    'severity': 'caution',
                    'note': 'Supplement safety in pregnancy varies; consult a clinician.'}],
  'drug_interactions': []},
 {'name': 'Trace Mineral Complex',
  'category': 'supplement',
  'description': 'Dietary supplement: Trace Mineral Complex.',
  'mechanism': 'Modulates mTOR/autophagy balance.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Electrolyte Powder',
  'category': 'supplement',
  'description': 'Dietary supplement: Electrolyte Powder.',
  'mechanism': 'Modulates HPA axis stress-response signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Oral Rehydration Salts',
  'category': 'supplement',
  'description': 'Dietary supplement: Oral Rehydration Salts.',
  'mechanism': 'Interacts with thyroid hormone axis signaling.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Magnesium Citrate',
  'category': 'supplement',
  'description': 'Dietary supplement: Magnesium Citrate.',
  'mechanism': 'Affects hepatic lipid metabolism pathways.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []},
 {'name': 'Magnesium Malate',
  'category': 'supplement',
  'description': 'Dietary supplement: Magnesium Malate.',
  'mechanism': 'Supports one-carbon/methylation cycle function.',
  'is_regulated': False,
  'compounds': [],
  'safety_flags': [],
  'drug_interactions': []}]
