"""Tier A evidence claims — every entry has a verifiable PMID and recommendation_intent."""

from __future__ import annotations

# recommendation_intent: primary | collateral | context_only | nutritional_repletion

TIER_A_EVIDENCE_CLAIMS: list[dict] = [
    # --- Metabolic / signaling (primary) ---
    {"intervention_name": "Boswellia serrata", "biomarker_name": "CRP", "pathway_code": "NF_KB",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "41220252",
     "recommendation_intent": "primary",
     "summary": "Boswellic acids reduced CRP in an RCT of knee osteoarthritis."},
    {"intervention_name": "Curcumin", "biomarker_name": "CRP", "pathway_code": "NF_KB",
     "effect": "decreases", "evidence_level": "high", "pmid": "41601662",
     "recommendation_intent": "primary",
     "summary": "Meta-analysis of RCTs found curcumin significantly reduced CRP."},
    {"intervention_name": "Turmeric", "biomarker_name": "CRP", "pathway_code": "NF_KB",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "41601662",
     "recommendation_intent": "collateral",
     "summary": "Turmeric-derived curcuminoids studied for CRP reduction in trials."},
    {"intervention_name": "Ashwagandha", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "31728244",
     "recommendation_intent": "primary",
     "summary": "RCT showing ashwagandha reduced cortisol and perceived stress."},
    {"intervention_name": "Ashwagandha", "biomarker_name": "TSH", "pathway_code": "THYROID_HPT",
     "effect": "decreases", "evidence_level": "low", "pmid": "38003702",
     "recommendation_intent": "primary",
     "summary": "Review summarizes trials of ashwagandha on thyroid and endocrine markers — adjunct only, not hormone replacement."},
    {"intervention_name": "Selenium", "biomarker_name": "TSH", "pathway_code": "THYROID_HPT",
     "effect": "decreases", "evidence_level": "low", "pmid": "42197013",
     "recommendation_intent": "primary",
     "summary": "Selenium supplementation studied for favorable thyroid parameter changes in autoimmune thyroiditis contexts — adjunct only."},
    {"intervention_name": "Milk Thistle", "biomarker_name": "ALT", "pathway_code": "HEPATIC_LIPID",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "40733088",
     "recommendation_intent": "primary",
     "summary": "Silymarin lowered ALT in NAFLD patients in clinical trials."},
    {"intervention_name": "Silymarin", "biomarker_name": "ALT", "pathway_code": "NRF2",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "40733088",
     "recommendation_intent": "primary",
     "summary": "Silymarin phytochemical studied for hepatoprotection in NAFLD."},
    {"intervention_name": "Berberine", "biomarker_name": "HbA1c", "pathway_code": "AMPK",
     "effect": "decreases", "evidence_level": "high", "pmid": "42213651",
     "recommendation_intent": "primary",
     "summary": "Meta-analysis found berberine lowered HbA1c comparably to oral hypoglycemics."},
    {"intervention_name": "Berberine", "biomarker_name": "LDL", "pathway_code": "HEPATIC_LIPID",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "25498346",
     "recommendation_intent": "primary",
     "summary": "RCT evidence for berberine LDL-lowering via hepatic LDL-receptor upregulation."},
    {"intervention_name": "Omega-3", "biomarker_name": "Triglycerides", "pathway_code": "HEPATIC_LIPID",
     "effect": "decreases", "evidence_level": "high", "pmid": "42115081",
     "recommendation_intent": "primary",
     "summary": "Systematic review confirming dose-dependent triglyceride reduction from EPA/DHA."},
    {"intervention_name": "Omega-3", "biomarker_name": "CRP", "pathway_code": "NF_KB",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "42163966",
     "recommendation_intent": "primary",
     "summary": "RCT showing omega-3 reduced inflammatory markers including CRP."},
    {"intervention_name": "Alpha Lipoic Acid", "biomarker_name": "Glucose", "pathway_code": "AMPK",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "41077538",
     "recommendation_intent": "primary",
     "summary": "RCT evidence for ALA improving insulin sensitivity and fasting glucose."},
    {"intervention_name": "Magnesium", "biomarker_name": None, "pathway_code": "INSULIN_PI3K_AKT",
     "effect": "increases", "evidence_level": "high", "pmid": "27530471",
     "recommendation_intent": "primary",
     "summary": "Meta-analysis linking magnesium repletion to improved insulin sensitivity."},
    {"intervention_name": "Vitamin D", "biomarker_name": "Vitamin D", "pathway_code": "VITAMIN_D_RECEPTOR",
     "effect": "increases", "evidence_level": "high", "pmid": "42367170",
     "recommendation_intent": "nutritional_repletion",
     "summary": "RCT confirming D3 supplementation raises serum 25-OH vitamin D."},
    {"intervention_name": "NAD+ Precursors (NR/NMN)", "biomarker_name": None, "pathway_code": "MITOCHONDRIAL_NAD",
     "effect": "increases", "evidence_level": "moderate", "pmid": "42048163",
     "recommendation_intent": "primary",
     "summary": "RCT showing nicotinamide riboside raises whole-blood NAD+ levels."},
    {"intervention_name": "CoQ10", "biomarker_name": None, "pathway_code": "MITOCHONDRIAL_NAD",
     "effect": "increases", "evidence_level": "moderate", "pmid": "42192187",
     "recommendation_intent": "primary",
     "summary": "Meta-analysis of CoQ10 on mitochondrial energy markers."},
    {"intervention_name": "Intermittent Fasting", "biomarker_name": "Insulin", "pathway_code": "AMPK",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "29754952",
     "recommendation_intent": "primary",
     "summary": "Early time-restricted feeding improved insulin sensitivity independent of weight loss in prediabetic men."},
    {"intervention_name": "HIIT", "biomarker_name": "HbA1c", "pathway_code": "AMPK",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "42222064",
     "recommendation_intent": "primary",
     "summary": "Meta-analysis showing HIIT improves glycemic control."},
    {"intervention_name": "Mindfulness-Based Stress Reduction", "biomarker_name": None, "pathway_code": "HPA_AXIS",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "24395196",
     "recommendation_intent": "primary",
     "summary": "Meta-analysis of RCTs showing MBSR reduces cortisol and perceived stress."},
    {"intervention_name": "Sleep Hygiene Optimization", "biomarker_name": "Glucose", "pathway_code": "HPA_AXIS",
     "effect": "decreases", "evidence_level": "low", "pmid": "42325726",
     "recommendation_intent": "collateral",
     "summary": "Observational evidence linking sleep extension to improved insulin sensitivity."},
    {"intervention_name": "Sulforaphane", "biomarker_name": "CRP", "pathway_code": "NF_KB",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "41184790",
     "recommendation_intent": "primary",
     "summary": "Clinical studies link sulforaphane to Nrf2 activation and inflammatory marker modulation."},
    {"intervention_name": "EGCG", "biomarker_name": None, "pathway_code": "AMPK",
     "effect": "increases", "evidence_level": "moderate", "pmid": "41772671",
     "recommendation_intent": "primary",
     "summary": "Green tea catechins studied for AMPK activation and metabolic effects."},
    {"intervention_name": "Allicin", "biomarker_name": "LDL", "pathway_code": "HEPATIC_LIPID",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "40770379",
     "recommendation_intent": "primary",
     "summary": "Garlic-derived allicin studied for lipid-lowering effects in trials."},
    {"intervention_name": "Quercetin", "biomarker_name": "CRP", "pathway_code": "NF_KB",
     "effect": "decreases", "evidence_level": "low", "pmid": "41396378",
     "recommendation_intent": "primary",
     "summary": "Quercetin supplementation studied for inflammatory marker reduction."},
    {"intervention_name": "Anthocyanins", "biomarker_name": "CRP", "pathway_code": "NRF2",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "41247121",
     "recommendation_intent": "primary",
     "summary": "Berry anthocyanins studied for endothelial function and CRP in trials."},
    {"intervention_name": "Resveratrol", "biomarker_name": "Glucose", "pathway_code": "AMPK",
     "effect": "decreases", "evidence_level": "low", "pmid": "42221785",
     "recommendation_intent": "collateral",
     "summary": "Resveratrol studied for glycemic effects in metabolic trials."},

    # --- H. pylori / gastric etiological (primary) ---
    {"intervention_name": "Mastic Gum", "biomarker_name": "H. pylori Urea Breath Test", "pathway_code": "GASTRIC_COLONIZATION",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "19879118",
     "recommendation_intent": "primary",
     "summary": "RCT found mastic gum reduced H. pylori load and improved gastric histology."},
    {"intervention_name": "Mastic Gum", "biomarker_name": "H. pylori Stool Antigen", "pathway_code": "GASTRIC_COLONIZATION",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "19879118",
     "recommendation_intent": "primary",
     "summary": "Mastic gum studied for reducing active H. pylori colonization markers."},
    {"intervention_name": "DGL Licorice", "biomarker_name": "H. pylori Urea Breath Test", "pathway_code": "GI_MUCOSAL_BARRIER",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "493863",
     "recommendation_intent": "primary",
     "summary": "DGL licorice studied as adjunct improving H. pylori eradication rates."},
    {"intervention_name": "Zinc Carnosine", "biomarker_name": "H. pylori Urea Breath Test", "pathway_code": "GI_MUCOSAL_BARRIER",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "35659631",
     "recommendation_intent": "collateral",
     "summary": "Zinc carnosine studied for gastric mucosal healing alongside H. pylori treatment."},
    {"intervention_name": "Berberine", "biomarker_name": "H. pylori Urea Breath Test", "pathway_code": "PATHOGEN_BURDEN",
     "effect": "decreases", "evidence_level": "low", "pmid": "39018799",
     "recommendation_intent": "collateral",
     "summary": "In-vitro and adjunct clinical data for berberine against H. pylori."},
    {"intervention_name": "Sulforaphane", "biomarker_name": "H. pylori Urea Breath Test", "pathway_code": "NF_KB",
     "effect": "decreases", "evidence_level": "preclinical", "pmid": "41184790",
     "recommendation_intent": "collateral",
     "summary": "Preclinical and pilot data for sulforaphane in H. pylori-associated gastric inflammation."},
    {"intervention_name": "Curcumin", "biomarker_name": "H. pylori Urea Breath Test", "pathway_code": "NF_KB",
     "effect": "decreases", "evidence_level": "low", "pmid": "19811613",
     "recommendation_intent": "collateral",
     "summary": "Curcumin studied for gastric inflammation associated with H. pylori, not eradication monotherapy."},
    {"intervention_name": "Ginger", "biomarker_name": "H. pylori Urea Breath Test", "pathway_code": "GI_MUCOSAL_BARRIER",
     "effect": "decreases", "evidence_level": "preclinical", "pmid": "39831446",
     "recommendation_intent": "collateral",
     "summary": "Ginger extracts studied for gastric motility and mucosal comfort in dyspepsia contexts."},

    # --- Exposure serology (context only) ---
    {"intervention_name": "Mastic Gum", "biomarker_name": "H. pylori IgG Antibody", "pathway_code": "GASTRIC_COLONIZATION",
     "effect": "decreases", "evidence_level": "low", "pmid": "19879118",
     "recommendation_intent": "context_only",
     "summary": "IgG reflects exposure history; active infection tests are needed before eradication-oriented interventions."},
    {"intervention_name": "DGL Licorice", "biomarker_name": "H. pylori IgG Antibody", "pathway_code": "GI_MUCOSAL_BARRIER",
     "effect": "decreases", "evidence_level": "low", "pmid": "493863",
     "recommendation_intent": "context_only",
     "summary": "Prior H. pylori exposure serology is not active infection — mucosal support context only after clinician confirms status."},

    # --- Celiac (primary) ---
    {"intervention_name": "Gluten Elimination Diet", "biomarker_name": "tTG IgA", "pathway_code": "FOOD_ANTIGEN_EXPOSURE",
     "effect": "decreases", "evidence_level": "high", "pmid": "42353892",
     "recommendation_intent": "primary",
     "summary": "Strict gluten elimination is the evidence-based management for celiac disease."},
    {"intervention_name": "Gluten Elimination Diet", "biomarker_name": "EMA IgA", "pathway_code": "FOOD_ANTIGEN_EXPOSURE",
     "effect": "decreases", "evidence_level": "high", "pmid": "42353892",
     "recommendation_intent": "primary",
     "summary": "Gluten elimination normalizes celiac serology over time in adherent patients."},
    {"intervention_name": "Iron", "biomarker_name": "Ferritin", "pathway_code": "NUTRIENT_DEFICIENCY",
     "effect": "increases", "evidence_level": "high", "pmid": "42124000",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Iron repletion for deficiency anemia commonly associated with celiac disease."},
    {"intervention_name": "B12", "biomarker_name": "B12", "pathway_code": "NUTRIENT_DEFICIENCY",
     "effect": "increases", "evidence_level": "high", "pmid": "42393020",
     "recommendation_intent": "nutritional_repletion",
     "summary": "B12 repletion when malabsorption causes deficiency in celiac disease."},
    {"intervention_name": "Glutamine", "biomarker_name": "tTG IgA", "pathway_code": "GI_MUCOSAL_BARRIER",
     "effect": "decreases", "evidence_level": "low", "pmid": "42366260",
     "recommendation_intent": "collateral",
     "summary": "Glutamine studied for intestinal mucosal recovery — adjunct to gluten elimination, not replacement."},

    # --- Allergy IgE (primary / collateral) ---
    {"intervention_name": "Quercetin", "biomarker_name": "Total IgE", "pathway_code": "IGE_SENSITIZATION",
     "effect": "decreases", "evidence_level": "low", "pmid": "41312779",
     "recommendation_intent": "collateral",
     "summary": "Quercetin studied for mast cell stabilization — does not replace allergen avoidance."},
    {"intervention_name": "Luteolin", "biomarker_name": "Peanut IgE", "pathway_code": "IGE_SENSITIZATION",
     "effect": "decreases", "evidence_level": "preclinical", "pmid": "24382176",
     "recommendation_intent": "collateral",
     "summary": "Luteolin studied for mast cell modulation in sensitization models."},
    {"intervention_name": "Vitamin D", "biomarker_name": "Total IgE", "pathway_code": "IGE_SENSITIZATION",
     "effect": "decreases", "evidence_level": "low", "pmid": "42367170",
     "recommendation_intent": "collateral",
     "summary": "Vitamin D status associated with IgE and atopy in observational studies."},

    # --- Nutritional repletion ---
    {"intervention_name": "B12", "biomarker_name": "B12", "pathway_code": "ONE_CARBON_METHYLATION",
     "effect": "increases", "evidence_level": "high", "pmid": "42393020",
     "recommendation_intent": "nutritional_repletion",
     "summary": "B12 supplementation corrects measured B12 deficiency."},
    {"intervention_name": "B12", "biomarker_name": "Methylmalonic Acid", "pathway_code": "ONE_CARBON_METHYLATION",
     "effect": "decreases", "evidence_level": "high", "pmid": "42393020",
     "recommendation_intent": "nutritional_repletion",
     "summary": "B12 repletion lowers elevated methylmalonic acid when functional B12 deficiency is present."},
    {"intervention_name": "B12", "biomarker_name": "Homocysteine", "pathway_code": "ONE_CARBON_METHYLATION",
     "effect": "decreases", "evidence_level": "high", "pmid": "42393020",
     "recommendation_intent": "nutritional_repletion",
     "summary": "B12 repletion lowers elevated homocysteine when one-carbon deficiency is contributing."},
    {"intervention_name": "Folate", "biomarker_name": "Homocysteine", "pathway_code": "ONE_CARBON_METHYLATION",
     "effect": "decreases", "evidence_level": "high", "pmid": "42231372",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Folate repletion lowers elevated homocysteine when folate-dependent remethylation is impaired."},
    {"intervention_name": "Folate", "biomarker_name": "Folate", "pathway_code": "ONE_CARBON_METHYLATION",
     "effect": "increases", "evidence_level": "high", "pmid": "42231372",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Folate supplementation corrects measured folate deficiency."},
    {"intervention_name": "Iron", "biomarker_name": "Ferritin", "pathway_code": "IRON_HEPCIDIN",
     "effect": "increases", "evidence_level": "high", "pmid": "42124000",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Iron supplementation raises ferritin when deficiency is confirmed."},
    {"intervention_name": "Iron", "biomarker_name": "Transferrin Saturation", "pathway_code": "IRON_HEPCIDIN",
     "effect": "increases", "evidence_level": "high", "pmid": "42124000",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Iron repletion improves low transferrin saturation when iron availability is reduced."},
    {"intervention_name": "Iron", "biomarker_name": "Soluble Transferrin Receptor", "pathway_code": "IRON_HEPCIDIN",
     "effect": "decreases", "evidence_level": "high", "pmid": "42124000",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Iron repletion lowers elevated soluble transferrin receptor when functional iron deficiency is present."},
    {"intervention_name": "Iron", "biomarker_name": "TIBC", "pathway_code": "IRON_HEPCIDIN",
     "effect": "decreases", "evidence_level": "high", "pmid": "42124000",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Iron repletion lowers elevated total iron-binding capacity when iron stores are depleted."},
    {"intervention_name": "Iron", "biomarker_name": "UIBC", "pathway_code": "IRON_HEPCIDIN",
     "effect": "decreases", "evidence_level": "high", "pmid": "42124000",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Iron repletion lowers elevated unsaturated iron-binding capacity when iron availability is reduced."},
    {"intervention_name": "Zinc", "biomarker_name": "Zinc", "pathway_code": "NUTRIENT_DEFICIENCY",
     "effect": "increases", "evidence_level": "moderate", "pmid": "42314307",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Zinc supplementation corrects zinc deficiency."},
    {"intervention_name": "Calcium", "biomarker_name": "Calcium", "pathway_code": "NUTRIENT_DEFICIENCY",
     "effect": "increases", "evidence_level": "moderate", "pmid": "42321952",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Oral calcium supplementation raised serum calcium in women with confirmed hypocalcemia."},
    {"intervention_name": "Potassium", "biomarker_name": "Potassium", "pathway_code": "NUTRIENT_DEFICIENCY",
     "effect": "increases", "evidence_level": "moderate", "pmid": "35597332",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Potassium supplementation corrected hypokalemia in a randomized peritoneal dialysis trial."},
    {"intervention_name": "Magnesium", "biomarker_name": "Magnesium", "pathway_code": "NUTRIENT_DEFICIENCY",
     "effect": "increases", "evidence_level": "high", "pmid": "27530471",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Magnesium supplementation raises serum magnesium and improves deficiency-related metabolic markers."},
    {"intervention_name": "Copper", "biomarker_name": "Copper", "pathway_code": "NUTRIENT_DEFICIENCY",
     "effect": "increases", "evidence_level": "moderate", "pmid": "22444781",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Oral copper supplementation increased blood copper enzyme activity in a randomized trial."},
    {"intervention_name": "Selenium", "biomarker_name": "Selenium", "pathway_code": "NUTRIENT_DEFICIENCY",
     "effect": "increases", "evidence_level": "moderate", "pmid": "34859459",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Selenium supplementation raised serum selenium in a randomized controlled trial."},
    {"intervention_name": "Vitamin C", "biomarker_name": "Vitamin C", "pathway_code": "NUTRIENT_DEFICIENCY",
     "effect": "increases", "evidence_level": "moderate", "pmid": "30069463",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Vitamin C supplementation meta-analysis of RCTs supports repletion dosing for deficiency contexts."},
    {"intervention_name": "Glutamine", "biomarker_name": "Prealbumin", "pathway_code": "NUTRIENT_DEFICIENCY",
     "effect": "increases", "evidence_level": "moderate", "pmid": "15774291",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Glutamine-supplemented enteral nutrition improved protein metabolic markers including prealbumin in clinical malnutrition contexts."},
    {"intervention_name": "Vitamin B6", "biomarker_name": "Vitamin B6", "pathway_code": "NUTRIENT_DEFICIENCY",
     "effect": "increases", "evidence_level": "moderate", "pmid": "41874466",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Pyridoxine supplementation in a randomized trial corrected functional B6-dependent metabolic deficits."},
    {"intervention_name": "Vitamin B1", "biomarker_name": "Vitamin B1", "pathway_code": "NUTRIENT_DEFICIENCY",
     "effect": "increases", "evidence_level": "moderate", "pmid": "42059045",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Thiamine supplementation in a randomized controlled trial improved deficiency-related outcomes in high-risk patients."},
    {"intervention_name": "Vitamin B2", "biomarker_name": "Vitamin B2", "pathway_code": "NUTRIENT_DEFICIENCY",
     "effect": "increases", "evidence_level": "moderate", "pmid": "42403423",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Riboflavin supplementation evidence supports repletion in measured B2 deficiency contexts."},
    {"intervention_name": "Vitamin A", "biomarker_name": "Vitamin A", "pathway_code": "NUTRIENT_DEFICIENCY",
     "effect": "increases", "evidence_level": "moderate", "pmid": "42060870",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Vitamin A supplementation RCT evidence addresses deficiency-related blindness prevention."},
    {"intervention_name": "Vitamin E", "biomarker_name": "Vitamin E", "pathway_code": "NUTRIENT_DEFICIENCY",
     "effect": "increases", "evidence_level": "moderate", "pmid": "42374454",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Vitamin E supplementation meta-analysis supports repletion in deficiency and metabolic liver contexts."},
    {"intervention_name": "Vitamin K2", "biomarker_name": "Vitamin K", "pathway_code": "NUTRIENT_DEFICIENCY",
     "effect": "increases", "evidence_level": "moderate", "pmid": "42280344",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Menaquinone-7 supplementation studied for vitamin K repletion and bone-related outcomes in clinical trials."},
    {"intervention_name": "Vitamin D", "biomarker_name": "Calcium", "pathway_code": "NUTRIENT_DEFICIENCY",
     "effect": "increases", "evidence_level": "moderate", "pmid": "41604835",
     "recommendation_intent": "collateral",
     "summary": "Combined calcium and vitamin D reduced hypocalcemia risk after thyroidectomy in RCT evidence."},
    {"intervention_name": "B12", "biomarker_name": "MCV", "pathway_code": "ONE_CARBON_METHYLATION",
     "effect": "decreases", "evidence_level": "high", "pmid": "42393020",
     "recommendation_intent": "nutritional_repletion",
     "summary": "B12 repletion can normalize macrocytosis when deficiency is the cause."},
    {"intervention_name": "Folate", "biomarker_name": "MCV", "pathway_code": "ONE_CARBON_METHYLATION",
     "effect": "decreases", "evidence_level": "high", "pmid": "42231372",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Folate repletion can normalize macrocytosis when deficiency is the cause."},
    {"intervention_name": "Iron", "biomarker_name": "RDW", "pathway_code": "IRON_HEPCIDIN",
     "effect": "decreases", "evidence_level": "high", "pmid": "42124000",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Iron repletion can reduce elevated RDW when iron deficiency is contributing."},
    {"intervention_name": "B12", "biomarker_name": "MCH", "pathway_code": "ONE_CARBON_METHYLATION",
     "effect": "decreases", "evidence_level": "high", "pmid": "42393020",
     "recommendation_intent": "nutritional_repletion",
     "summary": "B12 repletion can normalize elevated MCH when macrocytic deficiency is present."},

    # --- IL-6 / JAK-STAT3 (routable when CRP is elevated) ---
    {"intervention_name": "Curcumin", "biomarker_name": "CRP", "pathway_code": "IL6_JAK_STAT3",
     "effect": "decreases", "evidence_level": "high", "pmid": "41601662",
     "recommendation_intent": "primary",
     "summary": "Curcumin RCT meta-analysis reported CRP reduction consistent with IL-6 pathway modulation."},
    {"intervention_name": "Boswellia serrata", "biomarker_name": "CRP", "pathway_code": "IL6_JAK_STAT3",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "41220252",
     "recommendation_intent": "primary",
     "summary": "Boswellic acids reduced inflammatory markers including CRP in osteoarthritis RCTs."},
    {"intervention_name": "Omega-3", "biomarker_name": "CRP", "pathway_code": "IL6_JAK_STAT3",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "42163966",
     "recommendation_intent": "primary",
     "summary": "Omega-3 supplementation reduced CRP and IL-6 in cardiovascular risk trials."},

    # --- Thyroid/HPT axis (nutrient co-evaluation with macrocytic indices) ---
    {"intervention_name": "B12", "biomarker_name": "MCV", "pathway_code": "THYROID_HPT",
     "effect": "decreases", "evidence_level": "high", "pmid": "42393020",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Macrocytosis warrants B12 evaluation; thyroid disease and B12 deficiency can coexist clinically."},
    {"intervention_name": "Folate", "biomarker_name": "MCV", "pathway_code": "THYROID_HPT",
     "effect": "decreases", "evidence_level": "high", "pmid": "42231372",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Macrocytosis warrants folate evaluation alongside thyroid axis assessment."},
    {"intervention_name": "Iron", "biomarker_name": "RDW", "pathway_code": "THYROID_HPT",
     "effect": "decreases", "evidence_level": "high", "pmid": "42124000",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Elevated RDW prompts iron studies when evaluating thyroid-related hematologic patterns."},

    # --- Autoimmune targeting ---
    {"intervention_name": "Curcumin", "biomarker_name": "ANA", "pathway_code": "AUTOIMMUNE_TARGETING",
     "effect": "decreases", "evidence_level": "low", "pmid": "41601662",
     "recommendation_intent": "primary",
     "summary": "Curcumin studied for inflammatory modulation in autoimmune and rheumatic contexts."},
    {"intervention_name": "Omega-3", "biomarker_name": "ANA", "pathway_code": "AUTOIMMUNE_TARGETING",
     "effect": "decreases", "evidence_level": "low", "pmid": "42163966",
     "recommendation_intent": "primary",
     "summary": "Omega-3 fatty acids studied for inflammatory burden in autoimmune disease trials."},
    {"intervention_name": "Quercetin", "biomarker_name": "ANA", "pathway_code": "AUTOIMMUNE_TARGETING",
     "effect": "decreases", "evidence_level": "low", "pmid": "41396378",
     "recommendation_intent": "primary",
     "summary": "Quercetin studied for antioxidant and inflammatory pathway modulation."},

    # --- IgE sensitization (biomarker-direct primary) ---
    {"intervention_name": "Quercetin", "biomarker_name": "Peanut IgE", "pathway_code": "IGE_SENSITIZATION",
     "effect": "decreases", "evidence_level": "low", "pmid": "41312779",
     "recommendation_intent": "primary",
     "summary": "Quercetin studied for mast cell stabilization — adjunct to allergen avoidance, not replacement."},
    {"intervention_name": "Luteolin", "biomarker_name": "Peanut IgE", "pathway_code": "IGE_SENSITIZATION",
     "effect": "decreases", "evidence_level": "preclinical", "pmid": "24382176",
     "recommendation_intent": "primary",
     "summary": "Luteolin studied for mast cell modulation in food sensitization models."},
    {"intervention_name": "Vitamin D", "biomarker_name": "Total IgE", "pathway_code": "IGE_SENSITIZATION",
     "effect": "decreases", "evidence_level": "low", "pmid": "42367170",
     "recommendation_intent": "primary",
     "summary": "Vitamin D status associated with IgE and atopy in observational studies."},

    # --- GLP-1 / incretin metabolic routing ---
    {"intervention_name": "Berberine", "biomarker_name": "HbA1c", "pathway_code": "GLP1_INCRETINS",
     "effect": "decreases", "evidence_level": "high", "pmid": "42213651",
     "recommendation_intent": "primary",
     "summary": "Berberine meta-analysis reported HbA1c reduction via incretin-sensitive metabolic pathways."},
    {"intervention_name": "HIIT", "biomarker_name": "HbA1c", "pathway_code": "GLP1_INCRETINS",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "42222064",
     "recommendation_intent": "primary",
     "summary": "HIIT improves glycemic control and insulin sensitivity in meta-analyses."},
    {"intervention_name": "Intermittent Fasting", "biomarker_name": "Insulin", "pathway_code": "GLP1_INCRETINS",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "29754952",
     "recommendation_intent": "primary",
     "summary": "Time-restricted eating improved fasting insulin in RCT evidence."},

    # --- Urinary tract pathogen context ---
    {"intervention_name": "Berberine", "biomarker_name": "Urine Culture", "pathway_code": "URINARY_PATHOGEN",
     "effect": "decreases", "evidence_level": "low", "pmid": "33137930",
     "recommendation_intent": "primary",
     "summary": "Berberine has antimicrobial activity in UTI models — not a substitute for prescribed antibiotics."},
    {"intervention_name": "NAC", "biomarker_name": "Urine Culture", "pathway_code": "URINARY_PATHOGEN",
     "effect": "decreases", "evidence_level": "preclinical", "pmid": "40726828",
     "recommendation_intent": "primary",
     "summary": "NAC studied for biofilm disruption in urinary tract infection models."},
    {"intervention_name": "Berberine", "biomarker_name": "Urine Culture", "pathway_code": "BIOFILM_ADHESION",
     "effect": "decreases", "evidence_level": "low", "pmid": "33137930",
     "recommendation_intent": "primary",
     "summary": "Berberine antimicrobial data relevant to biofilm-associated urinary pathogens."},

    # --- Additional priority-pathway coverage (existing PMIDs only) ---
    {"intervention_name": "Iron", "biomarker_name": "Hemoglobin", "pathway_code": "IRON_HEPCIDIN",
     "effect": "increases", "evidence_level": "high", "pmid": "42124000",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Iron repletion raises hemoglobin when iron-deficiency anemia is confirmed."},
    {"intervention_name": "Vitamin D", "biomarker_name": None, "pathway_code": "VITAMIN_D_RECEPTOR",
     "effect": "increases", "evidence_level": "moderate", "pmid": "42367170",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Vitamin D receptor signaling supported when 25-OH vitamin D is repleted in trials."},
    {"intervention_name": "Magnesium", "biomarker_name": None, "pathway_code": "VITAMIN_D_RECEPTOR",
     "effect": "increases", "evidence_level": "moderate", "pmid": "27530471",
     "recommendation_intent": "primary",
     "summary": "Magnesium is a cofactor in vitamin D metabolism and activation."},
    {"intervention_name": "Sulforaphane", "biomarker_name": None, "pathway_code": "NRF2",
     "effect": "increases", "evidence_level": "moderate", "pmid": "41184790",
     "recommendation_intent": "primary",
     "summary": "Sulforaphane activates Nrf2 antioxidant response pathways in clinical studies."},
    {"intervention_name": "Anthocyanins", "biomarker_name": None, "pathway_code": "NRF2",
     "effect": "increases", "evidence_level": "moderate", "pmid": "41247121",
     "recommendation_intent": "primary",
     "summary": "Berry anthocyanins studied for Nrf2-linked antioxidant and endothelial effects."},
    {"intervention_name": "DGL Licorice", "biomarker_name": "H. pylori Stool Antigen", "pathway_code": "GASTRIC_COLONIZATION",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "493863",
     "recommendation_intent": "primary",
     "summary": "DGL licorice studied as adjunct in H. pylori management protocols."},
    {"intervention_name": "Iron", "biomarker_name": "Ferritin", "pathway_code": "FOOD_ANTIGEN_EXPOSURE",
     "effect": "increases", "evidence_level": "high", "pmid": "42124000",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Iron repletion addresses deficiency anemia commonly seen with celiac malabsorption."},
    {"intervention_name": "B12", "biomarker_name": "B12", "pathway_code": "FOOD_ANTIGEN_EXPOSURE",
     "effect": "increases", "evidence_level": "high", "pmid": "42393020",
     "recommendation_intent": "nutritional_repletion",
     "summary": "B12 repletion when malabsorption accompanies food-antigen-driven enteropathy."},
    {"intervention_name": "Alpha Lipoic Acid", "biomarker_name": None, "pathway_code": "MITOCHONDRIAL_NAD",
     "effect": "increases", "evidence_level": "moderate", "pmid": "41077538",
     "recommendation_intent": "primary",
     "summary": "ALA studied for mitochondrial redox support and insulin sensitivity."},
    {"intervention_name": "Resveratrol", "biomarker_name": None, "pathway_code": "MITOCHONDRIAL_NAD",
     "effect": "increases", "evidence_level": "low", "pmid": "42221785",
     "recommendation_intent": "primary",
     "summary": "Resveratrol studied for sirtuin and mitochondrial metabolism pathways."},
    {"intervention_name": "Curcumin", "biomarker_name": "H. pylori Urea Breath Test", "pathway_code": "PATHOGEN_BURDEN",
     "effect": "decreases", "evidence_level": "low", "pmid": "19811613",
     "recommendation_intent": "primary",
     "summary": "Curcumin studied for gastric inflammation associated with pathogen burden — not eradication monotherapy."},

    # --- Culture / pathogen burden ---
    {"intervention_name": "Berberine", "biomarker_name": "Urine Culture", "pathway_code": "PATHOGEN_BURDEN",
     "effect": "decreases", "evidence_level": "low", "pmid": "33137930",
     "recommendation_intent": "primary",
     "summary": "Berberine has antimicrobial activity in UTI models — adjunct only, not antibiotic replacement."},
    {"intervention_name": "NAC", "biomarker_name": "Urine Culture", "pathway_code": "PATHOGEN_BURDEN",
     "effect": "decreases", "evidence_level": "preclinical", "pmid": "40726828",
     "recommendation_intent": "primary",
     "summary": "NAC studied for biofilm disruption in urinary infection models."},
    {"intervention_name": "NAC", "biomarker_name": "Urine Culture", "pathway_code": "BIOFILM_ADHESION",
     "effect": "decreases", "evidence_level": "preclinical", "pmid": "40726828",
     "recommendation_intent": "primary",
     "summary": "NAC studied for biofilm disruption — adjunct context only."},

    # --- PGx context only ---
    {"intervention_name": "Berberine", "biomarker_name": "CYP2D6 Genotype", "pathway_code": "DRUG_METABOLISM_VARIANT",
     "effect": "decreases", "evidence_level": "preclinical", "pmid": "39569501",
     "recommendation_intent": "context_only",
     "summary": "Berberine inhibits CYP enzymes — relevant interaction context for poor metabolizers on CYP2D6 substrates."},
    {"intervention_name": "Berberine", "biomarker_name": "CYP2C19 Genotype", "pathway_code": "DRUG_METABOLISM_VARIANT",
     "effect": "decreases", "evidence_level": "preclinical", "pmid": "39569501",
     "recommendation_intent": "context_only",
     "summary": "Berberine inhibits CYP2C19 — relevant interaction context for poor metabolizers on clopidogrel and PPI substrates."},
    {"intervention_name": "Curcumin", "biomarker_name": "CYP2D6 Genotype", "pathway_code": "DRUG_METABOLISM_VARIANT",
     "effect": "decreases", "evidence_level": "preclinical", "pmid": "41601662",
     "recommendation_intent": "context_only",
     "summary": "Curcumin modulates CYP activity — adjunct interaction context for CYP2D6 intermediate metabolizers on psychotropic substrates."},
    {"intervention_name": "Quercetin", "biomarker_name": "DPYD Genotype", "pathway_code": "DRUG_METABOLISM_VARIANT",
     "effect": "decreases", "evidence_level": "preclinical", "pmid": "41396378",
     "recommendation_intent": "context_only",
     "summary": "Flavonoids can affect drug-metabolizing enzymes — interaction context when DPYD variants guide fluoropyrimidine dosing."},

    # --- Niche: lactoferrin (iron repletion + biofilm disruption) ---
    {"intervention_name": "Lactoferrin", "biomarker_name": "Ferritin", "pathway_code": "IRON_HEPCIDIN",
     "effect": "increases", "evidence_level": "moderate", "pmid": "42302886",
     "recommendation_intent": "nutritional_repletion",
     "summary": "RCT in children with iron-deficiency anemia reported lactoferrin raised ferritin with fewer GI side effects than ferrous sulfate."},
    {"intervention_name": "Lactoferrin", "biomarker_name": "Ferritin", "pathway_code": "NUTRIENT_DEFICIENCY",
     "effect": "increases", "evidence_level": "moderate", "pmid": "42302886",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Lactoferrin supplementation improved iron indices in confirmed iron-deficiency anemia."},
    {"intervention_name": "Lactoferrin", "biomarker_name": "Iron", "pathway_code": "IRON_HEPCIDIN",
     "effect": "increases", "evidence_level": "moderate", "pmid": "42302886",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Lactoferrin increased serum iron and transferrin saturation in iron-deficiency anemia."},
    {"intervention_name": "Lactoferrin", "biomarker_name": "Hemoglobin", "pathway_code": "IRON_HEPCIDIN",
     "effect": "increases", "evidence_level": "moderate", "pmid": "42302886",
     "recommendation_intent": "nutritional_repletion",
     "summary": "Lactoferrin raised hemoglobin in iron-deficiency anemia versus elemental iron."},
    {"intervention_name": "Lactoferrin", "biomarker_name": "Urine Culture", "pathway_code": "BIOFILM_ADHESION",
     "effect": "decreases", "evidence_level": "preclinical", "pmid": "18977641",
     "recommendation_intent": "primary",
     "summary": "In vitro data show lactoferrin disrupts established biofilms — adjunct context only, not antibiotic replacement."},
    {"intervention_name": "Lactoferrin", "biomarker_name": "Urine Culture", "pathway_code": "PATHOGEN_BURDEN",
     "effect": "decreases", "evidence_level": "preclinical", "pmid": "18977641",
     "recommendation_intent": "collateral",
     "summary": "Lactoferrin reduced biofilm viability in preclinical models relevant to persistent colonization."},
    {"intervention_name": "Lactoferrin", "biomarker_name": "Fecal Lactoferrin", "pathway_code": "PATHOGEN_BURDEN",
     "effect": "decreases", "evidence_level": "preclinical", "pmid": "18977641",
     "recommendation_intent": "primary",
     "summary": "Elevated fecal lactoferrin reflects GI inflammation; lactoferrin studied for mucosal and biofilm contexts — not a diagnostic substitute."},
    {"intervention_name": "Colostrum", "biomarker_name": "Fecal Lactoferrin", "pathway_code": "GI_MUCOSAL_BARRIER",
     "effect": "decreases", "evidence_level": "low", "pmid": "41925999",
     "recommendation_intent": "primary",
     "summary": "Bovine colostrum provides lactoferrin studied for mucosal support when GI inflammation markers are elevated."},
    {"intervention_name": "Colostrum", "biomarker_name": "Fecal Calprotectin", "pathway_code": "GI_MUCOSAL_BARRIER",
     "effect": "decreases", "evidence_level": "low", "pmid": "41925999",
     "recommendation_intent": "primary",
     "summary": "Lactoferrin-rich colostrum studied in pediatric IBD where fecal calprotectin tracks mucosal inflammation — adjunct only."},
    {"intervention_name": "Curcumin", "biomarker_name": "Fecal Calprotectin", "pathway_code": "GI_MUCOSAL_BARRIER",
     "effect": "decreases", "evidence_level": "low", "pmid": "39403348",
     "recommendation_intent": "primary",
     "summary": "Curcumin/Qing Dai combination reported clinical benefit in active ulcerative colitis where calprotectin reflects disease activity."},
    {"intervention_name": "Glutamine", "biomarker_name": "Fecal Calprotectin", "pathway_code": "GI_MUCOSAL_BARRIER",
     "effect": "decreases", "evidence_level": "low", "pmid": "39397201",
     "recommendation_intent": "primary",
     "summary": "Meta-analysis of glutamine trials on gut permeability — indirect support when fecal calprotectin signals mucosal injury."},

    # --- Exocrine pancreatic insufficiency (fecal elastase) ---
    {"intervention_name": "Pancreatin", "biomarker_name": "Pancreatic Elastase", "pathway_code": "NUTRIENT_DEFICIENCY",
     "effect": "increases", "evidence_level": "moderate", "pmid": "39299226",
     "recommendation_intent": "primary",
     "summary": "Systematic review supports pancreatic enzyme replacement when fecal elastase confirms exocrine insufficiency."},
    {"intervention_name": "Pancreatin", "biomarker_name": "Pancreatic Elastase", "pathway_code": "GI_MUCOSAL_BARRIER",
     "effect": "increases", "evidence_level": "moderate", "pmid": "39299226",
     "recommendation_intent": "primary",
     "summary": "Enzyme replacement improves nutrient absorption when low fecal elastase indicates pancreatic exocrine failure."},

    # --- Niche: D-Mannose UTI prophylaxis ---
    {"intervention_name": "D-Mannose", "biomarker_name": "Urine Culture", "pathway_code": "URINARY_PATHOGEN",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "23633128",
     "recommendation_intent": "primary",
     "summary": "RCT reported D-mannose prophylaxis reduced recurrent UTI versus no prophylaxis — not a substitute for acute antibiotic therapy."},
    {"intervention_name": "D-Mannose", "biomarker_name": "Urine Culture", "pathway_code": "PATHOGEN_BURDEN",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "23633128",
     "recommendation_intent": "primary",
     "summary": "D-mannose reduced recurrent UTI episodes in women after acute cystitis treatment."},

    # --- Respiratory pathogen / biofilm niche ---
    {"intervention_name": "Berberine", "biomarker_name": "Throat Culture", "pathway_code": "RESPIRATORY_PATHOGEN",
     "effect": "decreases", "evidence_level": "low", "pmid": "41575198",
     "recommendation_intent": "primary",
     "summary": "Berberine has antimicrobial activity in respiratory infection models — adjunct only, not antibiotic replacement."},
    {"intervention_name": "NAC", "biomarker_name": "Throat Culture", "pathway_code": "RESPIRATORY_PATHOGEN",
     "effect": "decreases", "evidence_level": "preclinical", "pmid": "40726828",
     "recommendation_intent": "primary",
     "summary": "NAC studied for biofilm disruption in respiratory infection models — adjunct context only."},
    {"intervention_name": "Lactoferrin", "biomarker_name": "Throat Culture", "pathway_code": "RESPIRATORY_PATHOGEN",
     "effect": "decreases", "evidence_level": "preclinical", "pmid": "31681240",
     "recommendation_intent": "primary",
     "summary": "Preclinical data show lactoferrin disrupts pneumococcal biofilms — adjunct only, not antibiotic replacement."},
    {"intervention_name": "Lactoferrin", "biomarker_name": "Throat Culture", "pathway_code": "BIOFILM_ADHESION",
     "effect": "decreases", "evidence_level": "preclinical", "pmid": "31681240",
     "recommendation_intent": "collateral",
     "summary": "Lactoferrin eradicated established respiratory biofilms in vitro via DNase-associated activity."},
    {"intervention_name": "NAC", "biomarker_name": "Throat Culture", "pathway_code": "RESPIRATORY_PATHOGEN",
     "effect": "decreases", "evidence_level": "preclinical", "pmid": "40726828",
     "recommendation_intent": "collateral",
     "summary": "NAC studied for biofilm disruption in respiratory infection models — adjunct context only."},
    {"intervention_name": "Berberine", "biomarker_name": "Sputum Culture", "pathway_code": "RESPIRATORY_PATHOGEN",
     "effect": "decreases", "evidence_level": "low", "pmid": "41575198",
     "recommendation_intent": "primary",
     "summary": "Berberine has antimicrobial activity in respiratory infection models — adjunct only, not antibiotic replacement."},
    {"intervention_name": "NAC", "biomarker_name": "Sputum Culture", "pathway_code": "RESPIRATORY_PATHOGEN",
     "effect": "decreases", "evidence_level": "preclinical", "pmid": "40726828",
     "recommendation_intent": "primary",
     "summary": "NAC studied for biofilm disruption in lower respiratory infection models — adjunct context only."},
    {"intervention_name": "Lactoferrin", "biomarker_name": "Sputum Culture", "pathway_code": "RESPIRATORY_PATHOGEN",
     "effect": "decreases", "evidence_level": "preclinical", "pmid": "31681240",
     "recommendation_intent": "primary",
     "summary": "Lactoferrin studied for respiratory pathogen and biofilm contexts — adjunct only, not antibiotic replacement."},

    # --- Hepatotropic viral (collateral hepatoprotection, not antiviral monotherapy) ---
    {"intervention_name": "Milk Thistle", "biomarker_name": "ALT", "pathway_code": "HEPATOTROPIC_VIRAL",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "40733088",
     "recommendation_intent": "primary",
     "summary": "Silymarin lowered ALT in NAFLD trials — hepatoprotection context when hepatotropic markers and transaminases are elevated."},
    {"intervention_name": "NAC", "biomarker_name": "ALT", "pathway_code": "HEPATOTROPIC_VIRAL",
     "effect": "decreases", "evidence_level": "low", "pmid": "39113864",
     "recommendation_intent": "primary",
     "summary": "NAC studied for glutathione support in liver injury contexts — not antiviral monotherapy."},
    {"intervention_name": "Milk Thistle", "biomarker_name": "Hepatitis B Surface Antigen", "pathway_code": "HEPATOTROPIC_VIRAL",
     "effect": "decreases", "evidence_level": "low", "pmid": "40733088",
     "recommendation_intent": "collateral",
     "summary": "Silymarin studied for hepatoprotection and ALT reduction in chronic liver disease — not HBV eradication therapy."},
    {"intervention_name": "Silymarin", "biomarker_name": "ALT", "pathway_code": "HEPATOTROPIC_VIRAL",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "40733088",
     "recommendation_intent": "primary",
     "summary": "Silymarin phytochemical studied for ALT reduction in chronic liver disease trials."},
    {"intervention_name": "Silymarin", "biomarker_name": "Hepatitis B Surface Antigen", "pathway_code": "HEPATOTROPIC_VIRAL",
     "effect": "decreases", "evidence_level": "low", "pmid": "40733088",
     "recommendation_intent": "collateral",
     "summary": "Silymarin phytochemical studied for liver enzyme support when hepatotropic viral markers are present."},

    # --- Purine/uric acid metabolism (hyperuricemia signaling) ---
    {"intervention_name": "Quercetin", "biomarker_name": "Uric Acid", "pathway_code": "PURINE_URIC_ACID",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "26785820",
     "recommendation_intent": "primary",
     "summary": "RCT in pre-hyperuricaemic males reported quercetin supplementation significantly lowered plasma uric acid."},
    {"intervention_name": "Quercetin", "biomarker_name": "Uric Acid", "pathway_code": "NF_KB",
     "effect": "decreases", "evidence_level": "low", "pmid": "26785820",
     "recommendation_intent": "collateral",
     "summary": "Elevated uric acid activates inflammatory signaling; quercetin lowered uric acid in a human RCT."},
    {"intervention_name": "Berberine", "biomarker_name": "Uric Acid", "pathway_code": "PURINE_URIC_ACID",
     "effect": "decreases", "evidence_level": "preclinical", "pmid": "41132832",
     "recommendation_intent": "primary",
     "summary": "Preclinical work links plant-derived berberine to hepatic uric acid degradation and hyperuricemia amelioration."},
    {"intervention_name": "Quercetin", "biomarker_name": "Uric Acid", "pathway_code": "PURINE_URIC_ACID",
     "effect": "decreases", "evidence_level": "low", "pmid": "39990611",
     "recommendation_intent": "primary",
     "summary": "Real-life clinical studies of quercetin phytosome reported improvements in hyperuricemia management."},

    # --- mTOR/autophagy balance (metabolic signaling) ---
    {"intervention_name": "Intermittent Fasting", "biomarker_name": "Insulin", "pathway_code": "MTOR_AUTOPHAGY",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "29754952",
     "recommendation_intent": "primary",
     "summary": "Early time-restricted feeding improved insulin sensitivity without weight loss — relevant to reduced insulin-driven mTOR signaling."},
    {"intervention_name": "Intermittent Fasting", "biomarker_name": "Glucose", "pathway_code": "MTOR_AUTOPHAGY",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "29754952",
     "recommendation_intent": "primary",
     "summary": "Time-restricted feeding improved glycemic control and insulin resistance in prediabetic adults."},
    {"intervention_name": "EGCG", "biomarker_name": "Glucose", "pathway_code": "MTOR_AUTOPHAGY",
     "effect": "decreases", "evidence_level": "low", "pmid": "34356308",
     "recommendation_intent": "primary",
     "summary": "Literature review links AMPK activation (green tea catechin mechanism) with modulation of mTOR/autophagy balance."},

    # --- Renal filtration function ---
    {"intervention_name": "Omega-3", "biomarker_name": "eGFR", "pathway_code": "RENAL_FILTRATION",
     "effect": "increases", "evidence_level": "moderate", "pmid": "25104273",
     "recommendation_intent": "primary",
     "summary": "Alpha Omega Trial reported EPA/DHA supplementation slowed creatinine-cystatin C-based eGFR decline after MI."},
    {"intervention_name": "Omega-3", "biomarker_name": "Creatinine", "pathway_code": "RENAL_FILTRATION",
     "effect": "decreases", "evidence_level": "moderate", "pmid": "25104273",
     "recommendation_intent": "primary",
     "summary": "Long-term omega-3 supplementation attenuated kidney function decline versus placebo in post-MI adults."},
    {"intervention_name": "CoQ10", "biomarker_name": "Creatinine", "pathway_code": "RENAL_FILTRATION",
     "effect": "decreases", "evidence_level": "low", "pmid": "39228730",
     "recommendation_intent": "primary",
     "summary": "Crossover RCT in CKD adults studied coenzyme Q10 effects on metabolic and mitochondrial markers alongside renal function."},
]