"""Tier A curated interventions — evidence-backed only, no placeholder padding.

Quality over count: each entry has real compounds, targets, and PMID-linked claims
in tier_a_evidence.py. Grow toward 200 only via evidence validation, not templates.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Herbs (18)
# ---------------------------------------------------------------------------
TIER_A_HERBS: list[dict] = [
    {
        "name": "Boswellia serrata",
        "category": "herb",
        "description": "Indian frankincense resin extract standardized for boswellic acids.",
        "mechanism": "Selectively inhibits 5-LOX, reducing leukotriene synthesis and NF-κB-driven inflammation.",
        "is_regulated": False,
        "compounds": [
            {"name": "AKBA", "primary_target": "5-LOX", "role": "primary active constituent", "pubchem_cid": "6758"},
        ],
        "safety_flags": [{"condition": "pregnancy", "severity": "contraindication", "note": "Insufficient safety data; avoid."}],
        "drug_interactions": [{"drug_name": "Warfarin", "severity": "moderate", "mechanism": "May potentiate anticoagulant effect.", "note": "Monitor INR."}],
    },
    {
        "name": "Ashwagandha",
        "category": "herb",
        "description": "Withania somnifera root extract standardized for withanolides.",
        "mechanism": "Modulates HPA axis activity and GABAergic signaling.",
        "is_regulated": False,
        "compounds": [{"name": "Withanolides", "primary_target": "HPA axis", "role": "primary active constituent class", "pubchem_cid": None}],
        "safety_flags": [{"condition": "pregnancy", "severity": "contraindication", "note": "Avoid in pregnancy."}],
        "drug_interactions": [{"drug_name": "Levothyroxine", "severity": "moderate", "mechanism": "May affect thyroid levels.", "note": "Monitor TSH."}],
    },
    {
        "name": "Milk Thistle",
        "category": "herb",
        "description": "Silybum marianum seed extract standardized for silymarin.",
        "mechanism": "Upregulates Nrf2-mediated antioxidant defenses in hepatocytes.",
        "is_regulated": False,
        "compounds": [{"name": "Silymarin", "primary_target": "Nrf2", "role": "primary active constituent", "pubchem_cid": "5213"}],
        "safety_flags": [],
        "drug_interactions": [],
    },
    {
        "name": "Mastic Gum",
        "category": "herb",
        "description": "Resin from Pistacia lentiscus var. chia, used in gastric health research.",
        "mechanism": "Triterpenic acids exert bacteriostatic effects against H. pylori and support gastric mucosa.",
        "is_regulated": False,
        "compounds": [
            {"name": "Masticadienonic acid", "primary_target": "H. pylori", "role": "primary active constituent", "pubchem_cid": None},
            {"name": "Isomasticadienonic acid", "primary_target": "H. pylori", "role": "active constituent", "pubchem_cid": None},
        ],
        "safety_flags": [{"condition": "pregnancy", "severity": "caution", "note": "Insufficient safety data; discuss with clinician."}],
        "drug_interactions": [],
    },
    {
        "name": "DGL Licorice",
        "category": "herb",
        "description": "Deglycyrrhizinated licorice root extract (Glycyrrhiza glabra).",
        "mechanism": "Supports gastric mucosal integrity; studied as adjunct in H. pylori protocols.",
        "is_regulated": False,
        "compounds": [{"name": "Glabridin", "primary_target": "gastric mucosa", "role": "primary active constituent", "pubchem_cid": "124052"}],
        "safety_flags": [{"condition": "hypertension", "severity": "caution", "note": "Use deglycyrrhizinated form only; full glycyrrhizin raises BP."}],
        "drug_interactions": [],
    },
    {
        "name": "Ginger",
        "category": "herb",
        "description": "Zingiber officinale rhizome extract.",
        "mechanism": "Gingerols inhibit NF-κB and COX pathways; studied for nausea and GI motility.",
        "is_regulated": False,
        "compounds": [{"name": "Gingerol", "primary_target": "NF-κB", "role": "primary active constituent", "pubchem_cid": "442793"}],
        "safety_flags": [{"condition": "pregnancy", "severity": "caution", "note": "Food amounts generally considered safe; high-dose extract requires clinician guidance."}],
        "drug_interactions": [{"drug_name": "Warfarin", "severity": "low", "mechanism": "Possible antiplatelet effect.", "note": None}],
    },

    {
        "name": "Turmeric",
        "category": "herb",
        "description": "Curcuma longa rhizome (turmeric root).",
        "mechanism": "Curcuminoids inhibit NF-κB nuclear translocation and COX-2 expression.",
        "is_regulated": False,
        "compounds": [{"name": "Curcumin", "primary_target": "NF-κB", "role": "primary active constituent", "pubchem_cid": "969516"}],
        "safety_flags": [{"condition": "pregnancy", "severity": "caution", "note": "High-dose extract not well studied in pregnancy."}],
        "drug_interactions": [{"drug_name": "Warfarin", "severity": "moderate", "mechanism": "Antiplatelet activity.", "note": None}],
    },
    {
        "name": "Andrographis",
        "category": "herb",
        "description": "Andrographis paniculata aerial parts extract.",
        "mechanism": "Andrographolide modulates NF-κB and has been studied in upper respiratory infections.",
        "is_regulated": False,
        "compounds": [{"name": "Andrographolide", "primary_target": "NF-κB", "role": "primary active constituent", "pubchem_cid": "5318517"}],
        "safety_flags": [{"condition": "pregnancy", "severity": "contraindication", "note": "Avoid in pregnancy."}],
        "drug_interactions": [],
    },
    {
        "name": "Olive Leaf",
        "category": "herb",
        "description": "Olea europaea leaf extract standardized for oleuropein.",
        "mechanism": "Oleuropein has antimicrobial and antioxidant properties studied in metabolic health.",
        "is_regulated": False,
        "compounds": [{"name": "Oleuropein", "primary_target": "NF-κB", "role": "primary active constituent", "pubchem_cid": "5281544"}],
        "safety_flags": [],
        "drug_interactions": [{"drug_name": "Antihypertensives", "severity": "low", "mechanism": "Possible additive BP lowering.", "note": None}],
    },
    {
        "name": "Rhodiola rosea",
        "category": "herb",
        "description": "Rhodiola rosea root extract standardized for rosavins and salidroside.",
        "mechanism": "Adaptogenic modulation of HPA axis stress response.",
        "is_regulated": False,
        "compounds": [{"name": "Salidroside", "primary_target": "HPA axis", "role": "primary active constituent", "pubchem_cid": "159278"}],
        "safety_flags": [{"condition": "bipolar_disorder", "severity": "caution", "note": "May be activating; use with psychiatric oversight."}],
        "drug_interactions": [],
    },
    {
        "name": "Chamomile",
        "category": "herb",
        "description": "Matricaria chamomilla flower extract.",
        "mechanism": "Apigenin binds GABA-A receptors; studied for GI relaxation and mild anxiolysis.",
        "is_regulated": False,
        "compounds": [{"name": "Apigenin", "primary_target": "GABA-A receptor", "role": "primary active constituent", "pubchem_cid": "5280443"}],
        "safety_flags": [{"condition": "ragweed_allergy", "severity": "caution", "note": "Cross-reactivity possible in Asteraceae allergy."}],
        "drug_interactions": [{"drug_name": "Warfarin", "severity": "moderate", "mechanism": "Case reports of INR elevation.", "note": "Monitor INR."}],
    },
    {
        "name": "Peppermint",
        "category": "herb",
        "description": "Mentha piperita leaf oil or extract.",
        "mechanism": "Menthol relaxes smooth muscle; studied in IBS and functional dyspepsia.",
        "is_regulated": False,
        "compounds": [{"name": "Menthol", "primary_target": "TRPM8", "role": "primary active constituent", "pubchem_cid": "1254"}],
        "safety_flags": [{"condition": "gerd", "severity": "caution", "note": "May worsen reflux in some patients."}],
        "drug_interactions": [],
    },
    {
        "name": "Holy Basil",
        "category": "herb",
        "description": "Ocimum sanctum (tulsi) leaf extract.",
        "mechanism": "Eugenol and ocimumosides modulate cortisol and glucose in stress models.",
        "is_regulated": False,
        "compounds": [{"name": "Eugenol", "primary_target": "HPA axis", "role": "primary active constituent", "pubchem_cid": "3314"}],
        "safety_flags": [],
        "drug_interactions": [],
    },
    {
        "name": "Slippery Elm",
        "category": "herb",
        "description": "Ulmus rubra inner bark mucilage preparation.",
        "mechanism": "Mucilage coats GI mucosa; used traditionally for esophageal and gastric irritation.",
        "is_regulated": False,
        "compounds": [{"name": "Mucilage polysaccharides", "primary_target": "gastric mucosa", "role": "primary active constituent", "pubchem_cid": None}],
        "safety_flags": [],
        "drug_interactions": [{"drug_name": "Oral medications", "severity": "low", "mechanism": "May delay absorption if taken simultaneously.", "note": "Separate by 2 hours."}],
    },
    {
        "name": "Goldenseal",
        "category": "herb",
        "description": "Hydrastis canadensis root extract containing berberine alkaloids.",
        "mechanism": "Berberine inhibits microbial adhesion and modulates AMPK.",
        "is_regulated": False,
        "compounds": [{"name": "Berberine", "primary_target": "AMPK", "role": "primary active constituent", "pubchem_cid": "2353"}],
        "safety_flags": [{"condition": "pregnancy", "severity": "contraindication", "note": "Berberine crosses placenta; avoid."}],
        "drug_interactions": [{"drug_name": "Cyclosporine", "severity": "high", "mechanism": "CYP3A4/P-gp inhibition.", "note": "Avoid without specialist supervision."}],
    },

    {
        "name": "Licorice Root",
        "category": "herb",
        "description": "Full Glycyrrhiza glabra root (contains glycyrrhizin — distinct from DGL).",
        "mechanism": "Glycyrrhizin has mineralocorticoid-like effects; distinct from DGL mucosal applications.",
        "is_regulated": False,
        "compounds": [{"name": "Glycyrrhizin", "primary_target": "11-beta-HSD", "role": "primary active constituent", "pubchem_cid": "14982"}],
        "safety_flags": [{"condition": "hypertension", "severity": "contraindication", "note": "Glycyrrhizin can cause hypokalemic hypertension."}],
        "drug_interactions": [{"drug_name": "Diuretics", "severity": "high", "mechanism": "Additive potassium loss.", "note": "Avoid combination."}],
    },
]

# ---------------------------------------------------------------------------
# Supplements + lifestyle (from hand-authored seed, plus Tier A additions)
# ---------------------------------------------------------------------------
TIER_A_SUPPLEMENTS: list[dict] = [
    {
        "name": "Berberine",
        "category": "supplement",
        "description": "Isoquinoline alkaloid from Berberis species.",
        "mechanism": "Activates AMPK; studied for glycemic and lipid effects and antimicrobial properties.",
        "is_regulated": False,
        "compounds": [{"name": "Berberine hydrochloride", "primary_target": "AMPK", "role": "primary active constituent", "pubchem_cid": "72322"}],
        "safety_flags": [{"condition": "pregnancy", "severity": "contraindication", "note": "Crosses placenta; avoid."}],
        "drug_interactions": [
            {"drug_name": "Metformin", "severity": "moderate", "mechanism": "Additive glucose lowering.", "note": "Monitor for hypoglycemia."},
            {"drug_name": "Cyclosporine", "severity": "high", "mechanism": "CYP3A4/P-gp inhibition.", "note": "Avoid without supervision."},
        ],
    },
    {
        "name": "Omega-3",
        "category": "supplement",
        "description": "EPA/DHA marine or algal oil.",
        "mechanism": "Specialized pro-resolving mediators reduce NF-κB-driven inflammation.",
        "is_regulated": False,
        "compounds": [
            {"name": "EPA", "primary_target": "Pro-resolving mediator synthesis", "role": "primary active constituent", "pubchem_cid": "446284"},
            {"name": "DHA", "primary_target": "Membrane phospholipid remodeling", "role": "primary active constituent", "pubchem_cid": "445580"},
        ],
        "safety_flags": [],
        "drug_interactions": [{"drug_name": "Warfarin", "severity": "moderate", "mechanism": "Additive antiplatelet effect at high doses.", "note": "Monitor INR above 3g/day."}],
    },
    {
        "name": "Alpha Lipoic Acid",
        "category": "supplement",
        "description": "Mitochondrial cofactor and antioxidant (ALA).",
        "mechanism": "Regenerates glutathione; activates AMPK and improves insulin signaling.",
        "is_regulated": False,
        "compounds": [{"name": "R-alpha lipoic acid", "primary_target": "AMPK", "role": "primary active constituent", "pubchem_cid": "6112"}],
        "safety_flags": [],
        "drug_interactions": [{"drug_name": "Insulin/antidiabetics", "severity": "moderate", "mechanism": "Additive glucose lowering.", "note": "Monitor for hypoglycemia."}],
    },
    {
        "name": "Magnesium",
        "category": "supplement",
        "description": "Essential mineral (glycinate/citrate forms preferred).",
        "mechanism": "Cofactor for ATP-dependent enzymes; modulates insulin signaling.",
        "is_regulated": False,
        "compounds": [{"name": "Magnesium glycinate", "primary_target": "NMDA receptor", "role": "bioavailable form", "pubchem_cid": None}],
        "safety_flags": [{"condition": "severe_ckd", "severity": "contraindication", "note": "Risk of hypermagnesemia."}],
        "drug_interactions": [],
    },
    {
        "name": "Vitamin D",
        "category": "supplement",
        "description": "Cholecalciferol (D3) supplementation.",
        "mechanism": "VDR signaling regulates calcium homeostasis and immune function.",
        "is_regulated": False,
        "compounds": [{"name": "Cholecalciferol (D3)", "primary_target": "Vitamin D receptor", "role": "primary active constituent", "pubchem_cid": "5280795"}],
        "safety_flags": [{"condition": "severe_ckd", "severity": "caution", "note": "High-dose D3 may worsen hyperphosphatemia in advanced CKD."}],
        "drug_interactions": [],
    },
    {
        "name": "NAD+ Precursors (NR/NMN)",
        "category": "supplement",
        "description": "Nicotinamide riboside / NMN NAD+ precursors.",
        "mechanism": "Replenishes intracellular NAD+ pools supporting mitochondrial function.",
        "is_regulated": False,
        "compounds": [{"name": "Nicotinamide Riboside", "primary_target": "NAD+ salvage pathway", "role": "NAD+ precursor", "pubchem_cid": "439924"}],
        "safety_flags": [],
        "drug_interactions": [],
    },
    {
        "name": "CoQ10",
        "category": "supplement",
        "description": "Coenzyme Q10 mitochondrial cofactor.",
        "mechanism": "Supports mitochondrial ATP production; depleted by statin therapy.",
        "is_regulated": False,
        "compounds": [{"name": "Ubiquinol", "primary_target": "Mitochondrial electron transport", "role": "reduced form", "pubchem_cid": "5281915"}],
        "safety_flags": [],
        "drug_interactions": [{"drug_name": "Warfarin", "severity": "low", "mechanism": "Structural similarity to vitamin K.", "note": "Monitor INR."}],
    },
    {
        "name": "NAC",
        "category": "supplement",
        "description": "N-acetylcysteine — glutathione precursor.",
        "mechanism": "Replenishes glutathione; studied for oxidative stress and biofilm contexts.",
        "is_regulated": False,
        "compounds": [{"name": "N-acetylcysteine", "primary_target": "glutathione synthesis", "role": "primary active constituent", "pubchem_cid": "12035"}],
        "safety_flags": [],
        "drug_interactions": [{"drug_name": "Nitroglycerin", "severity": "moderate", "mechanism": "May potentiate hypotensive effect.", "note": None}],
    },
    {
        "name": "Zinc Carnosine",
        "category": "supplement",
        "description": "Zinc L-carnosine chelate studied for gastric mucosal support.",
        "mechanism": "Adheres to gastric mucosa and supports ulcer healing in clinical trials.",
        "is_regulated": False,
        "compounds": [{"name": "Zinc L-carnosine", "primary_target": "gastric mucosa", "role": "primary active constituent", "pubchem_cid": None}],
        "safety_flags": [],
        "drug_interactions": [{"drug_name": "Antibiotics", "severity": "low", "mechanism": "Zinc may reduce absorption of fluoroquinolones/tetracyclines.", "note": "Separate by 2 hours."}],
    },
    {
        "name": "Glutamine",
        "category": "supplement",
        "description": "Conditionally essential amino acid for enterocyte fuel.",
        "mechanism": "Primary energy source for intestinal epithelial cells; supports mucosal barrier.",
        "is_regulated": False,
        "compounds": [{"name": "L-Glutamine", "primary_target": "intestinal epithelium", "role": "primary active constituent", "pubchem_cid": "5961"}],
        "safety_flags": [{"condition": "severe_hepatic_encephalopathy", "severity": "contraindication", "note": "May worsen ammonia in advanced liver disease."}],
        "drug_interactions": [],
    },
    {
        "name": "Zinc",
        "category": "supplement",
        "description": "Zinc picolinate or gluconate supplementation.",
        "mechanism": "Cofactor for immune and mucosal repair enzymes.",
        "is_regulated": False,
        "compounds": [{"name": "Zinc gluconate", "primary_target": "zinc-dependent enzymes", "role": "primary active constituent", "pubchem_cid": "443148"}],
        "safety_flags": [{"condition": "copper_deficiency", "severity": "caution", "note": "Chronic high-dose zinc can induce copper deficiency."}],
        "drug_interactions": [],
    },
    {
        "name": "Calcium",
        "category": "supplement",
        "description": "Calcium carbonate or citrate for hypocalcemia repletion.",
        "mechanism": "Restores serum calcium supporting bone mineralization and neuromuscular function.",
        "is_regulated": False,
        "compounds": [{"name": "Calcium citrate", "primary_target": "serum calcium", "role": "bioavailable form", "pubchem_cid": "22410"}],
        "safety_flags": [{"condition": "hypercalcemia", "severity": "contraindication", "note": "Do not supplement when serum calcium is elevated."}],
        "drug_interactions": [{"drug_name": "Levothyroxine", "severity": "moderate", "mechanism": "Calcium reduces thyroid hormone absorption.", "note": "Separate by 4 hours."}],
    },
    {
        "name": "Potassium",
        "category": "supplement",
        "description": "Potassium chloride or citrate for hypokalemia repletion.",
        "mechanism": "Restores serum potassium supporting neuromuscular and cardiac conduction function.",
        "is_regulated": False,
        "compounds": [{"name": "Potassium chloride", "primary_target": "serum potassium", "role": "primary active constituent", "pubchem_cid": "4873"}],
        "safety_flags": [{"condition": "hyperkalemia", "severity": "contraindication", "note": "Do not supplement when serum potassium is elevated or in advanced CKD without monitoring."}],
        "drug_interactions": [{"drug_name": "ACE inhibitors/ARBs", "severity": "moderate", "mechanism": "Additive hyperkalemia risk.", "note": "Monitor serum potassium closely."}],
    },
    {
        "name": "Copper",
        "category": "supplement",
        "description": "Copper bisglycinate or gluconate for confirmed hypocupremia repletion.",
        "mechanism": "Restores serum copper supporting ceruloplasmin synthesis and iron mobilization.",
        "is_regulated": False,
        "compounds": [{"name": "Copper bisglycinate", "primary_target": "serum copper", "role": "bioavailable form", "pubchem_cid": None}],
        "safety_flags": [{"condition": "wilsons_disease", "severity": "contraindication", "note": "Copper accumulation is harmful in Wilson disease."}],
        "drug_interactions": [{"drug_name": "Zinc supplements", "severity": "moderate", "mechanism": "High-dose zinc competes with copper absorption.", "note": "Separate dosing and monitor copper if zinc is co-used."}],
    },
    {
        "name": "Selenium",
        "category": "supplement",
        "description": "Selenomethionine or sodium selenite for confirmed selenium deficiency.",
        "mechanism": "Replenishes selenoproteins supporting antioxidant and thyroid-related enzyme function.",
        "is_regulated": False,
        "compounds": [{"name": "Selenomethionine", "primary_target": "selenoprotein pools", "role": "organic selenium form", "pubchem_cid": "6326970"}],
        "safety_flags": [{"condition": "selenosis_risk", "severity": "caution", "note": "Avoid high-dose selenium when levels are already adequate."}],
        "drug_interactions": [],
    },
    {
        "name": "Vitamin C",
        "category": "supplement",
        "description": "Ascorbic acid supplementation for confirmed vitamin C deficiency.",
        "mechanism": "Replenishes ascorbate pools supporting collagen synthesis and antioxidant defenses.",
        "is_regulated": False,
        "compounds": [{"name": "Ascorbic acid", "primary_target": "plasma ascorbate", "role": "primary active constituent", "pubchem_cid": "54670067"}],
        "safety_flags": [{"condition": "hemochromatosis", "severity": "caution", "note": "High-dose vitamin C may increase iron absorption."}],
        "drug_interactions": [],
    },
    {
        "name": "Vitamin B6",
        "category": "supplement",
        "description": "Pyridoxine (B6) supplementation for confirmed B6 deficiency.",
        "mechanism": "Replenishes pyridoxal phosphate-dependent enzymes in amino acid and one-carbon metabolism.",
        "is_regulated": False,
        "compounds": [{"name": "Pyridoxine HCl", "primary_target": "plasma pyridoxal phosphate", "role": "primary active constituent", "pubchem_cid": "6019"}],
        "safety_flags": [{"condition": "peripheral_neuropathy", "severity": "caution", "note": "Very high-dose B6 may worsen neuropathy symptoms."}],
        "drug_interactions": [{"drug_name": "Levodopa", "severity": "moderate", "mechanism": "B6 may reduce levodopa efficacy without carbidopa.", "note": "Monitor Parkinson symptom control."}],
    },
    {
        "name": "Vitamin B1",
        "category": "supplement",
        "description": "Thiamine supplementation for confirmed B1 deficiency.",
        "mechanism": "Replenishes thiamine pyrophosphate-dependent enzymes in carbohydrate metabolism.",
        "is_regulated": False,
        "compounds": [{"name": "Thiamine HCl", "primary_target": "erythrocyte transketolase activity", "role": "primary active constituent", "pubchem_cid": "1130"}],
        "safety_flags": [],
        "drug_interactions": [],
    },
    {
        "name": "Vitamin B2",
        "category": "supplement",
        "description": "Riboflavin supplementation for confirmed B2 deficiency.",
        "mechanism": "Replenishes FAD/FMN cofactors supporting mitochondrial energy metabolism.",
        "is_regulated": False,
        "compounds": [{"name": "Riboflavin", "primary_target": "erythrocyte glutathione reductase activity", "role": "primary active constituent", "pubchem_cid": "493570"}],
        "safety_flags": [],
        "drug_interactions": [],
    },
    {
        "name": "Vitamin A",
        "category": "supplement",
        "description": "Retinol or beta-carotene supplementation for confirmed vitamin A deficiency.",
        "mechanism": "Replenishes retinol stores supporting vision, mucosal immunity, and epithelial repair.",
        "is_regulated": False,
        "compounds": [{"name": "Retinyl palmitate", "primary_target": "serum retinol", "role": "preformed vitamin A", "pubchem_cid": "5280531"}],
        "safety_flags": [{"condition": "pregnancy", "severity": "caution", "note": "High-dose preformed vitamin A is teratogenic; use clinician-guided dosing."}],
        "drug_interactions": [],
    },
    {
        "name": "Vitamin E",
        "category": "supplement",
        "description": "Alpha-tocopherol supplementation for confirmed vitamin E deficiency.",
        "mechanism": "Replenishes lipid-soluble antioxidant pools protecting membrane polyunsaturated fats.",
        "is_regulated": False,
        "compounds": [{"name": "D-alpha-tocopherol", "primary_target": "serum alpha-tocopherol", "role": "primary active constituent", "pubchem_cid": "14985"}],
        "safety_flags": [{"condition": "anticoagulant_therapy", "severity": "caution", "note": "High-dose vitamin E may increase bleeding risk with anticoagulants."}],
        "drug_interactions": [{"drug_name": "Warfarin", "severity": "moderate", "mechanism": "May potentiate anticoagulant effect at high doses.", "note": "Monitor INR if co-used."}],
    },
    {
        "name": "Vitamin K2",
        "category": "supplement",
        "description": "Menaquinone (MK-7) supplementation for confirmed vitamin K deficiency.",
        "mechanism": "Replenishes vitamin K-dependent carboxylation supporting coagulation and bone matrix proteins.",
        "is_regulated": False,
        "compounds": [{"name": "Menaquinone-7 (MK-7)", "primary_target": "serum vitamin K", "role": "long-acting K2 form", "pubchem_cid": "5284607"}],
        "safety_flags": [{"condition": "anticoagulant_therapy", "severity": "contraindication", "note": "Vitamin K antagonizes warfarin; do not supplement without clinician coordination."}],
        "drug_interactions": [{"drug_name": "Warfarin", "severity": "high", "mechanism": "Vitamin K reduces anticoagulant efficacy.", "note": "Contraindicated without INR monitoring plan."}],
    },
    {
        "name": "Iron",
        "category": "supplement",
        "description": "Ferrous bisglycinate or sulfate for iron repletion.",
        "mechanism": "Replenishes iron stores supporting hemoglobin synthesis.",
        "is_regulated": False,
        "compounds": [{"name": "Ferrous bisglycinate", "primary_target": "iron stores", "role": "bioavailable form", "pubchem_cid": None}],
        "safety_flags": [{"condition": "hemochromatosis", "severity": "contraindication", "note": "Do not supplement without confirmed deficiency."}],
        "drug_interactions": [{"drug_name": "Levothyroxine", "severity": "moderate", "mechanism": "Reduces thyroid hormone absorption.", "note": "Separate by 4 hours."}],
    },
    {
        "name": "Lactoferrin",
        "category": "supplement",
        "description": "Iron-binding glycoprotein from bovine milk or colostrum.",
        "mechanism": "Supports iron absorption and hepcidin modulation; studied for biofilm disruption in infection models.",
        "is_regulated": False,
        "compounds": [{"name": "Bovine lactoferrin", "primary_target": "iron stores", "role": "primary active constituent", "pubchem_cid": None}],
        "safety_flags": [{"condition": "lactose_intolerance", "severity": "caution", "note": "Often derived from dairy; check product source."}],
        "drug_interactions": [],
    },
    {
        "name": "D-Mannose",
        "category": "supplement",
        "description": "Simple sugar studied for recurrent UTI prophylaxis.",
        "mechanism": "Competes with bacterial adhesins for uroepithelial mannose receptors.",
        "is_regulated": False,
        "compounds": [{"name": "D-Mannose", "primary_target": "uropathogen adhesion", "role": "primary active constituent", "pubchem_cid": "6251"}],
        "safety_flags": [{"condition": "diabetes", "severity": "caution", "note": "May affect glycemic load at high doses; monitor glucose."}],
        "drug_interactions": [],
    },
    {
        "name": "Pancreatin",
        "category": "supplement",
        "description": "Pancreatic enzyme supplement (lipase, protease, amylase) for exocrine insufficiency.",
        "mechanism": "Replaces deficient pancreatic digestive enzymes to support macronutrient absorption.",
        "is_regulated": False,
        "compounds": [{"name": "Pancrelipase", "primary_target": "digestive enzyme replacement", "role": "primary active constituent", "pubchem_cid": None}],
        "safety_flags": [{"condition": "pork_allergy", "severity": "contraindication", "note": "Porcine-derived enzymes — avoid if pork protein allergy."}],
        "drug_interactions": [],
    },
    {
        "name": "Colostrum",
        "category": "supplement",
        "description": "Bovine colostrum powder rich in lactoferrin and immunoglobulins.",
        "mechanism": "Provides lactoferrin and secretory IgA supporting mucosal immunity.",
        "is_regulated": False,
        "compounds": [{"name": "Bovine lactoferrin", "primary_target": "GI mucosa", "role": "primary active constituent", "pubchem_cid": None}],
        "safety_flags": [{"condition": "dairy_allergy", "severity": "contraindication", "note": "Avoid if cow's milk protein allergy."}],
        "drug_interactions": [],
    },
    {
        "name": "B12",
        "category": "supplement",
        "description": "Methylcobalamin or cyanocobalamin supplementation.",
        "mechanism": "Cofactor for methionine synthase and homocysteine clearance.",
        "is_regulated": False,
        "compounds": [{"name": "Methylcobalamin", "primary_target": "methionine synthase", "role": "active form", "pubchem_cid": "10898549"}],
        "safety_flags": [],
        "drug_interactions": [{"drug_name": "Metformin", "severity": "low", "mechanism": "Long-term metformin may lower B12.", "note": "Monitor B12 on metformin."}],
    },
    {
        "name": "Folate",
        "category": "supplement",
        "description": "Methylfolate (5-MTHF) or folic acid supplementation.",
        "mechanism": "One-carbon donor for methylation cycle and homocysteine clearance.",
        "is_regulated": False,
        "compounds": [{"name": "L-Methylfolate", "primary_target": "methylation cycle", "role": "active form", "pubchem_cid": "135398586"}],
        "safety_flags": [],
        "drug_interactions": [],
    },
    {
        "name": "Intermittent Fasting",
        "category": "behavior",
        "description": "Time-restricted eating protocol (commonly 16:8).",
        "mechanism": "Activates AMPK and autophagy while suppressing mTOR signaling.",
        "is_regulated": False,
        "compounds": [],
        "safety_flags": [{"condition": "pregnancy", "severity": "caution", "note": "Extended fasting not recommended in pregnancy."}],
        "drug_interactions": [],
    },
    {
        "name": "HIIT",
        "category": "exercise",
        "description": "High-intensity interval training.",
        "mechanism": "Activates AMPK and mitochondrial biogenesis; improves insulin sensitivity.",
        "is_regulated": False,
        "compounds": [],
        "safety_flags": [],
        "drug_interactions": [],
    },
    {
        "name": "Mindfulness-Based Stress Reduction",
        "category": "stress_reduction",
        "description": "Structured meditation/breathwork (MBSR).",
        "mechanism": "Reduces HPA axis reactivity and cortisol output.",
        "is_regulated": False,
        "compounds": [],
        "safety_flags": [],
        "drug_interactions": [],
    },
    {
        "name": "Sleep Hygiene Optimization",
        "category": "sleep",
        "description": "Behavioral protocol for sleep duration and quality.",
        "mechanism": "Restores HPA axis rhythm and insulin sensitivity disrupted by poor sleep.",
        "is_regulated": False,
        "compounds": [],
        "safety_flags": [],
        "drug_interactions": [],
    },
    {
        "name": "Gluten Elimination Diet",
        "category": "behavior",
        "description": "Strict removal of gluten-containing grains for celiac disease management.",
        "mechanism": "Eliminates gliadin exposure driving autoimmune intestinal damage in celiac disease.",
        "is_regulated": False,
        "compounds": [],
        "safety_flags": [],
        "drug_interactions": [],
    },
]

# ---------------------------------------------------------------------------
# Phytochemicals (15)
# ---------------------------------------------------------------------------
TIER_A_PHYTOCHEMICALS: list[dict] = [
    {"name": "Sulforaphane", "category": "phytochemical", "description": "Isothiocyanate from cruciferous glucoraphanin.", "mechanism": "Activates Nrf2 and modulates NF-κB.", "is_regulated": False, "safety_flags": [], "drug_interactions": []},
    {"name": "EGCG", "category": "phytochemical", "description": "Epigallocatechin gallate from green tea.", "mechanism": "AMPK activation and NF-κB inhibition.", "is_regulated": False, "safety_flags": [{"condition": "liver_disease", "severity": "caution", "note": "High-dose extracts rarely hepatotoxic."}], "drug_interactions": []},
    {"name": "Allicin", "category": "phytochemical", "description": "Organosulfur compound from crushed raw garlic.", "mechanism": "NF-κB inhibition and lipid effects.", "is_regulated": False, "safety_flags": [], "drug_interactions": [{"drug_name": "Warfarin", "severity": "moderate", "mechanism": "Antiplatelet activity.", "note": None}]},
    {"name": "Quercetin", "category": "phytochemical", "description": "Flavonol abundant in onions and apples.", "mechanism": "NF-κB and mast cell stabilization.", "is_regulated": False, "safety_flags": [], "drug_interactions": []},
    {"name": "Anthocyanins", "category": "phytochemical", "description": "Polyphenol class from berries and purple produce.", "mechanism": "Nrf2 and endothelial function.", "is_regulated": False, "safety_flags": [], "drug_interactions": []},
    {"name": "Ellagic Acid", "category": "phytochemical", "description": "Polyphenol from pomegranate.", "mechanism": "Nrf2 activation via urolithin metabolites.", "is_regulated": False, "safety_flags": [], "drug_interactions": []},
    {"name": "Lycopene", "category": "phytochemical", "description": "Carotenoid from cooked tomatoes.", "mechanism": "LDL oxidation inhibition.", "is_regulated": False, "safety_flags": [], "drug_interactions": []},
    {"name": "Curcumin", "category": "phytochemical", "description": "Curcuminoid from turmeric.", "mechanism": "NF-κB and COX-2 inhibition.", "is_regulated": False, "safety_flags": [{"condition": "pregnancy", "severity": "caution", "note": "High-dose not well studied in pregnancy."}], "drug_interactions": [{"drug_name": "Warfarin", "severity": "moderate", "mechanism": "Antiplatelet activity.", "note": None}]},
    {"name": "Resveratrol", "category": "phytochemical", "description": "Stilbene from grapes and berries.", "mechanism": "SIRT1 and AMPK modulation.", "is_regulated": False, "safety_flags": [], "drug_interactions": []},
    {"name": "Luteolin", "category": "phytochemical", "description": "Flavone with mast cell stabilizing properties.", "mechanism": "NF-κB inhibition and mast cell modulation.", "is_regulated": False, "safety_flags": [], "drug_interactions": []},
    {"name": "Silymarin", "category": "phytochemical", "description": "Flavonolignan complex from milk thistle.", "mechanism": "Nrf2-mediated hepatocyte protection.", "is_regulated": False, "safety_flags": [], "drug_interactions": []},
    {"name": "Apigenin", "category": "phytochemical", "description": "Flavone from chamomile and parsley.", "mechanism": "GABA-A modulation and anti-inflammatory effects.", "is_regulated": False, "safety_flags": [], "drug_interactions": []},
    {"name": "Piperine", "category": "phytochemical", "description": "Alkaloid from black pepper.", "mechanism": "Bioavailability enhancer via glucuronidation inhibition.", "is_regulated": False, "safety_flags": [], "drug_interactions": [{"drug_name": "Many medications", "severity": "moderate", "mechanism": "CYP and P-gp inhibition.", "note": "May raise drug levels."}]},
    {"name": "Naringenin", "category": "phytochemical", "description": "Flavanone from citrus.", "mechanism": "AMPK and hepatic lipid metabolism.", "is_regulated": False, "safety_flags": [], "drug_interactions": []},
    {"name": "Beta-Carotene", "category": "phytochemical", "description": "Provitamin A carotenoid from carrots.", "mechanism": "Nrf2 activation and vitamin A precursor.", "is_regulated": False, "safety_flags": [{"condition": "smoking", "severity": "contraindication", "note": "Supplement doses increased lung cancer risk in smokers (ATBC trial)."}], "drug_interactions": []},
    {"name": "Gingerol", "category": "phytochemical", "description": "Pungent phenolic compound from ginger.", "mechanism": "NF-κB inhibition and GI motility modulation.", "is_regulated": False, "safety_flags": [], "drug_interactions": []},
]

# ---------------------------------------------------------------------------
# Foods (15)
# ---------------------------------------------------------------------------
TIER_A_FOODS: list[dict] = [
    {"name": "Broccoli Sprouts", "category": "food", "description": "Young cruciferous sprouts — highest dietary sulforaphane precursor content.", "mechanism": None, "is_regulated": False, "safety_flags": [], "drug_interactions": []},
    {"name": "Broccoli", "category": "food", "description": "Brassica oleracea florets.", "mechanism": None, "is_regulated": False, "safety_flags": [], "drug_interactions": []},
    {"name": "Brussels Sprouts", "category": "food", "description": "Brassica oleracea gemmifera.", "mechanism": None, "is_regulated": False, "safety_flags": [], "drug_interactions": []},
    {"name": "Kale", "category": "food", "description": "Brassica oleracea acephala.", "mechanism": None, "is_regulated": False, "safety_flags": [], "drug_interactions": []},
    {"name": "Garlic", "category": "food", "description": "Culinary whole garlic bulb.", "mechanism": None, "is_regulated": False, "safety_flags": [], "drug_interactions": []},
    {"name": "Turmeric Root", "category": "food", "description": "Fresh or dried turmeric rhizome for cooking.", "mechanism": None, "is_regulated": False, "safety_flags": [], "drug_interactions": []},
    {"name": "Green Tea", "category": "food", "description": "Brewed Camellia sinensis tea.", "mechanism": None, "is_regulated": False, "safety_flags": [], "drug_interactions": []},
    {"name": "Blueberries", "category": "food", "description": "Vaccinium corymbosum berries.", "mechanism": None, "is_regulated": False, "safety_flags": [], "drug_interactions": []},
    {"name": "Blackberries", "category": "food", "description": "Rubus fruticosus berries.", "mechanism": None, "is_regulated": False, "safety_flags": [], "drug_interactions": []},
    {"name": "Pomegranate", "category": "food", "description": "Punica granatum arils or juice.", "mechanism": None, "is_regulated": False, "safety_flags": [], "drug_interactions": []},
    {"name": "Cooked Tomatoes", "category": "food", "description": "Heat-processed tomato products.", "mechanism": None, "is_regulated": False, "safety_flags": [], "drug_interactions": []},
    {"name": "Onions", "category": "food", "description": "Allium cepa bulbs.", "mechanism": None, "is_regulated": False, "safety_flags": [], "drug_interactions": []},
    {"name": "Ginger Root", "category": "food", "description": "Culinary ginger rhizome.", "mechanism": None, "is_regulated": False, "safety_flags": [], "drug_interactions": []},
    {"name": "Carrots", "category": "food", "description": "Daucus carota root.", "mechanism": None, "is_regulated": False, "safety_flags": [], "drug_interactions": []},
    {"name": "Spinach", "category": "food", "description": "Spinacia oleracea leafy green.", "mechanism": None, "is_regulated": False, "safety_flags": [], "drug_interactions": []},
]

# Curated food → compound links (no auto-generated padding).
TIER_A_FOOD_COMPOUND_SOURCES: list[tuple] = [
    ("Broccoli Sprouts", "Sulforaphane", "high", "1/4 cup fresh sprouts", "Roughly 10-100x glucoraphanin vs mature broccoli."),
    ("Broccoli", "Sulforaphane", "moderate", "1 cup steamed", "Light steaming preserves myrosinase."),
    ("Brussels Sprouts", "Sulforaphane", "moderate", "1 cup cooked", None),
    ("Kale", "Sulforaphane", "low", "1-2 cups raw", None),
    ("Garlic", "Allicin", "high", "1-2 cloves crushed raw", "Allicin forms after crushing; cooking deactivates allinase."),
    ("Turmeric Root", "Curcumin", "high", "1 tsp in cooking", None),
    ("Green Tea", "EGCG", "high", "2-3 cups brewed", "Brewed tea; extracts carry different safety data."),
    ("Blueberries", "Anthocyanins", "high", "1 cup fresh", None),
    ("Blackberries", "Anthocyanins", "high", "1 cup fresh", None),
    ("Pomegranate", "Ellagic Acid", "high", "1 cup arils or 8oz juice", None),
    ("Cooked Tomatoes", "Lycopene", "high", "1/2 cup tomato sauce", "Cooking with oil increases bioavailability."),
    ("Onions", "Quercetin", "moderate", "1/2 cup raw", "Red/yellow onions contain more quercetin."),
    ("Ginger Root", "Gingerol", "moderate", "1 tbsp fresh grated", None),
    ("Carrots", "Beta-Carotene", "high", "1 cup raw", None),
    ("Spinach", "Luteolin", "low", "2 cups raw", None),
]

TIER_A_INTERVENTIONS: list[dict] = TIER_A_HERBS + TIER_A_SUPPLEMENTS